<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 9 Linear mixed-effects models | An R companion to Statistics: data analysis and modelling</title>
  <meta name="description" content="A book about how to use R related to the book Statistics: Data analysis and modelling." />
  <meta name="generator" content="bookdown 0.24 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 9 Linear mixed-effects models | An R companion to Statistics: data analysis and modelling" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="A book about how to use R related to the book Statistics: Data analysis and modelling." />
  <meta name="github-repo" content="mspeekenbrink/sdam-book" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 9 Linear mixed-effects models | An R companion to Statistics: data analysis and modelling" />
  
  <meta name="twitter:description" content="A book about how to use R related to the book Statistics: Data analysis and modelling." />
  

<meta name="author" content="Maarten Speekenbrink" />


<meta name="date" content="2021-12-08" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="repeated-measures-anova.html"/>
<link rel="next" href="bayesian-hypothesis-testing-with-bayes-factors.html"/>
<script src="book_assets/header-attrs-2.11/header-attrs.js"></script>
<script src="book_assets/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="book_assets/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="book_assets/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="book_assets/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="book_assets/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="book_assets/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="book_assets/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="book_assets/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="book_assets/anchor-sections-1.0.1/anchor-sections.css" rel="stylesheet" />
<script src="book_assets/anchor-sections-1.0.1/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a>
<ul>
<li class="chapter" data-level="0.1" data-path="index.html"><a href="index.html#acknowledgements"><i class="fa fa-check"></i><b>0.1</b> Acknowledgements</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="introduction.html"><a href="introduction.html"><i class="fa fa-check"></i><b>1</b> Introduction</a>
<ul>
<li class="chapter" data-level="1.1" data-path="introduction.html"><a href="introduction.html#what-is-r"><i class="fa fa-check"></i><b>1.1</b> What is R?</a></li>
<li class="chapter" data-level="1.2" data-path="introduction.html"><a href="introduction.html#getting-started"><i class="fa fa-check"></i><b>1.2</b> Getting started</a>
<ul>
<li class="chapter" data-level="1.2.1" data-path="introduction.html"><a href="introduction.html#download-r"><i class="fa fa-check"></i><b>1.2.1</b> Download R</a></li>
<li class="chapter" data-level="1.2.2" data-path="introduction.html"><a href="introduction.html#download-r-studio"><i class="fa fa-check"></i><b>1.2.2</b> Download R Studio</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="introduction.html"><a href="introduction.html#working-with-rstudio"><i class="fa fa-check"></i><b>1.3</b> Working with RStudio</a></li>
<li class="chapter" data-level="1.4" data-path="introduction.html"><a href="introduction.html#installing-packages"><i class="fa fa-check"></i><b>1.4</b> Installing packages</a>
<ul>
<li class="chapter" data-level="1.4.1" data-path="introduction.html"><a href="introduction.html#installing-the-sdamr-package"><i class="fa fa-check"></i><b>1.4.1</b> Installing the <code>sdamr</code> package</a></li>
</ul></li>
<li class="chapter" data-level="1.5" data-path="introduction.html"><a href="introduction.html#getting-help"><i class="fa fa-check"></i><b>1.5</b> Getting help</a></li>
<li class="chapter" data-level="1.6" data-path="introduction.html"><a href="introduction.html#first-steps-r-as-a-calculator"><i class="fa fa-check"></i><b>1.6</b> First steps: R as a calculator</a></li>
<li class="chapter" data-level="1.7" data-path="introduction.html"><a href="introduction.html#data"><i class="fa fa-check"></i><b>1.7</b> Data</a>
<ul>
<li class="chapter" data-level="1.7.1" data-path="introduction.html"><a href="introduction.html#data-types"><i class="fa fa-check"></i><b>1.7.1</b> Data types</a></li>
<li class="chapter" data-level="1.7.2" data-path="introduction.html"><a href="introduction.html#objects"><i class="fa fa-check"></i><b>1.7.2</b> Objects</a></li>
<li class="chapter" data-level="1.7.3" data-path="introduction.html"><a href="introduction.html#importing-data"><i class="fa fa-check"></i><b>1.7.3</b> Importing data</a></li>
</ul></li>
<li class="chapter" data-level="1.8" data-path="introduction.html"><a href="introduction.html#exploring-data-descriptive-statistics"><i class="fa fa-check"></i><b>1.8</b> Exploring data: Descriptive statistics</a></li>
<li class="chapter" data-level="1.9" data-path="introduction.html"><a href="introduction.html#exploring-data-creating-plots"><i class="fa fa-check"></i><b>1.9</b> Exploring data: Creating plots</a>
<ul>
<li class="chapter" data-level="1.9.1" data-path="introduction.html"><a href="introduction.html#histogram"><i class="fa fa-check"></i><b>1.9.1</b> Histogram</a></li>
<li class="chapter" data-level="1.9.2" data-path="introduction.html"><a href="introduction.html#boxplot"><i class="fa fa-check"></i><b>1.9.2</b> Boxplot</a></li>
</ul></li>
<li class="chapter" data-level="1.10" data-path="introduction.html"><a href="introduction.html#scatterplot"><i class="fa fa-check"></i><b>1.10</b> Scatterplot</a></li>
<li class="chapter" data-level="1.11" data-path="introduction.html"><a href="introduction.html#raincloud-plot"><i class="fa fa-check"></i><b>1.11</b> Raincloud plot</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="statistical-modelling.html"><a href="statistical-modelling.html"><i class="fa fa-check"></i><b>2</b> Statistical modelling</a>
<ul>
<li class="chapter" data-level="2.1" data-path="statistical-modelling.html"><a href="statistical-modelling.html#distributions"><i class="fa fa-check"></i><b>2.1</b> Distributions</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="statistical-modelling.html"><a href="statistical-modelling.html#generating-random-data"><i class="fa fa-check"></i><b>2.1.1</b> Generating random data</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="statistical-modelling.html"><a href="statistical-modelling.html#estimation"><i class="fa fa-check"></i><b>2.2</b> Estimation</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="statistical-modelling.html"><a href="statistical-modelling.html#the-likelihood-function"><i class="fa fa-check"></i><b>2.2.1</b> The likelihood function</a></li>
<li class="chapter" data-level="2.2.2" data-path="statistical-modelling.html"><a href="statistical-modelling.html#calculating-the-likelihood-ratio"><i class="fa fa-check"></i><b>2.2.2</b> Calculating the likelihood ratio</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="statistical-modelling.html"><a href="statistical-modelling.html#hypothesis-testing-directly-with-the-binomial-distribution"><i class="fa fa-check"></i><b>2.3</b> Hypothesis testing directly with the binomial distribution</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="the-one-sample-t-test.html"><a href="the-one-sample-t-test.html"><i class="fa fa-check"></i><b>3</b> The one-sample t-test</a>
<ul>
<li class="chapter" data-level="3.1" data-path="the-one-sample-t-test.html"><a href="the-one-sample-t-test.html#missing-values"><i class="fa fa-check"></i><b>3.1</b> Missing values</a></li>
<li class="chapter" data-level="3.2" data-path="the-one-sample-t-test.html"><a href="the-one-sample-t-test.html#selecting-subsets-of-data"><i class="fa fa-check"></i><b>3.2</b> Selecting subsets of data</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="the-one-sample-t-test.html"><a href="the-one-sample-t-test.html#indexing-variables"><i class="fa fa-check"></i><b>3.2.1</b> Indexing variables</a></li>
<li class="chapter" data-level="3.2.2" data-path="the-one-sample-t-test.html"><a href="the-one-sample-t-test.html#the-subset-function"><i class="fa fa-check"></i><b>3.2.2</b> The <code>subset</code> function</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="the-one-sample-t-test.html"><a href="the-one-sample-t-test.html#one-sample-t-test"><i class="fa fa-check"></i><b>3.3</b> One-sample t-test</a></li>
<li class="chapter" data-level="3.4" data-path="the-one-sample-t-test.html"><a href="the-one-sample-t-test.html#effect-size"><i class="fa fa-check"></i><b>3.4</b> Effect size</a></li>
<li class="chapter" data-level="3.5" data-path="the-one-sample-t-test.html"><a href="the-one-sample-t-test.html#nonparametric-bootstrap"><i class="fa fa-check"></i><b>3.5</b> Nonparametric bootstrap</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="regression.html"><a href="regression.html"><i class="fa fa-check"></i><b>4</b> Regression</a>
<ul>
<li class="chapter" data-level="4.1" data-path="regression.html"><a href="regression.html#estimating-an-testing-a-simple-regression-model"><i class="fa fa-check"></i><b>4.1</b> Estimating an testing a simple regression model</a></li>
<li class="chapter" data-level="4.2" data-path="regression.html"><a href="regression.html#model-comparisons"><i class="fa fa-check"></i><b>4.2</b> Model comparisons</a></li>
<li class="chapter" data-level="4.3" data-path="regression.html"><a href="regression.html#estimating-and-testing-a-multiple-regression-model"><i class="fa fa-check"></i><b>4.3</b> Estimating and testing a multiple regression model</a></li>
<li class="chapter" data-level="4.4" data-path="regression.html"><a href="regression.html#residuals-and-predicted-values"><i class="fa fa-check"></i><b>4.4</b> Residuals and predicted values</a></li>
<li class="chapter" data-level="4.5" data-path="regression.html"><a href="regression.html#plotting-pairwise-scatterplots-for-many-variables"><i class="fa fa-check"></i><b>4.5</b> Plotting pairwise scatterplots for many variables</a></li>
<li class="chapter" data-level="4.6" data-path="regression.html"><a href="regression.html#multicollinearity-and-outlier-detection"><i class="fa fa-check"></i><b>4.6</b> Multicollinearity and outlier detection</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="moderation-and-mediation.html"><a href="moderation-and-mediation.html"><i class="fa fa-check"></i><b>5</b> Moderation and mediation</a>
<ul>
<li class="chapter" data-level="5.1" data-path="moderation-and-mediation.html"><a href="moderation-and-mediation.html#moderation-in-linear-models"><i class="fa fa-check"></i><b>5.1</b> Moderation in linear models</a>
<ul>
<li class="chapter" data-level="5.1.1" data-path="moderation-and-mediation.html"><a href="moderation-and-mediation.html#a-bit-about-namespaces"><i class="fa fa-check"></i><b>5.1.1</b> A bit about namespaces</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="moderation-and-mediation.html"><a href="moderation-and-mediation.html#centering"><i class="fa fa-check"></i><b>5.2</b> Centering</a></li>
<li class="chapter" data-level="5.3" data-path="moderation-and-mediation.html"><a href="moderation-and-mediation.html#mediation-analysis"><i class="fa fa-check"></i><b>5.3</b> Mediation analysis</a>
<ul>
<li class="chapter" data-level="5.3.1" data-path="moderation-and-mediation.html"><a href="moderation-and-mediation.html#causal-steps"><i class="fa fa-check"></i><b>5.3.1</b> Causal steps</a></li>
<li class="chapter" data-level="5.3.2" data-path="moderation-and-mediation.html"><a href="moderation-and-mediation.html#investigating-the-moderated-indirect-effect-with-a-bootstrap-test"><i class="fa fa-check"></i><b>5.3.2</b> Investigating the moderated (indirect) effect with a bootstrap test</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="contrast-coding-and-oneway-anova.html"><a href="contrast-coding-and-oneway-anova.html"><i class="fa fa-check"></i><b>6</b> Contrast coding and oneway ANOVA</a>
<ul>
<li class="chapter" data-level="6.1" data-path="contrast-coding-and-oneway-anova.html"><a href="contrast-coding-and-oneway-anova.html#computing-contrast-coded-predictors"><i class="fa fa-check"></i><b>6.1</b> Computing contrast-coded predictors</a></li>
<li class="chapter" data-level="6.2" data-path="contrast-coding-and-oneway-anova.html"><a href="contrast-coding-and-oneway-anova.html#assigning-contrasts-to-factors"><i class="fa fa-check"></i><b>6.2</b> Assigning contrasts to factors</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="contrast-coding-and-oneway-anova.html"><a href="contrast-coding-and-oneway-anova.html#default-coding-schemes"><i class="fa fa-check"></i><b>6.2.1</b> Default coding schemes</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="factorial-anova.html"><a href="factorial-anova.html"><i class="fa fa-check"></i><b>7</b> Factorial ANOVA</a>
<ul>
<li class="chapter" data-level="7.1" data-path="factorial-anova.html"><a href="factorial-anova.html#rainclouds-for-factorial-designs"><i class="fa fa-check"></i><b>7.1</b> Rainclouds for factorial designs</a></li>
<li class="chapter" data-level="7.2" data-path="factorial-anova.html"><a href="factorial-anova.html#formulating-estimating-and-testing-a-factorial-anova"><i class="fa fa-check"></i><b>7.2</b> Formulating, estimating, and testing a factorial ANOVA</a>
<ul>
<li class="chapter" data-level="7.2.1" data-path="factorial-anova.html"><a href="factorial-anova.html#a-threeway-anova"><i class="fa fa-check"></i><b>7.2.1</b> A threeway ANOVA</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="factorial-anova.html"><a href="factorial-anova.html#type-1-2-and-3-sums-of-squares"><i class="fa fa-check"></i><b>7.3</b> Type 1, 2, and 3 Sums of Squares</a></li>
<li class="chapter" data-level="7.4" data-path="factorial-anova.html"><a href="factorial-anova.html#planned-comparisons-and-post-hoc-tests-with-emmeans"><i class="fa fa-check"></i><b>7.4</b> Planned comparisons and post-hoc tests with <code>emmeans</code></a>
<ul>
<li class="chapter" data-level="7.4.1" data-path="factorial-anova.html"><a href="factorial-anova.html#adjusted-p-values"><i class="fa fa-check"></i><b>7.4.1</b> Adjusted p-values</a></li>
</ul></li>
<li class="chapter" data-level="7.5" data-path="factorial-anova.html"><a href="factorial-anova.html#testing-general-contrasts-with-emmeans"><i class="fa fa-check"></i><b>7.5</b> Testing general contrasts with <code>emmeans</code></a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="repeated-measures-anova.html"><a href="repeated-measures-anova.html"><i class="fa fa-check"></i><b>8</b> Repeated-measures ANOVA</a>
<ul>
<li class="chapter" data-level="8.1" data-path="repeated-measures-anova.html"><a href="repeated-measures-anova.html#long-and-wide-data"><i class="fa fa-check"></i><b>8.1</b> Long and wide data</a></li>
<li class="chapter" data-level="8.2" data-path="repeated-measures-anova.html"><a href="repeated-measures-anova.html#repeated-measures-anova-with-separate-glms"><i class="fa fa-check"></i><b>8.2</b> Repeated-measures ANOVA with separate GLMs</a>
<ul>
<li class="chapter" data-level="8.2.1" data-path="repeated-measures-anova.html"><a href="repeated-measures-anova.html#computing-within-subjects-composite-scores"><i class="fa fa-check"></i><b>8.2.1</b> Computing within-subjects composite scores</a></li>
<li class="chapter" data-level="8.2.2" data-path="repeated-measures-anova.html"><a href="repeated-measures-anova.html#performing-a-repeated-measures-anova-with-separate-models"><i class="fa fa-check"></i><b>8.2.2</b> Performing a repeated-measures ANOVA with separate models</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="repeated-measures-anova.html"><a href="repeated-measures-anova.html#repeated-measures-anova-with-the-car-package"><i class="fa fa-check"></i><b>8.3</b> Repeated-measures ANOVA with the <code>car</code> package</a></li>
<li class="chapter" data-level="8.4" data-path="repeated-measures-anova.html"><a href="repeated-measures-anova.html#repeated-measures-anova-with-the-afex-package"><i class="fa fa-check"></i><b>8.4</b> Repeated-measures ANOVA with the <code>afex</code> package</a></li>
<li class="chapter" data-level="8.5" data-path="repeated-measures-anova.html"><a href="repeated-measures-anova.html#contrasts-with-the-emmeans-package"><i class="fa fa-check"></i><b>8.5</b> Contrasts with the <code>emmeans</code> package</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="linear-mixed-effects-models.html"><a href="linear-mixed-effects-models.html"><i class="fa fa-check"></i><b>9</b> Linear mixed-effects models</a>
<ul>
<li class="chapter" data-level="9.1" data-path="linear-mixed-effects-models.html"><a href="linear-mixed-effects-models.html#formulating-and-estimating-linear-mixed-effects-models-with-lme4"><i class="fa fa-check"></i><b>9.1</b> Formulating and estimating linear mixed-effects models with <code>lme4</code></a>
<ul>
<li class="chapter" data-level="9.1.1" data-path="linear-mixed-effects-models.html"><a href="linear-mixed-effects-models.html#random-intercepts-model"><i class="fa fa-check"></i><b>9.1.1</b> Random intercepts model</a></li>
<li class="chapter" data-level="9.1.2" data-path="linear-mixed-effects-models.html"><a href="linear-mixed-effects-models.html#visually-assessing-model-assumptions"><i class="fa fa-check"></i><b>9.1.2</b> Visually assessing model assumptions</a></li>
<li class="chapter" data-level="9.1.3" data-path="linear-mixed-effects-models.html"><a href="linear-mixed-effects-models.html#random-intercepts-and-slopes"><i class="fa fa-check"></i><b>9.1.3</b> Random intercepts and slopes</a></li>
<li class="chapter" data-level="9.1.4" data-path="linear-mixed-effects-models.html"><a href="linear-mixed-effects-models.html#likelihood-ratio-test-with-the-anova-function"><i class="fa fa-check"></i><b>9.1.4</b> Likelihood ratio test with the <code>anova</code> function</a></li>
<li class="chapter" data-level="9.1.5" data-path="linear-mixed-effects-models.html"><a href="linear-mixed-effects-models.html#confidence-intervals"><i class="fa fa-check"></i><b>9.1.5</b> Confidence intervals</a></li>
<li class="chapter" data-level="9.1.6" data-path="linear-mixed-effects-models.html"><a href="linear-mixed-effects-models.html#plotting-model-predictions"><i class="fa fa-check"></i><b>9.1.6</b> Plotting model predictions</a></li>
</ul></li>
<li class="chapter" data-level="9.2" data-path="linear-mixed-effects-models.html"><a href="linear-mixed-effects-models.html#obtaining-p-values-with-afexmixed"><i class="fa fa-check"></i><b>9.2</b> Obtaining p-values with <code>afex::mixed</code></a></li>
<li class="chapter" data-level="9.3" data-path="linear-mixed-effects-models.html"><a href="linear-mixed-effects-models.html#crossed-random-effects"><i class="fa fa-check"></i><b>9.3</b> Crossed random effects</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="bayesian-hypothesis-testing-with-bayes-factors.html"><a href="bayesian-hypothesis-testing-with-bayes-factors.html"><i class="fa fa-check"></i><b>10</b> Bayesian hypothesis testing with Bayes Factors</a>
<ul>
<li class="chapter" data-level="10.1" data-path="bayesian-hypothesis-testing-with-bayes-factors.html"><a href="bayesian-hypothesis-testing-with-bayes-factors.html#the-bayesfactor-package"><i class="fa fa-check"></i><b>10.1</b> The <code>BayesFactor</code> package</a>
<ul>
<li class="chapter" data-level="10.1.1" data-path="bayesian-hypothesis-testing-with-bayes-factors.html"><a href="bayesian-hypothesis-testing-with-bayes-factors.html#a-bayesian-one-sample-t-test"><i class="fa fa-check"></i><b>10.1.1</b> A Bayesian one-sample t-test</a></li>
<li class="chapter" data-level="10.1.2" data-path="bayesian-hypothesis-testing-with-bayes-factors.html"><a href="bayesian-hypothesis-testing-with-bayes-factors.html#a-bayesian-two-sample-t-test"><i class="fa fa-check"></i><b>10.1.2</b> A Bayesian two-sample t-test</a></li>
<li class="chapter" data-level="10.1.3" data-path="bayesian-hypothesis-testing-with-bayes-factors.html"><a href="bayesian-hypothesis-testing-with-bayes-factors.html#a-bayesian-anova"><i class="fa fa-check"></i><b>10.1.3</b> A Bayesian ANOVA</a></li>
<li class="chapter" data-level="10.1.4" data-path="bayesian-hypothesis-testing-with-bayes-factors.html"><a href="bayesian-hypothesis-testing-with-bayes-factors.html#bayesian-regression-and-ancova"><i class="fa fa-check"></i><b>10.1.4</b> Bayesian regression and ANCOVA</a></li>
<li class="chapter" data-level="10.1.5" data-path="bayesian-hypothesis-testing-with-bayes-factors.html"><a href="bayesian-hypothesis-testing-with-bayes-factors.html#bayesian-repeated-measures-anova"><i class="fa fa-check"></i><b>10.1.5</b> Bayesian repeated-measures ANOVA</a></li>
<li class="chapter" data-level="10.1.6" data-path="bayesian-hypothesis-testing-with-bayes-factors.html"><a href="bayesian-hypothesis-testing-with-bayes-factors.html#parameter-estimates"><i class="fa fa-check"></i><b>10.1.6</b> Parameter estimates</a></li>
<li class="chapter" data-level="10.1.7" data-path="bayesian-hypothesis-testing-with-bayes-factors.html"><a href="bayesian-hypothesis-testing-with-bayes-factors.html#highest-density-interval"><i class="fa fa-check"></i><b>10.1.7</b> Highest-density interval</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="11" data-path="reproducible-reports-with-rmarkdown.html"><a href="reproducible-reports-with-rmarkdown.html"><i class="fa fa-check"></i><b>11</b> Reproducible reports with RMarkdown</a>
<ul>
<li class="chapter" data-level="11.1" data-path="reproducible-reports-with-rmarkdown.html"><a href="reproducible-reports-with-rmarkdown.html#yaml-headers"><i class="fa fa-check"></i><b>11.1</b> YAML headers</a></li>
<li class="chapter" data-level="11.2" data-path="reproducible-reports-with-rmarkdown.html"><a href="reproducible-reports-with-rmarkdown.html#markdown-syntax"><i class="fa fa-check"></i><b>11.2</b> Markdown syntax</a>
<ul>
<li class="chapter" data-level="11.2.1" data-path="reproducible-reports-with-rmarkdown.html"><a href="reproducible-reports-with-rmarkdown.html#inline-formatting"><i class="fa fa-check"></i><b>11.2.1</b> Inline formatting</a></li>
<li class="chapter" data-level="11.2.2" data-path="reproducible-reports-with-rmarkdown.html"><a href="reproducible-reports-with-rmarkdown.html#block-level-elements"><i class="fa fa-check"></i><b>11.2.2</b> Block-level elements</a></li>
<li class="chapter" data-level="11.2.3" data-path="reproducible-reports-with-rmarkdown.html"><a href="reproducible-reports-with-rmarkdown.html#math-expressions"><i class="fa fa-check"></i><b>11.2.3</b> Math expressions</a></li>
</ul></li>
<li class="chapter" data-level="11.3" data-path="reproducible-reports-with-rmarkdown.html"><a href="reproducible-reports-with-rmarkdown.html#r-code"><i class="fa fa-check"></i><b>11.3</b> R code chunks and inline R code</a>
<ul>
<li class="chapter" data-level="11.3.1" data-path="reproducible-reports-with-rmarkdown.html"><a href="reproducible-reports-with-rmarkdown.html#figures"><i class="fa fa-check"></i><b>11.3.1</b> Figures</a></li>
<li class="chapter" data-level="11.3.2" data-path="reproducible-reports-with-rmarkdown.html"><a href="reproducible-reports-with-rmarkdown.html#tables"><i class="fa fa-check"></i><b>11.3.2</b> Tables</a></li>
</ul></li>
<li class="chapter" data-level="11.4" data-path="reproducible-reports-with-rmarkdown.html"><a href="reproducible-reports-with-rmarkdown.html#apa-documents-with-papaja"><i class="fa fa-check"></i><b>11.4</b> APA documents with <code>papaja</code></a>
<ul>
<li class="chapter" data-level="11.4.1" data-path="reproducible-reports-with-rmarkdown.html"><a href="reproducible-reports-with-rmarkdown.html#installation"><i class="fa fa-check"></i><b>11.4.1</b> Installation</a></li>
<li class="chapter" data-level="11.4.2" data-path="reproducible-reports-with-rmarkdown.html"><a href="reproducible-reports-with-rmarkdown.html#how-to-use-papaja"><i class="fa fa-check"></i><b>11.4.2</b> How to use papaja</a></li>
<li class="chapter" data-level="11.4.3" data-path="reproducible-reports-with-rmarkdown.html"><a href="reproducible-reports-with-rmarkdown.html#getting-help-1"><i class="fa fa-check"></i><b>11.4.3</b> Getting help</a></li>
<li class="chapter" data-level="11.4.4" data-path="reproducible-reports-with-rmarkdown.html"><a href="reproducible-reports-with-rmarkdown.html#other-related-r-packages"><i class="fa fa-check"></i><b>11.4.4</b> Other related R packages</a></li>
</ul></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">An R companion to Statistics: data analysis and modelling</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="linear-mixed-effects-models" class="section level1" number="9">
<h1><span class="header-section-number">Chapter 9</span> Linear mixed-effects models</h1>
<p>In this Chapter, we will look at how to estimate and perform hypothesis tests for linear mixed-effects models. The main workhorse for estimating linear mixed-effects models is the <code>lme4</code> package <span class="citation">(<a href="#ref-R-lme4" role="doc-biblioref">Bates et al. 2021</a>)</span>. This package allows you to formulate a wide variety of mixed-effects and multilevel models through an extension of the R formula syntax. It is a really good package. But the main author of the package, Douglas Bates, has chosen not to provide <span class="math inline">\(p\)</span>-values for the model parameters. We will therefore also consider the <code>afex</code> package, which provides an interface to the two main approximations (Kenward-Roger and Satterthwaite) to provide the degrees of freedom to compute <span class="math inline">\(p\)</span>-values for <span class="math inline">\(F\)</span> tests. While the <code>mixed</code> function it provides is in principle all you need to estimate the models <em>and</em> get the estimates, I think it is useful to also understand the underlying <code>lme4</code> package <span class="citation">(<a href="#ref-R-lme4" role="doc-biblioref">Bates et al. 2021</a>)</span>, so we will start with a discussion of this, and then move to the <code>afex</code> package <span class="citation">(<a href="#ref-R-afex" role="doc-biblioref">Singmann et al. 2021</a>)</span>. If you install the <code>afex</code> package, it will install quite a few other packages on which it relies. So to get all the required packages for this chapter, you can just type</p>
<div class="sourceCode" id="cb403"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb403-1"><a href="linear-mixed-effects-models.html#cb403-1" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">&quot;afex&quot;</span>)</span></code></pre></div>
<p>In the R package, and you should have everything you need.</p>
<div id="formulating-and-estimating-linear-mixed-effects-models-with-lme4" class="section level2" number="9.1">
<h2><span class="header-section-number">9.1</span> Formulating and estimating linear mixed-effects models with <code>lme4</code></h2>
<p>The gold standard for fitting linear mixed-effects models in R is the <code>lmer()</code> (for <code>l</code>inear <code>m</code>ixed-<code>e</code>ffects <code>r</code>egression) in the <code>lme4</code> package. This function takes the following arguments (amongst others, for the full list of arguments, see <code>?lmer</code>):</p>
<ul>
<li><code>formula</code>: a two-sided linear formula describing both the fixed-effects and random-effects part of the model, with the response on the left of the <code>~</code> operator and predictors and random effects on the right-hand side of the <code>~</code> operator.</li>
<li><code>data</code>: A <code>data.frame</code>, which needs to be in the so-called “long” format, with a single row per observation. This may be different from what you might be used to when dealing with repeated-measures. A repeated-measures ANOVA in SPSS requires data in the “wide” format, where you use columns for the different repeated measures. Data in the “wide” format has a single row for each participants. In the “long” format, you will have multiple rows for the data from a single grouping level (e.g., participant, lab, etc.).<br />
</li>
<li><code>REML</code>: A logical variable whether to estimate the model with restricted maximum likelihood (<code>REML = TRUE</code>, the default) or with maximum likelihood (<code>REML = FALSE</code>).</li>
</ul>
<p>As correct use of the formula interface is vital, let’s first consider again how the formula interface works in general. Formulas allow you to specify a linear model succinctly (and by default, any model created with a formula will include an intercept, unless explicitly removed). Here are some examples (adapted from <span class="citation"><a href="#ref-Singmann2019-mixed" role="doc-biblioref">Singmann and Kellen</a> (<a href="#ref-Singmann2019-mixed" role="doc-biblioref">2019</a>)</span>):</p>
<table>
<colgroup>
<col width="12%" />
<col width="88%" />
</colgroup>
<thead>
<tr class="header">
<th>Formula</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>a + b</code></td>
<td>main effects of <code>a</code> and <code>b</code> (and no interaction)</td>
</tr>
<tr class="even">
<td><code>a:b</code></td>
<td>only interaction of <code>a</code> and <code>b</code> (and no main effects)</td>
</tr>
<tr class="odd">
<td><code>a * b</code></td>
<td>main effects and interaction of <code>a</code> and <code>b</code> (expands to: <code>a + b + a:b</code>)</td>
</tr>
<tr class="even">
<td><code>(a+b+c)^2</code></td>
<td>main effects and two-way interactions, but no three-way interaction (expands to: <code>a + b + c + a:b + b:c + a:c</code>)</td>
</tr>
<tr class="odd">
<td><code>(a+b)*c</code></td>
<td>all main effects and pairwise interactions between <code>c</code> and <code>a</code> or <code>b</code> (expands to: <code>a + b + c + a:c + b:c</code>)</td>
</tr>
<tr class="even">
<td><code>0 + a</code></td>
<td><code>0</code> suppresses the intercept resulting in a model that has one parameter per level of <code>a</code> (identical to: <code>a - 1</code>)</td>
</tr>
</tbody>
</table>
<p>The <code>lme4</code> package extends the formula interface to specify random effects structures. Random effects are added to the formula by writing elements between parentheses <code>()</code>. Within these parentheses, you provide the specification of the random effects to be included on the left-hand side of a conditional sign <code>|</code>. On the right-hand side of the sign, you specify the grouping factor, or grouping factors, on which these random effects depend. The grouping factors <strong>need to be of class <code>factor</code></strong> (i.e., they can <strong>not</strong> be numeric variables). Here are some examples of such specifications (again mostly adapted from <span class="citation"><a href="#ref-Singmann2019-mixed" role="doc-biblioref">Singmann and Kellen</a> (<a href="#ref-Singmann2019-mixed" role="doc-biblioref">2019</a>)</span>):</p>
<table>
<colgroup>
<col width="12%" />
<col width="88%" />
</colgroup>
<thead>
<tr class="header">
<th>Formula</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>(1|s)</code></td>
<td>random intercepts for unique level of the factor <code>s</code></td>
</tr>
<tr class="even">
<td><code>(1|s) + (1|i)</code></td>
<td>random intercepts for each unique level of <code>s</code> and for each unique level of <code>i</code></td>
</tr>
<tr class="odd">
<td><code>(1|s/i)</code></td>
<td>random intercepts for factor <code>s</code> and <code>i</code>, where the random effects for <code>i</code> are <em>nested</em> in <code>s</code>. This expands to <code>(1|s) + (1|s:i)</code>, i.e. a random intercept for each level of <code>s</code>, and each unique combination of the levels of <code>s</code> and <code>i</code>. Nested random effects are used in so-called multilevel models. For example, <code>s</code> might refer to schools, and <code>i</code> to classrooms within those schools.</td>
</tr>
<tr class="even">
<td><code>(a|s)</code></td>
<td>random intercepts and random slopes for <code>a</code>, for each level of <code>s</code>. Correlations between the intercept and slope effects are also estimated. (identical to <code>(a*b|s)</code>)</td>
</tr>
<tr class="odd">
<td><code>(a*b|s)</code></td>
<td>random intercepts and slopes for <code>a</code>, <code>b</code>, and the <code>a:b</code> interaction, for each level of <code>s</code>. Correlations between all the random effects are estimated.</td>
</tr>
<tr class="even">
<td><code>(0+a|s)</code></td>
<td>random slopes for <code>a</code> for each level of <code>s</code>, but no random intercepts</td>
</tr>
<tr class="odd">
<td><code>(a||s)</code></td>
<td>random intercepts and random slopes for <code>a</code>, for each level of <code>s</code>, but no correlations between the random effects (i.e. they are set to 0). This expands to: <code>(0+a|s) + (1|s)</code>)</td>
</tr>
</tbody>
</table>
<div id="random-intercepts-model" class="section level3" number="9.1.1">
<h3><span class="header-section-number">9.1.1</span> Random intercepts model</h3>
<p>Now let’s try to define a relatively simple linear mixed-effects model for the <code>anchoring</code> data set in the <code>sdamr</code> package. We will use the data from all the <code>referrers</code> try a few variations to get acquainted with the <code>lmer()</code> function. First, let’s load the packages and the data:</p>
<div class="sourceCode" id="cb404"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb404-1"><a href="linear-mixed-effects-models.html#cb404-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sdamr)</span>
<span id="cb404-2"><a href="linear-mixed-effects-models.html#cb404-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lme4)</span></code></pre></div>
<pre><code>## Loading required package: Matrix</code></pre>
<div class="sourceCode" id="cb406"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb406-1"><a href="linear-mixed-effects-models.html#cb406-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">&quot;anchoring&quot;</span>)</span></code></pre></div>
<p>Now let’s estimate a first linear mixed-effects model, with a fixed effect for anchor, and random intercepts, using <code>everest_feet</code> as the dependent variable. We will first ensure that <code>anchor</code> is a factor and associate a sum-to-zero contrast to it. We will also make <code>referrer</code> a factor; the contrast for this shouldn’t really matter, so we’ll leave it as a dummy code. We then set up the model, using <code>(1|referrer)</code> to specify that random intercept-effects should be included for each level of the <code>referrer</code> factor. Finally, we use the <code>summary()</code> function on the estimated model to obtain the estimates of the parameters.</p>
<div class="sourceCode" id="cb407"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb407-1"><a href="linear-mixed-effects-models.html#cb407-1" aria-hidden="true" tabindex="-1"></a>anchoring<span class="sc">$</span>anchor <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(anchoring<span class="sc">$</span>anchor)</span>
<span id="cb407-2"><a href="linear-mixed-effects-models.html#cb407-2" aria-hidden="true" tabindex="-1"></a><span class="fu">contrasts</span>(anchoring<span class="sc">$</span>anchor) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span><span class="sc">/</span><span class="dv">2</span>, <span class="sc">-</span><span class="dv">1</span><span class="sc">/</span><span class="dv">2</span>) <span class="co"># alphabetical order, so high before low</span></span>
<span id="cb407-3"><a href="linear-mixed-effects-models.html#cb407-3" aria-hidden="true" tabindex="-1"></a><span class="co"># define a lmer</span></span>
<span id="cb407-4"><a href="linear-mixed-effects-models.html#cb407-4" aria-hidden="true" tabindex="-1"></a>mod <span class="ot">&lt;-</span> lme4<span class="sc">::</span><span class="fu">lmer</span>(everest_feet <span class="sc">~</span> anchor <span class="sc">+</span> (<span class="dv">1</span><span class="sc">|</span>referrer), <span class="at">data=</span>anchoring)</span>
<span id="cb407-5"><a href="linear-mixed-effects-models.html#cb407-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod)</span></code></pre></div>
<pre><code>## Linear mixed model fit by REML [&#39;lmerMod&#39;]
## Formula: everest_feet ~ anchor + (1 | referrer)
##    Data: anchoring
## 
## REML criterion at convergence: 98195.5
## 
## Scaled residuals: 
##     Min      1Q  Median      3Q     Max 
## -3.4433 -0.7178 -0.1361  0.7419  3.5546 
## 
## Random effects:
##  Groups   Name        Variance Std.Dev.
##  referrer (Intercept)  2717134 1648    
##  Residual             93929988 9692    
## Number of obs: 4632, groups:  referrer, 31
## 
## Fixed effects:
##             Estimate Std. Error t value
## (Intercept)  22788.3      346.8   65.70
## anchor1      23047.3      285.8   80.64
## 
## Correlation of Fixed Effects:
##         (Intr)
## anchor1 0.022</code></pre>
<p>The output first shows some information about the structure of the model, and the value of the optimized “-2 log REML” (the logarithm of the minus two restricted maximum likelihood). Then some summary statistics for the <em>standardized residuals</em> are shown (these are the “raw” residuals divided by the estimated standard deviation of the residuals).</p>
<p>Under the <code>Random effects:</code> header, you will find a table with estimates of the variance and standard deviation of the random effects terms for each grouping factor (just <code>referrer</code> in this case). So the estimated standard deviation of the random intercept: <span class="math inline">\(\hat{\sigma}_{\gamma_0} = 1648\)</span>. You will also find an estimate of the variance and standard deviation of the residuals in this table: <span class="math inline">\(\hat{\sigma}_\epsilon = 9692\)</span>}.</p>
<p>Under the <code>Fixed effects:</code> header, you will find a table with an estimate for each fixed effect, as well as the standard error of this estimate, and an associated <span class="math inline">\(t\)</span> statistic. This output is much like the output of calling the <code>summary()</code> function on a standard model estimated with the <code>lm</code> function. But you won’t find the <span class="math inline">\(p\)</span>-value for these estimates. This is because the author of the <code>lme4</code> package, perhaps rightly, finds none of the approximations to the error degrees of freedom good enough for general usage. Opinions on this will vary. It is agreed that the true Type 1 error rate when using one of the approximations will not be exactly equal to the <span class="math inline">\(\alpha\)</span> level. In some cases, the difference may be substantial, but often the approximation will be reasonable enough to be useful in practice. For further information on this, there is a section in a very useful <a href="https://bbolker.github.io/mixedmodels-misc/glmmFAQ.html#why-doesnt-lme4-display-denominator-degrees-of-freedomp-values-what-other-options-do-i-have">GLMM FAQ</a>. You can also see <code>?lme4::pvalues</code> for some information about various approaches to obtaining <span class="math inline">\(p\)</span>-values.</p>
<p>The final table, under the <code>Correlation of Fixed Effects</code>, shows the approximate correlation between the estimators of the fixed effects. You can think of it as the expected correlation between the estimates of the fixed effects over all different datasets that you might obtain (assuming that the predictors have the same values in each). It is not something you generally need to be concerned about.</p>
</div>
<div id="visually-assessing-model-assumptions" class="section level3" number="9.1.2">
<h3><span class="header-section-number">9.1.2</span> Visually assessing model assumptions</h3>
<p>You can use the <code>predict</code> and <code>residuals</code> function to obtain the predicted values and residuals for a linear mixed effects model. You can then plot these, using e.g. <code>ggplot2</code>, as follows:</p>
<div class="sourceCode" id="cb409"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb409-1"><a href="linear-mixed-effects-models.html#cb409-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb409-2"><a href="linear-mixed-effects-models.html#cb409-2" aria-hidden="true" tabindex="-1"></a>tdat <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">predicted=</span><span class="fu">predict</span>(mod), <span class="at">residual =</span> <span class="fu">residuals</span>(mod))</span>
<span id="cb409-3"><a href="linear-mixed-effects-models.html#cb409-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(tdat,<span class="fu">aes</span>(<span class="at">x=</span>predicted,<span class="at">y=</span>residual)) <span class="sc">+</span> <span class="fu">geom_point</span>() <span class="sc">+</span> <span class="fu">geom_hline</span>(<span class="at">yintercept=</span><span class="dv">0</span>, <span class="at">lty=</span><span class="dv">3</span>)</span></code></pre></div>
<p><img src="09-LMER_files/figure-html/unnamed-chunk-5-1.png" width="672" /></p>
<p>It might be cool to colour the residuals by referrer as follows:</p>
<div class="sourceCode" id="cb410"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb410-1"><a href="linear-mixed-effects-models.html#cb410-1" aria-hidden="true" tabindex="-1"></a>tdat <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">predicted=</span><span class="fu">predict</span>(mod), <span class="at">residual =</span> <span class="fu">residuals</span>(mod), <span class="at">referrer=</span>anchoring<span class="sc">$</span>referrer)</span>
<span id="cb410-2"><a href="linear-mixed-effects-models.html#cb410-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(tdat,<span class="fu">aes</span>(<span class="at">x=</span>predicted,<span class="at">y=</span>residual, <span class="at">colour=</span>referrer)) <span class="sc">+</span> <span class="fu">geom_point</span>() <span class="sc">+</span> <span class="fu">geom_hline</span>(<span class="at">yintercept=</span><span class="dv">0</span>, <span class="at">lty=</span><span class="dv">3</span>)</span></code></pre></div>
<p><img src="09-LMER_files/figure-html/unnamed-chunk-6-1.png" width="672" />
If the legend gets in the way, you can remove it as follows:</p>
<div class="sourceCode" id="cb411"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb411-1"><a href="linear-mixed-effects-models.html#cb411-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(tdat,<span class="fu">aes</span>(<span class="at">x=</span>predicted,<span class="at">y=</span>residual, <span class="at">colour=</span>referrer)) <span class="sc">+</span> <span class="fu">geom_point</span>() <span class="sc">+</span> <span class="fu">geom_hline</span>(<span class="at">yintercept=</span><span class="dv">0</span>, <span class="at">lty=</span><span class="dv">3</span>) <span class="sc">+</span> <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">&quot;none&quot;</span>)</span></code></pre></div>
<p><img src="09-LMER_files/figure-html/unnamed-chunk-7-1.png" width="672" />
The <code>theme</code> function allows for lots of functionality (check <code>?theme</code>). You can also get a quick predicted vs residual plot from base R by simply calling <code>plot(mod)</code>.</p>
<p>We can get a nice-looking histogram of the residuals, and a QQ plot, as follows:</p>
<div class="sourceCode" id="cb412"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb412-1"><a href="linear-mixed-effects-models.html#cb412-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(tdat,<span class="fu">aes</span>(<span class="at">x=</span>residual)) <span class="sc">+</span> <span class="fu">geom_histogram</span>(<span class="at">bins=</span><span class="dv">20</span>, <span class="at">color=</span><span class="st">&quot;black&quot;</span>)</span></code></pre></div>
<p><img src="09-LMER_files/figure-html/unnamed-chunk-8-1.png" width="672" /></p>
<div class="sourceCode" id="cb413"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb413-1"><a href="linear-mixed-effects-models.html#cb413-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(tdat,<span class="fu">aes</span>(<span class="at">sample=</span>residual)) <span class="sc">+</span> <span class="fu">stat_qq</span>() <span class="sc">+</span> <span class="fu">stat_qq_line</span>()</span></code></pre></div>
<p><img src="09-LMER_files/figure-html/unnamed-chunk-8-2.png" width="672" /></p>
</div>
<div id="random-intercepts-and-slopes" class="section level3" number="9.1.3">
<h3><span class="header-section-number">9.1.3</span> Random intercepts and slopes</h3>
<p>Now let’s estimate a model with random intercepts and random slopes for <code>anchor</code>. To do so, we can simply add <code>anchor</code> in the mixed effects structure specification, as follows:</p>
<div class="sourceCode" id="cb414"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb414-1"><a href="linear-mixed-effects-models.html#cb414-1" aria-hidden="true" tabindex="-1"></a>modg <span class="ot">&lt;-</span> lme4<span class="sc">::</span><span class="fu">lmer</span>(everest_feet <span class="sc">~</span> anchor <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">+</span> anchor<span class="sc">|</span>referrer), <span class="at">data=</span>anchoring)</span>
<span id="cb414-2"><a href="linear-mixed-effects-models.html#cb414-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modg)</span></code></pre></div>
<pre><code>## Linear mixed model fit by REML [&#39;lmerMod&#39;]
## Formula: everest_feet ~ anchor + (1 + anchor | referrer)
##    Data: anchoring
## 
## REML criterion at convergence: 97944.4
## 
## Scaled residuals: 
##     Min      1Q  Median      3Q     Max 
## -3.5558 -0.6374 -0.1029  0.6551  3.8431 
## 
## Random effects:
##  Groups   Name        Variance Std.Dev. Corr 
##  referrer (Intercept)  2470481 1572          
##           anchor1     36036021 6003     -0.80
##  Residual             87887265 9375          
## Number of obs: 4632, groups:  referrer, 31
## 
## Fixed effects:
##             Estimate Std. Error t value
## (Intercept)  22840.8      329.4   69.34
## anchor1      23578.8     1139.0   20.70
## 
## Correlation of Fixed Effects:
##         (Intr)
## anchor1 -0.658</code></pre>
<p>As you can see, the model now estimates a variance of the random slopes effects, as well as a correlation between the random intercept and slope effects. We could try to get a model without the correlations as follows:</p>
<div class="sourceCode" id="cb416"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb416-1"><a href="linear-mixed-effects-models.html#cb416-1" aria-hidden="true" tabindex="-1"></a>modr <span class="ot">&lt;-</span> lme4<span class="sc">::</span><span class="fu">lmer</span>(everest_feet <span class="sc">~</span> anchor <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">+</span> anchor<span class="sc">||</span>referrer), <span class="at">data=</span>anchoring)</span></code></pre></div>
<pre><code>## Warning in checkConv(attr(opt, &quot;derivs&quot;), opt$par, ctrl = control$checkConv, :
## unable to evaluate scaled gradient</code></pre>
<pre><code>## Warning in checkConv(attr(opt, &quot;derivs&quot;), opt$par, ctrl = control$checkConv, :
## Model failed to converge: degenerate Hessian with 1 negative eigenvalues</code></pre>
<p>As you can see in the warning messages, this leads to various estimation issues. Moreover, the correlation is actually still there!</p>
<div class="sourceCode" id="cb419"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb419-1"><a href="linear-mixed-effects-models.html#cb419-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modr)</span></code></pre></div>
<pre><code>## Linear mixed model fit by REML [&#39;lmerMod&#39;]
## Formula: everest_feet ~ anchor + ((1 | referrer) + (0 + anchor | referrer))
##    Data: anchoring
## 
## REML criterion at convergence: 97944.4
## 
## Scaled residuals: 
##     Min      1Q  Median      3Q     Max 
## -3.5558 -0.6374 -0.1029  0.6551  3.8431 
## 
## Random effects:
##  Groups     Name        Variance Std.Dev. Corr 
##  referrer   (Intercept)    72369  269          
##  referrer.1 anchorhigh   3835401 1958          
##             anchorlow   18979098 4357     -0.77
##  Residual               87887261 9375          
## Number of obs: 4632, groups:  referrer, 31
## 
## Fixed effects:
##             Estimate Std. Error t value
## (Intercept)  22840.8      329.4   69.34
## anchor1      23578.8     1139.0   20.70
## 
## Correlation of Fixed Effects:
##         (Intr)
## anchor1 -0.658
## optimizer (nloptwrap) convergence code: 0 (OK)
## unable to evaluate scaled gradient
## Model failed to converge: degenerate  Hessian with 1 negative eigenvalues</code></pre>
<p>As it turns out, the <code>||</code> notation <strong>does not work well for factors</strong>!. It only works as expected with metric predictors. We can get the desired model by defining a contrast-coded predictor for <code>anchor</code> explicitly, as follows:</p>
<div class="sourceCode" id="cb421"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb421-1"><a href="linear-mixed-effects-models.html#cb421-1" aria-hidden="true" tabindex="-1"></a>anchoring<span class="sc">$</span>anchor_contrast <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">/</span><span class="dv">2</span></span>
<span id="cb421-2"><a href="linear-mixed-effects-models.html#cb421-2" aria-hidden="true" tabindex="-1"></a>anchoring<span class="sc">$</span>anchor_contrast[anchoring<span class="sc">$</span>anchor <span class="sc">==</span> <span class="st">&quot;low&quot;</span>] <span class="ot">&lt;-</span> <span class="sc">-</span><span class="dv">1</span><span class="sc">/</span><span class="dv">2</span></span>
<span id="cb421-3"><a href="linear-mixed-effects-models.html#cb421-3" aria-hidden="true" tabindex="-1"></a>modr <span class="ot">&lt;-</span> lme4<span class="sc">::</span><span class="fu">lmer</span>(everest_feet <span class="sc">~</span> anchor_contrast <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">+</span> anchor_contrast<span class="sc">||</span>referrer), <span class="at">data=</span>anchoring)</span>
<span id="cb421-4"><a href="linear-mixed-effects-models.html#cb421-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modr)</span></code></pre></div>
<pre><code>## Linear mixed model fit by REML [&#39;lmerMod&#39;]
## Formula: 
## everest_feet ~ anchor_contrast + ((1 | referrer) + (0 + anchor_contrast |  
##     referrer))
##    Data: anchoring
## 
## REML criterion at convergence: 97960.2
## 
## Scaled residuals: 
##     Min      1Q  Median      3Q     Max 
## -3.6330 -0.6464 -0.1011  0.6732  3.8333 
## 
## Random effects:
##  Groups     Name            Variance Std.Dev.
##  referrer   (Intercept)      2350312 1533    
##  referrer.1 anchor_contrast 36126381 6011    
##  Residual                   87899463 9375    
## Number of obs: 4632, groups:  referrer, 31
## 
## Fixed effects:
##                 Estimate Std. Error t value
## (Intercept)      22773.6      326.7   69.71
## anchor_contrast  23526.1     1141.8   20.60
## 
## Correlation of Fixed Effects:
##             (Intr)
## anchr_cntrs 0.011</code></pre>
<p>That is a little cumbersome, especially if you have a factor with lots of levels, in which case you would have to specify many contrast-coded predictors. The <code>lmer_alt()</code> function in the <code>afex</code> package will automatically generate the contrast-coded predictors needed, which will be convenient. You can try this by running:</p>
<div class="sourceCode" id="cb423"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb423-1"><a href="linear-mixed-effects-models.html#cb423-1" aria-hidden="true" tabindex="-1"></a>modr <span class="ot">&lt;-</span> afex<span class="sc">::</span><span class="fu">lmer_alt</span>(everest_feet <span class="sc">~</span> anchor <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">+</span> anchor<span class="sc">||</span>referrer), <span class="at">set_data_arg =</span> <span class="cn">TRUE</span>, <span class="at">data=</span>anchoring)</span>
<span id="cb423-2"><a href="linear-mixed-effects-models.html#cb423-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modr)</span></code></pre></div>
<pre><code>## Linear mixed model fit by REML. t-tests use Satterthwaite&#39;s method [
## lmerModLmerTest]
## Formula: everest_feet ~ anchor + (1 + re1.anchor1 || referrer)
##    Data: anchoring
## 
## REML criterion at convergence: 97960.2
## 
## Scaled residuals: 
##     Min      1Q  Median      3Q     Max 
## -3.6330 -0.6464 -0.1011  0.6732  3.8333 
## 
## Random effects:
##  Groups     Name        Variance Std.Dev.
##  referrer   (Intercept)  2350312 1533    
##  referrer.1 re1.anchor1 36126381 6011    
##  Residual               87899463 9375    
## Number of obs: 4632, groups:  referrer, 31
## 
## Fixed effects:
##             Estimate Std. Error       df t value Pr(&gt;|t|)    
## (Intercept) 22773.65     326.69    29.08   69.71   &lt;2e-16 ***
## anchor1     23526.08    1141.84    28.22   20.60   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Correlation of Fixed Effects:
##         (Intr)
## anchor1 0.011</code></pre>
<p>Note the use of the additional <code>set_data_arg = TRUE</code> argument, which is necessary to later use the object for model comparisons with the likelihood ratio test in the next section. Also note that the parameters now do come with <span class="math inline">\(p\)</span>-values (using the Satterthwaite approximation).</p>
</div>
<div id="likelihood-ratio-test-with-the-anova-function" class="section level3" number="9.1.4">
<h3><span class="header-section-number">9.1.4</span> Likelihood ratio test with the <code>anova</code> function</h3>
<p>We now have two versions of our random intercepts + slopes model, one which estimates the correlation between the random intercept and slope, and one which sets this to 0. A likelihood-ratio test comparing these two models is easily obtained as:</p>
<div class="sourceCode" id="cb425"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb425-1"><a href="linear-mixed-effects-models.html#cb425-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(modr,modg)</span></code></pre></div>
<pre><code>## refitting model(s) with ML (instead of REML)</code></pre>
<pre><code>## Data: anchoring
## Models:
## modr: everest_feet ~ anchor + (1 + re1.anchor1 || referrer)
## modg: everest_feet ~ anchor + (1 + anchor | referrer)
##      npar   AIC   BIC logLik deviance  Chisq Df Pr(&gt;Chisq)    
## modr    5 98000 98032 -48995    97990                         
## modg    6 97985 98024 -48987    97973 16.339  1  5.296e-05 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Note the message <code>refitting model(s) with ML (instead of REML)</code>. The likelihood-ratio test requires that the models are estimated by maximum likelihood, rather than restricted maximum likelihood (REML). The <code>lme4</code> package is clever enough to realize this, and first re-estimates the model before computing the likelihood ratio test. Also note that the test statistic is now called “Chisq,” for Chi-squared. This is the one we want. The test result is significant, and hence we can reject the null hypothesis that the correlation between the random intercept and slope is <span class="math inline">\(\rho_{\gamma_0,\gamma_1} = 0\)</span>.</p>
</div>
<div id="confidence-intervals" class="section level3" number="9.1.5">
<h3><span class="header-section-number">9.1.5</span> Confidence intervals</h3>
<p>While the <code>lme4</code> package does not provide <span class="math inline">\(p\)</span>-values, it does have functionality to compute confidence intervals via the <code>confint()</code> function. The default option is to compute so-called profile likelihood confidence intervals for all (fixed and random) parameters:</p>
<div class="sourceCode" id="cb428"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb428-1"><a href="linear-mixed-effects-models.html#cb428-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(modg)</span></code></pre></div>
<pre><code>## Computing profile confidence intervals ...</code></pre>
<pre><code>##                    2.5 %        97.5 %
## .sig01       1083.558297  2187.2825617
## .sig02         -0.956541    -0.5042915
## .sig03       4471.113419  7999.4737204
## .sigma       9185.991570  9570.4663804
## (Intercept) 22184.246089 23499.3202067
## anchor1     21298.714977 25838.8350190</code></pre>
<p>Note that <code>.sig01</code> refers to the standard deviation of the random intercept (i.e. <span class="math inline">\(\sigma{\gamma_0}\)</span>), <code>.sig02</code> refers to the correlation between the random intercept and random slope (i.e. <span class="math inline">\(\rho_{\gamma_0,\gamma_1}\)</span>), and <code>.sig03</code> to the standard deviation of the random slope (i.e. <span class="math inline">\(\sigma_{\gamma_1}\)</span>). The value of <code>.sig</code> refers to the standard deviation of the error term (i.e. <span class="math inline">\(\sigma_\epsilon\)</span>). Unfortunately, these are not the most informative labels, so it pays to check the values reported in <code>summary(modg)</code> to match them to the output here.</p>
<p>Parametric bootstrap confidence (via simulation) can be obtained by setting the argument <code>method = "boot"</code>. This is a very computationally intensive procedure, so you will have to wait some time for the results! Moreover, due to the random simulation involved, the results will vary (hopefully a little) every time you run the procedure:</p>
<div class="sourceCode" id="cb431"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb431-1"><a href="linear-mixed-effects-models.html#cb431-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">20201201</span>)</span>
<span id="cb431-2"><a href="linear-mixed-effects-models.html#cb431-2" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(modg, <span class="at">method=</span><span class="st">&quot;boot&quot;</span>)</span></code></pre></div>
<pre><code>## Computing bootstrap confidence intervals ...</code></pre>
<pre><code>## 
## 14 message(s): boundary (singular) fit: see ?isSingular</code></pre>
<pre><code>##                 2.5 %        97.5 %
## .sig01       1041.469  2111.5327662
## .sig02         -1.000    -0.5192476
## .sig03       4369.214  7716.5436429
## .sigma       9171.071  9573.5222532
## (Intercept) 22138.746 23535.5279557
## anchor1     21366.564 26111.6466861</code></pre>
<div class="sourceCode" id="cb435"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb435-1"><a href="linear-mixed-effects-models.html#cb435-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(modg, <span class="at">method=</span><span class="st">&quot;boot&quot;</span>)</span></code></pre></div>
<pre><code>## Computing bootstrap confidence intervals ...</code></pre>
<pre><code>## 
## 12 message(s): boundary (singular) fit: see ?isSingular
## 1 warning(s): Model failed to converge with max|grad| = 0.00760288 (tol = 0.002, component 1)</code></pre>
<pre><code>##                     2.5 %        97.5 %
## .sig01       1045.6131551  2151.4335327
## .sig02         -0.9976517    -0.5486075
## .sig03       4296.8794715  7695.7776431
## .sigma       9164.6786544  9584.8451898
## (Intercept) 22141.6525509 23504.3587997
## anchor1     21047.7038556 25819.4349753</code></pre>
<p>Note the warning messages. By default, the bootstrap simulates <code>nsim=500</code> datasets and re-estimates the model for each. In some of the simulated datasets, the estimation may fail, which provides the resulting warning messages. While confidence intervals and hypothesis tests, in the case of “standard” linear models give the same results, this is not necessarily the case for mixed models, as the <span class="math inline">\(F\)</span> tests for the fixed effects involve approximation of the error degrees of freedom (<span class="math inline">\(\text{df}_2\)</span>), whilst the computation of the confidence intervals rely on other forms of approximation (e.g. simulation for the parametric bootstrap). As confidence intervals are included by default in <code>lme4</code>, it seems like the author of the package believes these are perhaps more principled than the <span class="math inline">\(F\)</span> tests for the fixed effects.</p>
</div>
<div id="plotting-model-predictions" class="section level3" number="9.1.6">
<h3><span class="header-section-number">9.1.6</span> Plotting model predictions</h3>
<p>It can be useful to plot the model predictions for each level of the random grouping factor. We can obtain such a plot by storing the model predictions with the data. By adding the <code>group =</code> and <code>colour =</code> arguments in the <code>aes()</code> function, you can then get separate results for all levels of the random effect factor (<code>referrer</code> here). For instance, we can plot the predictions for the different levels of the <code>anchor</code> factor with connecting lines as follows:</p>
<div class="sourceCode" id="cb439"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb439-1"><a href="linear-mixed-effects-models.html#cb439-1" aria-hidden="true" tabindex="-1"></a>anchoring<span class="sc">$</span>pred <span class="ot">&lt;-</span> <span class="fu">predict</span>(modg)</span>
<span id="cb439-2"><a href="linear-mixed-effects-models.html#cb439-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(anchoring,<span class="fu">aes</span>(<span class="at">x=</span>anchor,<span class="at">y=</span>pred,<span class="at">colour=</span>referrer, <span class="at">group=</span>referrer)) <span class="sc">+</span> <span class="fu">geom_point</span>() <span class="sc">+</span> <span class="fu">geom_line</span>() <span class="sc">+</span> <span class="fu">theme</span>(<span class="at">legend.position=</span><span class="st">&quot;bottom&quot;</span>, <span class="at">legend.direction =</span> <span class="st">&quot;horizontal&quot;</span>)</span></code></pre></div>
<p><img src="09-LMER_files/figure-html/unnamed-chunk-16-1.png" width="576" /></p>
<p>This would also work if the variable of the x-axis is continuous, rather than categorical.</p>
</div>
</div>
<div id="obtaining-p-values-with-afexmixed" class="section level2" number="9.2">
<h2><span class="header-section-number">9.2</span> Obtaining p-values with <code>afex::mixed</code></h2>
<p>Despite some of the concerns about the validity of the <span class="math inline">\(p\)</span>-values for <span class="math inline">\(F\)</span>-tests of the fixed effects, they are often useful (if only to satisfy reviewers of your paper). Packages such as <code>pbkrtest</code> <span class="citation">(<a href="#ref-R-pbkrtest" role="doc-biblioref">Højsgaard 2020</a>)</span> and <code>lmerTest</code> <span class="citation">(<a href="#ref-R-lmerTest" role="doc-biblioref">Kuznetsova, Bruun Brockhoff, and Haubo Bojesen Christensen 2020</a>)</span> have been developed to provide these for mixed-effects models estimated with the <code>lmer()</code> function, using the Kenward-Roger or parametric bootstrap, and Satterthwaite approximations, respectively. The <code>afex</code> package <span class="citation">(<a href="#ref-R-afex" role="doc-biblioref">Singmann et al. 2021</a>)</span> provides a common interface to the functionality of these packages, via its <code>mixed</code> function. The <code>mixed</code> function offers some other convenient features, such as automatically using sum-to-zero contrasts (via <code>contr.sum()</code>), although I prefer setting my own contrasts and turn this off.</p>
<p>Some of the main arguments to the <code>mixed</code> function (see <code>?mixed</code> for the full overview) are:</p>
<ul>
<li><code>formula</code>: a two-sided linear formula describing both the fixed-effects and random-effects part of the model, with the response on the left of the <code>~</code> operator and predictors and random effects on the right-hand side of the <code>~</code> operator.</li>
<li><code>data</code>: A <code>data.frame</code>, which needs to be in the so-called “long” format, with a single row per observation. This may be different from what you might be used to when dealing with repeated-measures. A repeated-measures ANOVA in SPSS requires data in the “wide” format, where you use columns for the different repeated measures. Data in the “wide” format has a single row for each participants. In the “long” format, you will have multiple rows for the data from a single grouping level (e.g., participant, lab, etc.).<br />
</li>
<li><code>type</code>: Sums of Squares type to use (1, 2, or 3). Default is 3.</li>
<li><code>method</code>: Character vector indicating which approximation method to use for obtaining the p-values. <code>"KR"</code> for the Kenward-Roger approximation, <code>"S"</code> for the Satterthwaite approximation (the default), <code>"PB"</code> for a parametric bootstrap, and <code>"LRT"</code> for the likelihood ratio test.</li>
<li><code>test_intercept</code>: Logical variable indicating whether to obtain a test of the fixed intercept (only for Type 3 SS). Default is <code>FALSE</code></li>
<li><code>check_contrasts</code>: Logical variable indicating whether contrasts for factors should be checked and changed to <code>contr.sum</code> if they are not identical to <code>contr.sum</code>. Default is <code>TRUE</code>. You should set this to <code>FALSE</code> if you supply your own orthogonal contrasts.</li>
<li><code>expand_re</code>: Logical variable indicating whether random effect terms should be expanded (i.e. factors transformed into contrast-coded numerical predictors) before fitting with lmer. This allows proper use of the <code>||</code> notation with factors.</li>
</ul>
<p>Let’s try it out! First, let’s load the package:</p>
<div class="sourceCode" id="cb440"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb440-1"><a href="linear-mixed-effects-models.html#cb440-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(afex)</span></code></pre></div>
<pre><code>## ************
## Welcome to afex. For support visit: http://afex.singmann.science/</code></pre>
<pre><code>## - Functions for ANOVAs: aov_car(), aov_ez(), and aov_4()
## - Methods for calculating p-values with mixed(): &#39;S&#39;, &#39;KR&#39;, &#39;LRT&#39;, and &#39;PB&#39;
## - &#39;afex_aov&#39; and &#39;mixed&#39; objects can be passed to emmeans() for follow-up tests
## - NEWS: emmeans() for ANOVA models now uses model = &#39;multivariate&#39; as default.
## - Get and set global package options with: afex_options()
## - Set orthogonal sum-to-zero contrasts globally: set_sum_contrasts()
## - For example analyses see: browseVignettes(&quot;afex&quot;)
## ************</code></pre>
<pre><code>## 
## Attaching package: &#39;afex&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:lme4&#39;:
## 
##     lmer</code></pre>
<p>Note that after loading the <code>afex</code> package, the <code>lmer</code> function from <code>lme4</code> will be “masked” and the corresponding function from the <code>afex</code> namespace will be used (it is actually the same as the one from the <code>lmerTest</code> namespace), which is mostly the same, but expands the class of the returned object somewhat. Afterwards, you either have to use <code>lme4::lmer</code> whenever you explicitly want the function from the <code>lme4</code> package, or avoid loading the <code>afex</code> package, and always type e.g. <code>afex::mixed</code>. Either is fine, and mostly you wouldn’t need to worry, but sometimes the overriding of function names in the global workspace can give confusion and unexpected results, so it is good to be aware if this behaviour.</p>
<p>In the code below, I use the <code>mixed</code> function to estimate the model and compute <span class="math inline">\(p\)</span>-values for the fixed effect of <code>anchor</code> and the intercept with the <code>"KR"</code> option (note that this takes some time!):</p>
<div class="sourceCode" id="cb445"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb445-1"><a href="linear-mixed-effects-models.html#cb445-1" aria-hidden="true" tabindex="-1"></a>afmodg <span class="ot">&lt;-</span> <span class="fu">mixed</span>(everest_feet <span class="sc">~</span> anchor <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">+</span> anchor<span class="sc">|</span>referrer), <span class="at">data=</span>anchoring, <span class="at">check_contrasts =</span> <span class="cn">FALSE</span>, <span class="at">test_intercept =</span> <span class="cn">TRUE</span>, <span class="at">method=</span><span class="st">&quot;KR&quot;</span>)</span></code></pre></div>
<pre><code>## Fitting one lmer() model. [DONE]
## Calculating p-values. [DONE]</code></pre>
<p>The class of the returned object saved as <code>afmodg</code> is different from the usual one returned by the <code>lmer</code> function. To get the <span class="math inline">\(F\)</span> tests, you can just type in the name of the object:</p>
<div class="sourceCode" id="cb447"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb447-1"><a href="linear-mixed-effects-models.html#cb447-1" aria-hidden="true" tabindex="-1"></a>afmodg</span></code></pre></div>
<pre><code>## Mixed Model Anova Table (Type 3 tests, KR-method)
## 
## Model: everest_feet ~ anchor + (1 + anchor | referrer)
## Data: anchoring
##        Effect       df           F p.value
## 1 (Intercept) 1, 28.88 4759.47 ***   &lt;.001
## 2      anchor 1, 29.66  427.80 ***   &lt;.001
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;+&#39; 0.1 &#39; &#39; 1</code></pre>
<p>You can also use the <code>summary()</code> function to obtain the parameter estimates:</p>
<div class="sourceCode" id="cb449"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb449-1"><a href="linear-mixed-effects-models.html#cb449-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(afmodg)</span></code></pre></div>
<pre><code>## Linear mixed model fit by REML. t-tests use Satterthwaite&#39;s method [
## lmerModLmerTest]
## Formula: everest_feet ~ anchor + (1 + anchor | referrer)
##    Data: data
## 
## REML criterion at convergence: 97944.4
## 
## Scaled residuals: 
##     Min      1Q  Median      3Q     Max 
## -3.5558 -0.6374 -0.1029  0.6551  3.8431 
## 
## Random effects:
##  Groups   Name        Variance Std.Dev. Corr 
##  referrer (Intercept)  2470481 1572          
##           anchor1     36036021 6003     -0.80
##  Residual             87887265 9375          
## Number of obs: 4632, groups:  referrer, 31
## 
## Fixed effects:
##             Estimate Std. Error       df t value Pr(&gt;|t|)    
## (Intercept) 22840.77     329.42    27.49   69.34   &lt;2e-16 ***
## anchor1     23578.76    1138.95    27.32   20.70   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Correlation of Fixed Effects:
##         (Intr)
## anchor1 -0.658</code></pre>
<p>Note that we now also get <span class="math inline">\(p\)</span>-values for the effects (which are here derived from the Satterthwaite approximation to the degrees of freedom). That is, as mentioned before, because by loading the <code>afex</code> package, the <code>lme4::lmer()</code> function is masked and replaced by the <code>lmerTest::lmer()</code> function. This function uses the <code>lme4::lmer()</code> function to estimate the model, but then adds further results to compute the Satterthwaite degrees of freedom. If you like, you could force the use of the <code>lme4::lmer()</code> function, by specifying the appropriate namespace, as in e.g.</p>
<div class="sourceCode" id="cb451"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb451-1"><a href="linear-mixed-effects-models.html#cb451-1" aria-hidden="true" tabindex="-1"></a>lmermodg <span class="ot">&lt;-</span> lme4<span class="sc">::</span><span class="fu">lmer</span>(everest_feet <span class="sc">~</span> anchor <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">+</span> anchor<span class="sc">|</span>referrer), <span class="at">data=</span>anchoring)</span></code></pre></div>
<p>Continuing our example, we can also estimate the model without correlation between the random effects as follows:</p>
<div class="sourceCode" id="cb452"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb452-1"><a href="linear-mixed-effects-models.html#cb452-1" aria-hidden="true" tabindex="-1"></a>afmodr <span class="ot">&lt;-</span> <span class="fu">mixed</span>(everest_feet <span class="sc">~</span> anchor <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">+</span> anchor<span class="sc">||</span>referrer), <span class="at">data=</span>anchoring, <span class="at">check_contrasts =</span> <span class="cn">FALSE</span>, <span class="at">test_intercept =</span> <span class="cn">TRUE</span>, <span class="at">expand_re =</span> <span class="cn">TRUE</span>, <span class="at">method=</span><span class="st">&quot;KR&quot;</span>)</span></code></pre></div>
<pre><code>## Fitting one lmer() model. [DONE]
## Calculating p-values. [DONE]</code></pre>
<p>and get the <span class="math inline">\(F\)</span> tests for this model:</p>
<div class="sourceCode" id="cb454"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb454-1"><a href="linear-mixed-effects-models.html#cb454-1" aria-hidden="true" tabindex="-1"></a>afmodr</span></code></pre></div>
<pre><code>## Mixed Model Anova Table (Type 3 tests, KR-method)
## 
## Model: everest_feet ~ anchor + (1 + anchor || referrer)
## Data: anchoring
##        Effect       df           F p.value
## 1 (Intercept) 1, 28.86 4843.68 ***   &lt;.001
## 2      anchor 1, 29.69  424.13 ***   &lt;.001
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;+&#39; 0.1 &#39; &#39; 1</code></pre>
<p>and parameter estimates</p>
<div class="sourceCode" id="cb456"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb456-1"><a href="linear-mixed-effects-models.html#cb456-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(afmodr)</span></code></pre></div>
<pre><code>## Linear mixed model fit by REML. t-tests use Satterthwaite&#39;s method [
## lmerModLmerTest]
## Formula: everest_feet ~ anchor + (1 + re1.anchor1 || referrer)
##    Data: data
## 
## REML criterion at convergence: 97960.2
## 
## Scaled residuals: 
##     Min      1Q  Median      3Q     Max 
## -3.6330 -0.6464 -0.1011  0.6732  3.8333 
## 
## Random effects:
##  Groups     Name        Variance Std.Dev.
##  referrer   (Intercept)  2350312 1533    
##  referrer.1 re1.anchor1 36126381 6011    
##  Residual               87899463 9375    
## Number of obs: 4632, groups:  referrer, 31
## 
## Fixed effects:
##             Estimate Std. Error       df t value Pr(&gt;|t|)    
## (Intercept) 22773.65     326.69    29.08   69.71   &lt;2e-16 ***
## anchor1     23526.08    1141.84    28.22   20.60   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Correlation of Fixed Effects:
##         (Intr)
## anchor1 0.011</code></pre>
<p>Note that entering these two <code>mixed</code> models as is into the <code>anova</code> function <strong>will not</strong> provide the desired re-estimation of the models by maximum likelihood:</p>
<div class="sourceCode" id="cb458"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb458-1"><a href="linear-mixed-effects-models.html#cb458-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(afmodr,afmodg)</span></code></pre></div>
<pre><code>## Data: data
## Models:
## afmodr: everest_feet ~ anchor + (1 + re1.anchor1 || referrer)
## afmodg: everest_feet ~ anchor + (1 + anchor | referrer)
##        npar   AIC   BIC logLik deviance  Chisq Df Pr(&gt;Chisq)    
## afmodr    5 97970 98002 -48980    97960                         
## afmodg    6 97956 97995 -48972    97944 15.781  1  7.111e-05 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>This is not clear from the output (apart from the missing <code>refitting model(s) with ML (instead of REML)</code> message). For the correct results, you will need to provide the <code>lmer</code> model, stored in the <code>afmodr</code> and <code>afmodg</code> objects under <code>$full_model</code>:</p>
<div class="sourceCode" id="cb460"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb460-1"><a href="linear-mixed-effects-models.html#cb460-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(afmodr<span class="sc">$</span>full_model, afmodg<span class="sc">$</span>full_model)</span></code></pre></div>
<pre><code>## refitting model(s) with ML (instead of REML)</code></pre>
<pre><code>## Data: data
## Models:
## afmodr$full_model: everest_feet ~ anchor + (1 + re1.anchor1 || referrer)
## afmodg$full_model: everest_feet ~ anchor + (1 + anchor | referrer)
##                   npar   AIC   BIC logLik deviance  Chisq Df Pr(&gt;Chisq)    
## afmodr$full_model    5 98000 98032 -48995    97990                         
## afmodg$full_model    6 97985 98024 -48987    97973 16.339  1  5.296e-05 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Although the differences are small, the first test compares the “-2 log REML,” instead of the desired “-2 log ML” values. The assumptions underlying the likelihood-ratio test require the latter.</p>
</div>
<div id="crossed-random-effects" class="section level2" number="9.3">
<h2><span class="header-section-number">9.3</span> Crossed random effects</h2>
<p>The <code>lme4::lmer()</code> function (and the <code>afex::mixed()</code> function which that is built on top of that function) allows you to specify multiple sources for random effects. In the book, we discussed an example with crossed random effects, using the <code>speeddate</code> data. In this data, participants (identified by the <code>iid</code> variable) provide ratings of various attributes of different dating partners (identified by the <code>pid</code> variable). Here, <code>iid</code> refers to the Person factor, and <code>pid</code> to the Item factor.</p>
<p>To estimate a model with crossed random effects, you simply include two separate statements for the random effects in the model formula, one for the effects depending on <code>iid</code>, and one for the random effects depending on <code>pid</code>:</p>
<div class="sourceCode" id="cb463"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb463-1"><a href="linear-mixed-effects-models.html#cb463-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">&quot;speeddate&quot;</span>)</span>
<span id="cb463-2"><a href="linear-mixed-effects-models.html#cb463-2" aria-hidden="true" tabindex="-1"></a>dat <span class="ot">&lt;-</span> speeddate</span>
<span id="cb463-3"><a href="linear-mixed-effects-models.html#cb463-3" aria-hidden="true" tabindex="-1"></a><span class="co"># center the predictors</span></span>
<span id="cb463-4"><a href="linear-mixed-effects-models.html#cb463-4" aria-hidden="true" tabindex="-1"></a>dat<span class="sc">$</span>other_attr_c <span class="ot">&lt;-</span> <span class="fu">center</span>(dat<span class="sc">$</span>other_attr)</span>
<span id="cb463-5"><a href="linear-mixed-effects-models.html#cb463-5" aria-hidden="true" tabindex="-1"></a>dat<span class="sc">$</span>other_intel_c <span class="ot">&lt;-</span> <span class="fu">center</span>(dat<span class="sc">$</span>other_intel)</span>
<span id="cb463-6"><a href="linear-mixed-effects-models.html#cb463-6" aria-hidden="true" tabindex="-1"></a><span class="do">## estimate the model</span></span>
<span id="cb463-7"><a href="linear-mixed-effects-models.html#cb463-7" aria-hidden="true" tabindex="-1"></a>crmod <span class="ot">&lt;-</span> <span class="fu">mixed</span>(other_like <span class="sc">~</span> other_attr_c<span class="sc">*</span>other_intel_c <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">+</span> other_attr_c<span class="sc">*</span>other_intel_c<span class="sc">|</span>iid) <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">+</span> other_attr_c<span class="sc">*</span>other_intel_c<span class="sc">|</span>pid), <span class="at">data=</span>dat, <span class="at">test_intercept =</span> <span class="cn">TRUE</span>, <span class="at">method=</span><span class="st">&quot;KR&quot;</span>)</span></code></pre></div>
<pre><code>## Warning: Due to missing values, reduced number of observations to 1509</code></pre>
<pre><code>## Numerical variables NOT centered on 0: other_attr_c, other_intel_c
## If in interactions, interpretation of lower order (e.g., main) effects difficult.</code></pre>
<pre><code>## Fitting one lmer() model.</code></pre>
<pre><code>## boundary (singular) fit: see ?isSingular</code></pre>
<pre><code>## [DONE]
## Calculating p-values. [DONE]</code></pre>
<p>Note there are some warnings. The first states that, due to missing values, the number of observations is reduced. If a row in the dataset has a missing value on either the dependent variable to one of the predictors, it is not possible to compute an error or model prediction. Hence, such rows are removed from the dataset before fitting the model. The second warning, starting with <code>Numerical variables NOT centered on 0</code> we can ignore, as it is erroneous (we have centered the numeric predictors). The checks performed by <code>afex::mixed()</code> sometimes miss the mark. The third warning regarding boundary singular fit (<code>boundary (singular) fit: see ?isSingular</code>), is something that will require attention. It signals that the model may be too complex to estimate properly. Such issues often (but not always!) show in estimated variances of random effects of 0 (i.e., no variance) or correlations between random effects of 1 or -1. Before doing anything else, we should therefore inspect the random-effects estimates. We can view these estimates (as well as those of the fixed effects) as usual with the <code>summary()</code> function:</p>
<div class="sourceCode" id="cb469"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb469-1"><a href="linear-mixed-effects-models.html#cb469-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(crmod)</span></code></pre></div>
<pre><code>## Linear mixed model fit by REML. t-tests use Satterthwaite&#39;s method [
## lmerModLmerTest]
## Formula: other_like ~ other_attr_c * other_intel_c + (1 + other_attr_c *  
##     other_intel_c | iid) + (1 + other_attr_c * other_intel_c |      pid)
##    Data: data
## 
## REML criterion at convergence: 4673.3
## 
## Scaled residuals: 
##     Min      1Q  Median      3Q     Max 
## -4.6285 -0.5182  0.0161  0.5374  4.0147 
## 
## Random effects:
##  Groups   Name                       Variance  Std.Dev. Corr             
##  iid      (Intercept)                0.0787745 0.28067                   
##           other_attr_c               0.0234085 0.15300  -0.54            
##           other_intel_c              0.0230445 0.15180   0.50 -0.89      
##           other_attr_c:other_intel_c 0.0008858 0.02976  -0.43 -0.27  0.54
##  pid      (Intercept)                0.2848115 0.53368                   
##           other_attr_c               0.0423056 0.20568  -0.47            
##           other_intel_c              0.0489423 0.22123   0.11 -0.63      
##           other_attr_c:other_intel_c 0.0019882 0.04459  -0.36  0.27 -0.16
##  Residual                            0.9630700 0.98136                   
## Number of obs: 1509, groups:  iid, 102; pid, 102
## 
## Fixed effects:
##                              Estimate Std. Error         df t value Pr(&gt;|t|)
## (Intercept)                  6.224027   0.069972 112.566265  88.950  &lt; 2e-16
## other_attr_c                 0.555403   0.033642 119.387075  16.509  &lt; 2e-16
## other_intel_c                0.374503   0.039240  89.115616   9.544 2.78e-15
## other_attr_c:other_intel_c  -0.009401   0.013144  43.430420  -0.715    0.478
##                               
## (Intercept)                ***
## other_attr_c               ***
## other_intel_c              ***
## other_attr_c:other_intel_c    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Correlation of Fixed Effects:
##             (Intr) othr_t_ othr_n_
## other_ttr_c -0.365                
## other_ntl_c  0.118 -0.557         
## othr_tt_:__ -0.261  0.011   0.079 
## optimizer (nloptwrap) convergence code: 0 (OK)
## boundary (singular) fit: see ?isSingular</code></pre>
<p>In this case, none of the variances are estimated as 0, and none of the correlations are estimated as 1 or -1. But the estimated variances of the random <code>other_attr_c:other_intel_c</code> interactions are quite low, and close to 0. As such, it might make sense to remove these effects.</p>
<div class="sourceCode" id="cb471"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb471-1"><a href="linear-mixed-effects-models.html#cb471-1" aria-hidden="true" tabindex="-1"></a>crmod2 <span class="ot">&lt;-</span> <span class="fu">mixed</span>(other_like <span class="sc">~</span> other_attr_c<span class="sc">*</span>other_intel_c <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">+</span> other_attr_c <span class="sc">+</span> other_intel_c<span class="sc">|</span>iid) <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">+</span> other_attr_c <span class="sc">+</span> other_intel_c<span class="sc">|</span>pid), <span class="at">data=</span>dat, <span class="at">test_intercept =</span> <span class="cn">TRUE</span>, <span class="at">method=</span><span class="st">&quot;KR&quot;</span>)</span></code></pre></div>
<pre><code>## Warning: Due to missing values, reduced number of observations to 1509</code></pre>
<pre><code>## Numerical variables NOT centered on 0: other_attr_c, other_intel_c
## If in interactions, interpretation of lower order (e.g., main) effects difficult.</code></pre>
<pre><code>## Fitting one lmer() model.</code></pre>
<pre><code>## boundary (singular) fit: see ?isSingular</code></pre>
<pre><code>## Warning: Model failed to converge with 1 negative eigenvalue: -2.2e+03</code></pre>
<pre><code>## [DONE]
## Calculating p-values. [DONE]</code></pre>
<p>This does not resolve the issue, as we still get the <code>boundary (singular) fit</code> warning. Moreover, we now get another warning: <code>Model failed to converge with 1 negative eigenvalue</code>. Checking the parameter estimates:</p>
<div class="sourceCode" id="cb478"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb478-1"><a href="linear-mixed-effects-models.html#cb478-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(crmod2)</span></code></pre></div>
<pre><code>## Linear mixed model fit by REML. t-tests use Satterthwaite&#39;s method [
## lmerModLmerTest]
## Formula: other_like ~ other_attr_c * other_intel_c + (1 + other_attr_c +  
##     other_intel_c | iid) + (1 + other_attr_c + other_intel_c |      pid)
##    Data: data
## 
## REML criterion at convergence: 4717
## 
## Scaled residuals: 
##     Min      1Q  Median      3Q     Max 
## -4.4392 -0.5571  0.0336  0.5380  3.9036 
## 
## Random effects:
##  Groups   Name          Variance Std.Dev. Corr       
##  iid      (Intercept)   0.06644  0.2578              
##           other_attr_c  0.02636  0.1624   -0.60      
##           other_intel_c 0.02023  0.1422    0.75 -0.98
##  pid      (Intercept)   0.30244  0.5499              
##           other_attr_c  0.01746  0.1321   -1.00      
##           other_intel_c 0.03484  0.1867    0.28 -0.28
##  Residual               1.05820  1.0287              
## Number of obs: 1509, groups:  iid, 102; pid, 102
## 
## Fixed effects:
##                             Estimate Std. Error        df t value Pr(&gt;|t|)    
## (Intercept)                  6.20784    0.07028 117.29792  88.331   &lt;2e-16 ***
## other_attr_c                 0.53693    0.02948 118.54368  18.211   &lt;2e-16 ***
## other_intel_c                0.37939    0.03634  92.46214  10.441   &lt;2e-16 ***
## other_attr_c:other_intel_c  -0.01269    0.01056 136.72908  -1.202    0.231    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Correlation of Fixed Effects:
##             (Intr) othr_t_ othr_n_
## other_ttr_c -0.530                
## other_ntl_c  0.217 -0.467         
## othr_tt_:__ -0.132 -0.022   0.058 
## optimizer (nloptwrap) convergence code: 0 (OK)
## boundary (singular) fit: see ?isSingular</code></pre>
<p>shows a rather high negative correlation between the <code>iid</code>-wise random effects of <code>other_attr_c</code> and <code>other_intel_c</code>. Perhaps allowing the random effects to be correlated is too complex for this data. Hence, we can try a model with independent random effects:</p>
<div class="sourceCode" id="cb480"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb480-1"><a href="linear-mixed-effects-models.html#cb480-1" aria-hidden="true" tabindex="-1"></a>crmod3 <span class="ot">&lt;-</span> <span class="fu">mixed</span>(other_like <span class="sc">~</span> other_attr_c<span class="sc">*</span>other_intel_c <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">+</span> other_attr_c <span class="sc">+</span> other_intel_c<span class="sc">||</span>iid) <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">+</span> other_attr_c <span class="sc">+</span> other_intel_c<span class="sc">||</span>pid), <span class="at">data=</span>dat, <span class="at">test_intercept =</span> <span class="cn">TRUE</span>, <span class="at">method=</span><span class="st">&quot;KR&quot;</span>)</span></code></pre></div>
<pre><code>## Warning: Due to missing values, reduced number of observations to 1509</code></pre>
<pre><code>## Numerical variables NOT centered on 0: other_attr_c, other_intel_c
## If in interactions, interpretation of lower order (e.g., main) effects difficult.</code></pre>
<pre><code>## Fitting one lmer() model. [DONE]
## Calculating p-values. [DONE]</code></pre>
<p>This eliminates the boundary singular fit issue. Inspecting the random-effects estimates shows no clear signs of further problems, as all the variances are well-above 0:</p>
<div class="sourceCode" id="cb484"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb484-1"><a href="linear-mixed-effects-models.html#cb484-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(crmod3)</span></code></pre></div>
<pre><code>## Linear mixed model fit by REML. t-tests use Satterthwaite&#39;s method [
## lmerModLmerTest]
## Formula: other_like ~ other_attr_c * other_intel_c + (1 + other_attr_c +  
##     other_intel_c || iid) + (1 + other_attr_c + other_intel_c ||      pid)
##    Data: data
## 
## REML criterion at convergence: 4722.6
## 
## Scaled residuals: 
##     Min      1Q  Median      3Q     Max 
## -4.4949 -0.5229 -0.0019  0.5369  3.9118 
## 
## Random effects:
##  Groups   Name          Variance Std.Dev.
##  iid      (Intercept)   0.064981 0.25491 
##  iid.1    other_attr_c  0.016389 0.12802 
##  iid.2    other_intel_c 0.009267 0.09627 
##  pid      (Intercept)   0.260186 0.51008 
##  pid.1    other_attr_c  0.038972 0.19741 
##  pid.2    other_intel_c 0.049752 0.22305 
##  Residual               0.992730 0.99636 
## Number of obs: 1509, groups:  iid, 102; pid, 102
## 
## Fixed effects:
##                             Estimate Std. Error        df t value Pr(&gt;|t|)    
## (Intercept)                  6.23128    0.06724 115.11853  92.673  &lt; 2e-16 ***
## other_attr_c                 0.55284    0.03177 130.82879  17.399  &lt; 2e-16 ***
## other_intel_c                0.36684    0.03763  90.58968   9.749 8.94e-16 ***
## other_attr_c:other_intel_c  -0.01010    0.01249 314.62283  -0.808     0.42    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Correlation of Fixed Effects:
##             (Intr) othr_t_ othr_n_
## other_ttr_c -0.021                
## other_ntl_c -0.016 -0.153         
## othr_tt_:__ -0.066 -0.055   0.129</code></pre>
<p>Although the “keep it maximal” idea is good in theory, in practice, maximal models are often difficult or impossible to estimate. Determining an appropriate random-effects structure may require reducing the complexity of the model iteratively. Some guidelines for this process are provided by <span class="citation"><a href="#ref-matuschek_balancing_2017" role="doc-biblioref">Matuschek et al.</a> (<a href="#ref-matuschek_balancing_2017" role="doc-biblioref">2017</a>)</span>.</p>
<p>In this case, the results regarding the fixed effects are robust over the different random-effects structures. For instance, comparing the maximal model to the final model shows that the same effects are significant:</p>
<div class="sourceCode" id="cb486"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb486-1"><a href="linear-mixed-effects-models.html#cb486-1" aria-hidden="true" tabindex="-1"></a>crmod</span></code></pre></div>
<pre><code>## Warning: lme4 reported (at least) the following warnings for &#39;full&#39;:
##   * boundary (singular) fit: see ?isSingular</code></pre>
<pre><code>## Mixed Model Anova Table (Type 3 tests, KR-method)
## 
## Model: other_like ~ other_attr_c * other_intel_c + (1 + other_attr_c * 
## Model:     other_intel_c | iid) + (1 + other_attr_c * other_intel_c | 
## Model:     pid)
## Data: dat
##                       Effect        df           F p.value
## 1                (Intercept) 1, 122.81 7783.26 ***   &lt;.001
## 2               other_attr_c 1, 120.32  263.45 ***   &lt;.001
## 3              other_intel_c 1, 100.35   86.97 ***   &lt;.001
## 4 other_attr_c:other_intel_c  1, 48.28        0.42    .521
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;+&#39; 0.1 &#39; &#39; 1</code></pre>
<div class="sourceCode" id="cb489"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb489-1"><a href="linear-mixed-effects-models.html#cb489-1" aria-hidden="true" tabindex="-1"></a>crmod3</span></code></pre></div>
<pre><code>## Mixed Model Anova Table (Type 3 tests, KR-method)
## 
## Model: other_like ~ other_attr_c * other_intel_c + (1 + other_attr_c + 
## Model:     other_intel_c || iid) + (1 + other_attr_c + other_intel_c || 
## Model:     pid)
## Data: dat
##                       Effect        df           F p.value
## 1                (Intercept) 1, 120.68 8535.99 ***   &lt;.001
## 2               other_attr_c 1, 123.23  299.68 ***   &lt;.001
## 3              other_intel_c 1, 101.15   93.80 ***   &lt;.001
## 4 other_attr_c:other_intel_c 1, 353.92        0.63    .430
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;+&#39; 0.1 &#39; &#39; 1</code></pre>
<p>The <span class="math inline">\(F\)</span>-values of the last model are higher, which is consistent with the increased power that generally results from simpler random-effects structures (at a potential cost of increasing Type I error). In any case, knowing that the maximal and simpler random-effects structures both would lead to the same substantive conclusions provides some reassurance that the results are robust. The <code>afex</code> package also has a useful “vignette” (a longer document describing an analysis and package functionality) on mixed-effects models, which you can view through the command:</p>
<div class="sourceCode" id="cb491"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb491-1"><a href="linear-mixed-effects-models.html#cb491-1" aria-hidden="true" tabindex="-1"></a><span class="fu">vignette</span>(<span class="st">&quot;afex_mixed_example&quot;</span>, <span class="at">package=</span><span class="st">&quot;afex&quot;</span>)</span></code></pre></div>

</div>
</div>
<h3>References</h3>
<div id="refs" class="references csl-bib-body hanging-indent">
<div id="ref-R-lme4" class="csl-entry">
Bates, Douglas, Martin Maechler, Ben Bolker, and Steven Walker. 2021. <em>Lme4: Linear Mixed-Effects Models Using Eigen and S4</em>. <a href="https://github.com/lme4/lme4/">https://github.com/lme4/lme4/</a>.
</div>
<div id="ref-R-pbkrtest" class="csl-entry">
Højsgaard, Ulrich Halekoh Søren. 2020. <em>Pbkrtest: Parametric Bootstrap and Kenward Roger Based Methods for Mixed Model Comparison</em>. <a href="http://people.math.aau.dk/~sorenh/software/pbkrtest/">http://people.math.aau.dk/~sorenh/software/pbkrtest/</a>.
</div>
<div id="ref-R-lmerTest" class="csl-entry">
Kuznetsova, Alexandra, Per Bruun Brockhoff, and Rune Haubo Bojesen Christensen. 2020. <em>lmerTest: Tests in Linear Mixed Effects Models</em>. <a href="https://github.com/runehaubo/lmerTestR">https://github.com/runehaubo/lmerTestR</a>.
</div>
<div id="ref-matuschek_balancing_2017" class="csl-entry">
Matuschek, Hannes, Reinhold Kliegl, Shravan Vasishth, Harald Baayen, and Douglas Bates. 2017. <span>“Balancing Type i Error and Power in Linear Mixed Models.”</span> <em>Journal of Memory and Language</em> 94: 305–15. <a href="https://doi.org/10.1016/j.jml.2017.01.001">https://doi.org/10.1016/j.jml.2017.01.001</a>.
</div>
<div id="ref-R-afex" class="csl-entry">
Singmann, Henrik, Ben Bolker, Jake Westfall, Frederik Aust, and Mattan S. Ben-Shachar. 2021. <em>Afex: Analysis of Factorial Experiments</em>. <a href="https://CRAN.R-project.org/package=afex">https://CRAN.R-project.org/package=afex</a>.
</div>
<div id="ref-Singmann2019-mixed" class="csl-entry">
Singmann, Henrik, and David Kellen. 2019. <span>“An Introduction to Linear Mixed Modeling in Experimental Psychology.”</span> In <em>New Methods in Cognitive Psychology</em>, 4–31. Psychology Press. <a href="http://singmann.org/download/publications/singmann_kellen-introduction-mixed-models.pdf, preprint">http://singmann.org/download/publications/singmann_kellen-introduction-mixed-models.pdf, preprint</a>.
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="repeated-measures-anova.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="bayesian-hypothesis-testing-with-bayes-factors.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="book_assets/gitbook-2.6.7/js/app.min.js"></script>
<script src="book_assets/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="book_assets/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="book_assets/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="book_assets/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="book_assets/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="book_assets/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="book_assets/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": null,
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
},
"source": null
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
