<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 9 Bayesian hypothesis testing through Bayes Factors | An R companion to Statistics: data analysis and modelling</title>
  <meta name="description" content="A book about how to use R related to the book Statistics: Data analysis and modelling." />
  <meta name="generator" content="bookdown 0.21 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 9 Bayesian hypothesis testing through Bayes Factors | An R companion to Statistics: data analysis and modelling" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="A book about how to use R related to the book Statistics: Data analysis and modelling." />
  <meta name="github-repo" content="mspeekenbrink/sdam-book" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 9 Bayesian hypothesis testing through Bayes Factors | An R companion to Statistics: data analysis and modelling" />
  
  <meta name="twitter:description" content="A book about how to use R related to the book Statistics: Data analysis and modelling." />
  

<meta name="author" content="Maarten Speekenbrink" />


<meta name="date" content="2020-12-09" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="linear-mixed-effects-models.html"/>

<script src="book_assets/jquery-2.2.3/jquery.min.js"></script>
<link href="book_assets/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="book_assets/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="book_assets/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="book_assets/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="book_assets/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="book_assets/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="book_assets/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<script src="book_assets/accessible-code-block-0.0.1/empty-anchor.js"></script>
<link href="book_assets/anchor-sections-1.0/anchor-sections.css" rel="stylesheet" />
<script src="book_assets/anchor-sections-1.0/anchor-sections.js"></script>


<style type="text/css">
code.sourceCode > span { display: inline-block; line-height: 1.25; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a><ul>
<li class="chapter" data-level="0.1" data-path="index.html"><a href="index.html#acknowledgements"><i class="fa fa-check"></i><b>0.1</b> Acknowledgements</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="introduction.html"><a href="introduction.html"><i class="fa fa-check"></i><b>1</b> Introduction</a><ul>
<li class="chapter" data-level="1.1" data-path="introduction.html"><a href="introduction.html#what-is-r"><i class="fa fa-check"></i><b>1.1</b> What is R?</a></li>
<li class="chapter" data-level="1.2" data-path="introduction.html"><a href="introduction.html#getting-started"><i class="fa fa-check"></i><b>1.2</b> Getting started</a><ul>
<li class="chapter" data-level="1.2.1" data-path="introduction.html"><a href="introduction.html#download-r"><i class="fa fa-check"></i><b>1.2.1</b> Download R</a></li>
<li class="chapter" data-level="1.2.2" data-path="introduction.html"><a href="introduction.html#download-r-studio"><i class="fa fa-check"></i><b>1.2.2</b> Download R Studio</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="introduction.html"><a href="introduction.html#working-with-rstudio"><i class="fa fa-check"></i><b>1.3</b> Working with RStudio</a></li>
<li class="chapter" data-level="1.4" data-path="introduction.html"><a href="introduction.html#installing-packages"><i class="fa fa-check"></i><b>1.4</b> Installing packages</a><ul>
<li class="chapter" data-level="1.4.1" data-path="introduction.html"><a href="introduction.html#installing-the-sdamr-package"><i class="fa fa-check"></i><b>1.4.1</b> Installing the <code>sdamr</code> package</a></li>
</ul></li>
<li class="chapter" data-level="1.5" data-path="introduction.html"><a href="introduction.html#getting-help"><i class="fa fa-check"></i><b>1.5</b> Getting help</a></li>
<li class="chapter" data-level="1.6" data-path="introduction.html"><a href="introduction.html#first-steps-r-as-a-calculator"><i class="fa fa-check"></i><b>1.6</b> First steps: R as a calculator</a></li>
<li class="chapter" data-level="1.7" data-path="introduction.html"><a href="introduction.html#data"><i class="fa fa-check"></i><b>1.7</b> Data</a><ul>
<li class="chapter" data-level="1.7.1" data-path="introduction.html"><a href="introduction.html#data-types"><i class="fa fa-check"></i><b>1.7.1</b> Data types</a></li>
<li class="chapter" data-level="1.7.2" data-path="introduction.html"><a href="introduction.html#objects"><i class="fa fa-check"></i><b>1.7.2</b> Objects</a></li>
<li class="chapter" data-level="1.7.3" data-path="introduction.html"><a href="introduction.html#importing-data"><i class="fa fa-check"></i><b>1.7.3</b> Importing data</a></li>
</ul></li>
<li class="chapter" data-level="1.8" data-path="introduction.html"><a href="introduction.html#exploring-data-descriptive-statistics"><i class="fa fa-check"></i><b>1.8</b> Exploring data: Descriptive statistics</a></li>
<li class="chapter" data-level="1.9" data-path="introduction.html"><a href="introduction.html#exploring-data-creating-plots"><i class="fa fa-check"></i><b>1.9</b> Exploring data: Creating plots</a><ul>
<li class="chapter" data-level="1.9.1" data-path="introduction.html"><a href="introduction.html#histogram"><i class="fa fa-check"></i><b>1.9.1</b> Histogram</a></li>
<li class="chapter" data-level="1.9.2" data-path="introduction.html"><a href="introduction.html#boxplot"><i class="fa fa-check"></i><b>1.9.2</b> Boxplot</a></li>
</ul></li>
<li class="chapter" data-level="1.10" data-path="introduction.html"><a href="introduction.html#scatterplot"><i class="fa fa-check"></i><b>1.10</b> Scatterplot</a></li>
<li class="chapter" data-level="1.11" data-path="introduction.html"><a href="introduction.html#raincloud-plot"><i class="fa fa-check"></i><b>1.11</b> Raincloud plot</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="statistical-modelling.html"><a href="statistical-modelling.html"><i class="fa fa-check"></i><b>2</b> Statistical modelling</a><ul>
<li class="chapter" data-level="2.1" data-path="statistical-modelling.html"><a href="statistical-modelling.html#distributions"><i class="fa fa-check"></i><b>2.1</b> Distributions</a><ul>
<li class="chapter" data-level="2.1.1" data-path="statistical-modelling.html"><a href="statistical-modelling.html#generating-random-data"><i class="fa fa-check"></i><b>2.1.1</b> Generating random data</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="statistical-modelling.html"><a href="statistical-modelling.html#estimation"><i class="fa fa-check"></i><b>2.2</b> Estimation</a><ul>
<li class="chapter" data-level="2.2.1" data-path="statistical-modelling.html"><a href="statistical-modelling.html#the-likelihood-function"><i class="fa fa-check"></i><b>2.2.1</b> The likelihood function</a></li>
<li class="chapter" data-level="2.2.2" data-path="statistical-modelling.html"><a href="statistical-modelling.html#calculating-the-likelihood-ratio"><i class="fa fa-check"></i><b>2.2.2</b> Calculating the likelihood ratio</a></li>
<li class="chapter" data-level="2.2.3" data-path="statistical-modelling.html"><a href="statistical-modelling.html#working-out-the-theoretical-distribution-of-the-likelihood-ratio"><i class="fa fa-check"></i><b>2.2.3</b> Working out the theoretical distribution of the likelihood ratio</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="statistical-modelling.html"><a href="statistical-modelling.html#hypothesis-testing-directly-with-the-binomial-distribution"><i class="fa fa-check"></i><b>2.3</b> Hypothesis testing directly with the binomial distribution</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="the-one-sample-t-test.html"><a href="the-one-sample-t-test.html"><i class="fa fa-check"></i><b>3</b> The one-sample t-test</a><ul>
<li class="chapter" data-level="3.1" data-path="the-one-sample-t-test.html"><a href="the-one-sample-t-test.html#missing-values"><i class="fa fa-check"></i><b>3.1</b> Missing values</a></li>
<li class="chapter" data-level="3.2" data-path="the-one-sample-t-test.html"><a href="the-one-sample-t-test.html#selecting-subsets-of-data"><i class="fa fa-check"></i><b>3.2</b> Selecting subsets of data</a><ul>
<li class="chapter" data-level="3.2.1" data-path="the-one-sample-t-test.html"><a href="the-one-sample-t-test.html#the-subset-function"><i class="fa fa-check"></i><b>3.2.1</b> The <code>subset</code> function</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="the-one-sample-t-test.html"><a href="the-one-sample-t-test.html#one-sample-t-test"><i class="fa fa-check"></i><b>3.3</b> One-sample t-test</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="regression.html"><a href="regression.html"><i class="fa fa-check"></i><b>4</b> Regression</a><ul>
<li class="chapter" data-level="4.1" data-path="regression.html"><a href="regression.html#estimating-an-testing-a-simple-regression-model"><i class="fa fa-check"></i><b>4.1</b> Estimating an testing a simple regression model</a></li>
<li class="chapter" data-level="4.2" data-path="regression.html"><a href="regression.html#model-comparisons"><i class="fa fa-check"></i><b>4.2</b> Model comparisons</a></li>
<li class="chapter" data-level="4.3" data-path="regression.html"><a href="regression.html#estimating-and-testing-a-multiple-regression-model"><i class="fa fa-check"></i><b>4.3</b> Estimating and testing a multiple regression model</a></li>
<li class="chapter" data-level="4.4" data-path="regression.html"><a href="regression.html#residuals-and-predicted-values"><i class="fa fa-check"></i><b>4.4</b> Residuals and predicted values</a></li>
<li class="chapter" data-level="4.5" data-path="regression.html"><a href="regression.html#plotting-pairwise-scatterplots-for-many-variables"><i class="fa fa-check"></i><b>4.5</b> Plotting pairwise scatterplots for many variables</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="moderation-and-mediation.html"><a href="moderation-and-mediation.html"><i class="fa fa-check"></i><b>5</b> Moderation and mediation</a><ul>
<li class="chapter" data-level="5.1" data-path="moderation-and-mediation.html"><a href="moderation-and-mediation.html#moderation-in-linear-models"><i class="fa fa-check"></i><b>5.1</b> Moderation in linear models</a><ul>
<li class="chapter" data-level="5.1.1" data-path="moderation-and-mediation.html"><a href="moderation-and-mediation.html#a-bit-about-namespaces"><i class="fa fa-check"></i><b>5.1.1</b> A bit about namespaces</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="moderation-and-mediation.html"><a href="moderation-and-mediation.html#centering"><i class="fa fa-check"></i><b>5.2</b> Centering</a></li>
<li class="chapter" data-level="5.3" data-path="moderation-and-mediation.html"><a href="moderation-and-mediation.html#mediation-analysis"><i class="fa fa-check"></i><b>5.3</b> Mediation analysis</a><ul>
<li class="chapter" data-level="5.3.1" data-path="moderation-and-mediation.html"><a href="moderation-and-mediation.html#causal-steps"><i class="fa fa-check"></i><b>5.3.1</b> Causal steps</a></li>
<li class="chapter" data-level="5.3.2" data-path="moderation-and-mediation.html"><a href="moderation-and-mediation.html#investigating-the-moderated-indirect-effect-with-a-bootstrap-test"><i class="fa fa-check"></i><b>5.3.2</b> Investigating the moderated (indirect) effect with a bootstrap test</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="contrast-coding-and-oneway-anova.html"><a href="contrast-coding-and-oneway-anova.html"><i class="fa fa-check"></i><b>6</b> Contrast coding and oneway ANOVA</a><ul>
<li class="chapter" data-level="6.1" data-path="contrast-coding-and-oneway-anova.html"><a href="contrast-coding-and-oneway-anova.html#computing-contrast-coding-predictors"><i class="fa fa-check"></i><b>6.1</b> Computing contrast-coding predictors</a></li>
<li class="chapter" data-level="6.2" data-path="contrast-coding-and-oneway-anova.html"><a href="contrast-coding-and-oneway-anova.html#assigning-contrasts-to-factors"><i class="fa fa-check"></i><b>6.2</b> Assigning contrasts to factors</a><ul>
<li class="chapter" data-level="6.2.1" data-path="contrast-coding-and-oneway-anova.html"><a href="contrast-coding-and-oneway-anova.html#default-coding-schemes"><i class="fa fa-check"></i><b>6.2.1</b> Default coding schemes</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="factorial-anova.html"><a href="factorial-anova.html"><i class="fa fa-check"></i><b>7</b> Factorial ANOVA</a><ul>
<li class="chapter" data-level="7.1" data-path="factorial-anova.html"><a href="factorial-anova.html#rainclouds-for-factorial-designs"><i class="fa fa-check"></i><b>7.1</b> Rainclouds for factorial designs</a></li>
<li class="chapter" data-level="7.2" data-path="factorial-anova.html"><a href="factorial-anova.html#formulating-estimating-and-testing-a-factorial-anova"><i class="fa fa-check"></i><b>7.2</b> Formulating, estimating, and testing a factorial ANOVA</a><ul>
<li class="chapter" data-level="7.2.1" data-path="factorial-anova.html"><a href="factorial-anova.html#a-threeway-anova"><i class="fa fa-check"></i><b>7.2.1</b> A threeway ANOVA</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="factorial-anova.html"><a href="factorial-anova.html#type-1-2-and-3-sums-of-squares"><i class="fa fa-check"></i><b>7.3</b> Type 1, 2, and 3 Sums of Squares</a></li>
<li class="chapter" data-level="7.4" data-path="factorial-anova.html"><a href="factorial-anova.html#planned-comparisons-and-post-hoc-tests-with-emmeans"><i class="fa fa-check"></i><b>7.4</b> Planned comparisons and post-hoc tests with <code>emmeans</code></a><ul>
<li class="chapter" data-level="7.4.1" data-path="factorial-anova.html"><a href="factorial-anova.html#adjusted-p-values"><i class="fa fa-check"></i><b>7.4.1</b> Adjusted p-values</a></li>
</ul></li>
<li class="chapter" data-level="7.5" data-path="factorial-anova.html"><a href="factorial-anova.html#testing-general-contrasts-with-emmeans"><i class="fa fa-check"></i><b>7.5</b> Testing general contrasts with <code>emmeans</code></a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="linear-mixed-effects-models.html"><a href="linear-mixed-effects-models.html"><i class="fa fa-check"></i><b>8</b> Linear mixed-effects models</a><ul>
<li class="chapter" data-level="8.1" data-path="linear-mixed-effects-models.html"><a href="linear-mixed-effects-models.html#formulating-and-estimating-linear-mixed-effects-models-with-lme4"><i class="fa fa-check"></i><b>8.1</b> Formulating and estimating linear mixed-effects models with <code>lme4</code></a><ul>
<li class="chapter" data-level="8.1.1" data-path="linear-mixed-effects-models.html"><a href="linear-mixed-effects-models.html#random-intercepts-model"><i class="fa fa-check"></i><b>8.1.1</b> Random intercepts model</a></li>
<li class="chapter" data-level="8.1.2" data-path="linear-mixed-effects-models.html"><a href="linear-mixed-effects-models.html#visually-assessing-model-assumptions"><i class="fa fa-check"></i><b>8.1.2</b> Visually assessing model assumptions</a></li>
<li class="chapter" data-level="8.1.3" data-path="linear-mixed-effects-models.html"><a href="linear-mixed-effects-models.html#random-intercepts-and-slopes"><i class="fa fa-check"></i><b>8.1.3</b> Random intercepts and slopes</a></li>
<li class="chapter" data-level="8.1.4" data-path="linear-mixed-effects-models.html"><a href="linear-mixed-effects-models.html#likelihood-ratio-test-with-the-anova-function"><i class="fa fa-check"></i><b>8.1.4</b> Likelihood ratio test with the <code>anova</code> function</a></li>
<li class="chapter" data-level="8.1.5" data-path="linear-mixed-effects-models.html"><a href="linear-mixed-effects-models.html#confidence-intervals"><i class="fa fa-check"></i><b>8.1.5</b> Confidence intervals</a></li>
<li class="chapter" data-level="8.1.6" data-path="linear-mixed-effects-models.html"><a href="linear-mixed-effects-models.html#plotting-model-predictions"><i class="fa fa-check"></i><b>8.1.6</b> Plotting model predictions</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="linear-mixed-effects-models.html"><a href="linear-mixed-effects-models.html#obtaining-p-values-with-afexmixed"><i class="fa fa-check"></i><b>8.2</b> Obtaining p-values with <code>afex::mixed</code></a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="bayesian-hypothesis-testing-through-bayes-factors.html"><a href="bayesian-hypothesis-testing-through-bayes-factors.html"><i class="fa fa-check"></i><b>9</b> Bayesian hypothesis testing through Bayes Factors</a><ul>
<li class="chapter" data-level="9.1" data-path="bayesian-hypothesis-testing-through-bayes-factors.html"><a href="bayesian-hypothesis-testing-through-bayes-factors.html#the-bayesfactor-package"><i class="fa fa-check"></i><b>9.1</b> The <code>BayesFactor</code> package</a><ul>
<li class="chapter" data-level="9.1.1" data-path="bayesian-hypothesis-testing-through-bayes-factors.html"><a href="bayesian-hypothesis-testing-through-bayes-factors.html#a-bayesian-one-sample-t-test"><i class="fa fa-check"></i><b>9.1.1</b> A Bayesian one-sample t-test</a></li>
<li class="chapter" data-level="9.1.2" data-path="bayesian-hypothesis-testing-through-bayes-factors.html"><a href="bayesian-hypothesis-testing-through-bayes-factors.html#a-bayesian-two-sample-t-test"><i class="fa fa-check"></i><b>9.1.2</b> A Bayesian two-sample t-test</a></li>
<li class="chapter" data-level="9.1.3" data-path="bayesian-hypothesis-testing-through-bayes-factors.html"><a href="bayesian-hypothesis-testing-through-bayes-factors.html#a-bayesian-anova"><i class="fa fa-check"></i><b>9.1.3</b> A Bayesian ANOVA</a></li>
<li class="chapter" data-level="9.1.4" data-path="bayesian-hypothesis-testing-through-bayes-factors.html"><a href="bayesian-hypothesis-testing-through-bayes-factors.html#bayesian-regression-and-ancova"><i class="fa fa-check"></i><b>9.1.4</b> Bayesian regression and ANCOVA</a></li>
</ul></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">An R companion to Statistics: data analysis and modelling</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="bayesian-hypothesis-testing-through-bayes-factors" class="section level1">
<h1><span class="header-section-number">Chapter 9</span> Bayesian hypothesis testing through Bayes Factors</h1>
<p>In this chapter, we will discuss how to compute Bayes Factors for a variety of General Linear Models using the <code>BayesFactor</code> package <span class="citation">(Morey and Rouder <a href="#ref-R-BayesFactor" role="doc-biblioref">2018</a>)</span>. The package implements the “default” priors discussed in the SDAM book. <!-- More complex Bayesian models, such as mixed-effects and multilevel models, can be estimated with the `brms` package, and we will briefly touch upon this at the end of the chapter. --></p>
<div id="the-bayesfactor-package" class="section level2">
<h2><span class="header-section-number">9.1</span> The <code>BayesFactor</code> package</h2>
<p>The <code>BayesFactor</code> package implements Bayesian model comparisons for General Linear Models (as well as some other models for e.g. contingency tables and proportions) using JZS-priors for the parameters, or fixing those parameters to 0. Because Bayes Factors are <strong>transitive</strong>, in the sense that a ratio of Bayes Factor is itself another Bayes factor:
<span class="math display">\[\begin{align}
\text{BF}_{1,2} &amp;= \frac{p(Y_1,\ldots,Y_n|\text{MODEL 1})}{p(Y_1,\ldots,Y_n|\text{MODEL 2})} \\
&amp;= \frac{p(Y_1,\ldots,Y_n|\text{MODEL 1})/p(Y_1,\ldots,Y_n|\text{MODEL 0})} {p(Y_1,\ldots,Y_n|\text{MODEL 2})/p(Y_1,\ldots,Y_n|\text{MODEL 0})} \\
&amp;= \frac{\text{BF}_{1,0}}{\text{BF}_{2,0}}
\end{align}\]</span>
You can compute many other Bayes Factors which might not be provided by the package by simply dividing the Bayes factors that the package does provide. This makes the procedure of model comparison very flexible.</p>
<p>If you haven’t installed the <code>BayesFactor</code> package yet, you need to do so first. Then you can load it as usual by:</p>
<div class="sourceCode" id="cb330"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb330-1"><a href="bayesian-hypothesis-testing-through-bayes-factors.html#cb330-1"></a><span class="kw">library</span>(BayesFactor)</span></code></pre></div>
<div id="a-bayesian-one-sample-t-test" class="section level3">
<h3><span class="header-section-number">9.1.1</span> A Bayesian one-sample t-test</h3>
<p>A Bayesian alternative to a <span class="math inline">\(t\)</span>-test is provided via the <code>ttestBF</code> function. Similar to the <code>t.test</code> function in the base <code>stats</code> package, this function allows computation of a Bayes factor for a one-sample t-test and independent-samples t-tests (as well as a paired t-test, which we haven’t covered in the course). Let’s re-analyse the data we considered before, concerning participants’ judegments of the height of Mount Everest. The one-sample t-test we computed before, comparing the judgements to an assumed mean of <span class="math inline">\(\mu = 8848\)</span>, was:</p>
<div class="sourceCode" id="cb331"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb331-1"><a href="bayesian-hypothesis-testing-through-bayes-factors.html#cb331-1"></a><span class="co"># load the data</span></span>
<span id="cb331-2"><a href="bayesian-hypothesis-testing-through-bayes-factors.html#cb331-2"></a><span class="kw">library</span>(sdamr)</span>
<span id="cb331-3"><a href="bayesian-hypothesis-testing-through-bayes-factors.html#cb331-3"></a><span class="kw">data</span>(<span class="st">&quot;anchoring&quot;</span>)</span>
<span id="cb331-4"><a href="bayesian-hypothesis-testing-through-bayes-factors.html#cb331-4"></a><span class="co"># select the subset we analysed in Chapter 3</span></span>
<span id="cb331-5"><a href="bayesian-hypothesis-testing-through-bayes-factors.html#cb331-5"></a>dat &lt;-<span class="st"> </span><span class="kw">subset</span>(anchoring,(referrer <span class="op">==</span><span class="st"> &quot;swps&quot;</span> <span class="op">|</span><span class="st"> </span>referrer <span class="op">==</span><span class="st"> &quot;swpson&quot;</span>) <span class="op">&amp;</span><span class="st"> </span>anchor <span class="op">==</span><span class="st"> &quot;low&quot;</span>)</span>
<span id="cb331-6"><a href="bayesian-hypothesis-testing-through-bayes-factors.html#cb331-6"></a><span class="co"># compute the Frequentist one-sample t-test</span></span>
<span id="cb331-7"><a href="bayesian-hypothesis-testing-through-bayes-factors.html#cb331-7"></a><span class="kw">t.test</span>(dat<span class="op">$</span>everest_meters, <span class="dt">mu=</span><span class="dv">8848</span>)</span></code></pre></div>
<pre><code>## 
##  One Sample t-test
## 
## data:  dat$everest_meters
## t = -8.4429, df = 108, p-value = 1.558e-13
## alternative hypothesis: true mean is not equal to 8848
## 95 percent confidence interval:
##  5716.848 6907.537
## sample estimates:
## mean of x 
##  6312.193</code></pre>
<p>The syntax for the Bayesian alternative is <em>very</em> similar, namely:</p>
<div class="sourceCode" id="cb333"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb333-1"><a href="bayesian-hypothesis-testing-through-bayes-factors.html#cb333-1"></a>bf_anchor &lt;-<span class="st"> </span><span class="kw">ttestBF</span>(dat<span class="op">$</span>everest_meters, <span class="dt">mu=</span><span class="dv">8848</span>)</span></code></pre></div>
<p>This code provides a test of the following models:</p>
<p><span class="math display">\[\begin{align}
H_0\!&amp;: \mu = 8848 \\
H_1\!&amp;: \frac{\mu - 8848}{\sigma_\epsilon} \sim \textbf{Cauchy}(r)
\end{align}\]</span></p>
<p>After computing the Bayes factor and storing it in an object <code>bf_anchor</code>, we just see the print-out of the result by typing in the name of the object:</p>
<div class="sourceCode" id="cb334"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb334-1"><a href="bayesian-hypothesis-testing-through-bayes-factors.html#cb334-1"></a>bf_anchor</span></code></pre></div>
<pre><code>## Bayes factor analysis
## --------------
## [1] Alt., r=0.707 : 46902934208 ±0%
## 
## Against denominator:
##   Null, mu = 8848 
## ---
## Bayes factor type: BFoneSample, JZS</code></pre>
<p>This output is quite sparse, which is by no means a bad thing. It shows a few important things. Under <code>Alt.</code> (which stands for the alternative hypothesis), we first see the scaling factor <span class="math inline">\(r\)</span> used for the JZS prior distribution on the effect size. We then see the value of the Bayes Factor, which is “extreme”, showing that the alternative hypothesis at 46,902,934,208. Quite clearly, the average judgements differed from the true height of Mount Everest! After the computed value of the Bayes factor, you will find a proportional error estimate on the Bayes factor. In general, the marginal likelihoods that constitute the numerator (“top model”) and denominator (“bottom model”) of the Bayes factor can not be computed exactly, and have to be approximated by numerical integration routines, or simulation. This results in some (hopefully small) error in computation, and the error estimate indicates the extend to which the true Bayes factor might differ from the computed one. In this case, the error is (proportionally) very small, and hence we can be assured that our conclusion is unlikely to be affected by error in the approximation.</p>
<p>As we didn’t set the scaling factor explicitly, the default value is used, which is <span class="math inline">\(r = \frac{\sqrt{2}}{2} = 0.707\)</span>. Note that this is actually different from the default value of <span class="math inline">\(r=1\)</span> used in <span class="citation">Rouder et al. (<a href="#ref-rouder2009bayesian" role="doc-biblioref">2009</a>)</span>, which first introduced this version of the Bayesian t-test to a psychological audience, and the one used to illustrate the method in the SDAM book. While reducing the default value to <span class="math inline">\(r=0.707\)</span> is probably reasonable given the effect sizes generally encountered in psychological studies, a change in the default prior highlights the subjective nature of the prior distribution in the Bayesian model comparison procedure. You should also realise that different analyses, such as t-tests, ANOVA, and regression models, use different default values for the scaling factor. As shown in the SDAM book, the value of the Bayes factor depends on the choice for the scaling factor. Although the default value may be deemed reasonable, the choice should really be based on a consideration of the magnitude of the effect sizes you (yes, you!) expect in a particular study. This is not always easy, but you should pick one (the default value, for instance, if you can’t think of a better one) <em>before</em> conducting the analysis. If you feel that makes the test too subjective, you may may want to check the robustness of the result for different choices of the scaling factor. You can do this by computing the Bayes factor for a range of choices of the scaling factor, and then inspecting whether the strength of the evidence is in line with your choice for a reasonable range of values around your choice. The code below provides an example of this:</p>
<div class="sourceCode" id="cb336"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb336-1"><a href="bayesian-hypothesis-testing-through-bayes-factors.html#cb336-1"></a><span class="co"># create a vector with different values for the scaling factor r</span></span>
<span id="cb336-2"><a href="bayesian-hypothesis-testing-through-bayes-factors.html#cb336-2"></a>rscale &lt;-<span class="st"> </span><span class="kw">seq</span>(.<span class="dv">001</span>,<span class="dv">3</span>,<span class="dt">length=</span><span class="dv">100</span>)</span>
<span id="cb336-3"><a href="bayesian-hypothesis-testing-through-bayes-factors.html#cb336-3"></a></span>
<span id="cb336-4"><a href="bayesian-hypothesis-testing-through-bayes-factors.html#cb336-4"></a><span class="co"># create an ampty vector to store the resulting Bayes factors</span></span>
<span id="cb336-5"><a href="bayesian-hypothesis-testing-through-bayes-factors.html#cb336-5"></a>BFs &lt;-<span class="st"> </span><span class="kw">vector</span>(<span class="st">&quot;double&quot;</span>, <span class="dt">length=</span><span class="dv">100</span>)</span>
<span id="cb336-6"><a href="bayesian-hypothesis-testing-through-bayes-factors.html#cb336-6"></a></span>
<span id="cb336-7"><a href="bayesian-hypothesis-testing-through-bayes-factors.html#cb336-7"></a><span class="co"># compute the Bayes factor for each value of r</span></span>
<span id="cb336-8"><a href="bayesian-hypothesis-testing-through-bayes-factors.html#cb336-8"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="op">:</span><span class="dv">100</span>) {</span>
<span id="cb336-9"><a href="bayesian-hypothesis-testing-through-bayes-factors.html#cb336-9"></a>  temp_bf &lt;-<span class="st"> </span><span class="kw">ttestBF</span>(dat<span class="op">$</span>everest_meters, <span class="dt">mu=</span><span class="dv">8848</span>, <span class="dt">r =</span> rscale[i])</span>
<span id="cb336-10"><a href="bayesian-hypothesis-testing-through-bayes-factors.html#cb336-10"></a>  <span class="co"># the object returned by the ttestBF function is a so-called S4 object</span></span>
<span id="cb336-11"><a href="bayesian-hypothesis-testing-through-bayes-factors.html#cb336-11"></a>  <span class="co"># this has &quot;slots&quot; which can be accessed through the &quot;@&quot; operatpr</span></span>
<span id="cb336-12"><a href="bayesian-hypothesis-testing-through-bayes-factors.html#cb336-12"></a>  <span class="co"># the actual value for the BF is extracted by @bayesFactor$bf</span></span>
<span id="cb336-13"><a href="bayesian-hypothesis-testing-through-bayes-factors.html#cb336-13"></a>  <span class="co"># which is stored in a logarithmic scale, so we need to use &quot;exp&quot;</span></span>
<span id="cb336-14"><a href="bayesian-hypothesis-testing-through-bayes-factors.html#cb336-14"></a>  <span class="co"># to obtain the value of the actual Bayes factor </span></span>
<span id="cb336-15"><a href="bayesian-hypothesis-testing-through-bayes-factors.html#cb336-15"></a>  BFs[i] &lt;-<span class="st"> </span><span class="kw">exp</span>(temp_bf<span class="op">@</span>bayesFactor<span class="op">$</span>bf)</span>
<span id="cb336-16"><a href="bayesian-hypothesis-testing-through-bayes-factors.html#cb336-16"></a>}</span>
<span id="cb336-17"><a href="bayesian-hypothesis-testing-through-bayes-factors.html#cb336-17"></a><span class="co"># use ggplot to plot the values of the Bayes factor against the choice of r</span></span>
<span id="cb336-18"><a href="bayesian-hypothesis-testing-through-bayes-factors.html#cb336-18"></a><span class="kw">library</span>(ggplot2)</span>
<span id="cb336-19"><a href="bayesian-hypothesis-testing-through-bayes-factors.html#cb336-19"></a><span class="kw">ggplot</span>(<span class="kw">data.frame</span>(<span class="dt">r=</span>rscale,<span class="dt">BF=</span>BFs),<span class="kw">aes</span>(<span class="dt">x=</span>r,<span class="dt">y=</span>BF)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_line</span>()</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-190-1.svg" width="672" style="display: block; margin: auto;" /></p>
<p>Given the scale of the <span class="math inline">\(y\)</span>-axis, there is overwhelming evidence against the null-hypothesis for most choices of the scaling factor. Hence, the results seem rather robust to the exact choice of prior.</p>
</div>
<div id="a-bayesian-two-sample-t-test" class="section level3">
<h3><span class="header-section-number">9.1.2</span> A Bayesian two-sample t-test</h3>
<p>To compare the means of two groups, we can revisit the Tetris study, where we considered whether the number of memory intrusions is reduced after playing Tetris in combination with memory reactivation, compared to just memory reactivation by itself. The <code>ttestBF</code> function allows us to provide the data for one group as the <code>x</code> argument, and the data for the other group as the <code>y</code> argument, so we can perform our model comparison, by subsetting the dependent variable appropriately, as follows:</p>
<div class="sourceCode" id="cb337"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb337-1"><a href="bayesian-hypothesis-testing-through-bayes-factors.html#cb337-1"></a><span class="kw">data</span>(<span class="st">&quot;tetris2015&quot;</span>)</span>
<span id="cb337-2"><a href="bayesian-hypothesis-testing-through-bayes-factors.html#cb337-2"></a>bf_tetr &lt;-<span class="st"> </span><span class="kw">ttestBF</span>(<span class="dt">x=</span>tetris2015<span class="op">$</span>Days_One_to_Seven_Number_of_Intrusions[tetris2015<span class="op">$</span>Condition <span class="op">==</span><span class="st"> &quot;Reactivation&quot;</span>], <span class="dt">y =</span> tetris2015<span class="op">$</span>Days_One_to_Seven_Number_of_Intrusions[tetris2015<span class="op">$</span>Condition <span class="op">==</span><span class="st"> &quot;Tetris_Reactivation&quot;</span>])</span>
<span id="cb337-3"><a href="bayesian-hypothesis-testing-through-bayes-factors.html#cb337-3"></a>bf_tetr</span></code></pre></div>
<pre><code>## Bayes factor analysis
## --------------
## [1] Alt., r=0.707 : 16.78482 ±0%
## 
## Against denominator:
##   Null, mu1-mu2 = 0 
## ---
## Bayes factor type: BFindepSample, JZS</code></pre>
<p>Which shows strong evidence for the alternative hypothesis over the null hypothesis that the means are identical (i.e. that the difference between the means is zero, <span class="math inline">\(\mu_1 - \mu_2 = 0\)</span>), as the alternative model is 2.82 times more likely than the null model, which sets the difference between the means to exactly <span class="math inline">\(\mu_1 - \mu_2 = 0\)</span>, rather than allowing different values of this difference through the prior distribution.</p>
<p>A two-sample t-test should really be identical to a two-group ANOVA model, as both concern the same General Linear Model (a model with a single contrast-coding predictor, with e.q. values of <span class="math inline">\(-\tfrac{1}{2}\)</span> and <span class="math inline">\(\tfrac{1}{2}\)</span>). Before fully discussing the way to perform an ANOVA-type analysis with the <code>BayesFactor</code> package, let’s just double-check this is indeed the case:</p>
<div class="sourceCode" id="cb339"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb339-1"><a href="bayesian-hypothesis-testing-through-bayes-factors.html#cb339-1"></a>dat &lt;-<span class="st"> </span><span class="kw">subset</span>(tetris2015, Condition <span class="op">%in%</span><span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;Tetris_Reactivation&quot;</span>,<span class="st">&quot;Reactivation&quot;</span>))</span>
<span id="cb339-2"><a href="bayesian-hypothesis-testing-through-bayes-factors.html#cb339-2"></a><span class="co"># remove levels of Condition that are no longer needed due to subsetting</span></span>
<span id="cb339-3"><a href="bayesian-hypothesis-testing-through-bayes-factors.html#cb339-3"></a>dat<span class="op">$</span>Condition &lt;-<span class="st"> </span><span class="kw">droplevels</span>(dat<span class="op">$</span>Condition)</span>
<span id="cb339-4"><a href="bayesian-hypothesis-testing-through-bayes-factors.html#cb339-4"></a><span class="co">#contrasts(dat$Condition) &lt;- c(-1/2,1/2)</span></span>
<span id="cb339-5"><a href="bayesian-hypothesis-testing-through-bayes-factors.html#cb339-5"></a>bf2_tetr &lt;-<span class="st"> </span><span class="kw">anovaBF</span>(Days_One_to_Seven_Number_of_Intrusions <span class="op">~</span><span class="st"> </span>Condition, <span class="dt">data =</span> dat)</span>
<span id="cb339-6"><a href="bayesian-hypothesis-testing-through-bayes-factors.html#cb339-6"></a>bf2_tetr</span></code></pre></div>
<pre><code>## Bayes factor analysis
## --------------
## [1] Condition : 16.78482 ±0%
## 
## Against denominator:
##   Intercept only 
## ---
## Bayes factor type: BFlinearModel, JZS</code></pre>
<p>The results are indeed identical. Note that this is because both the <code>ttestBF</code> and <code>anovaBF</code> function use the same prior distribution for the effect.</p>
</div>
<div id="a-bayesian-anova" class="section level3">
<h3><span class="header-section-number">9.1.3</span> A Bayesian ANOVA</h3>
<p>More general ANOVA-type models can be tested though the <code>anovaBF</code> function. This function takes the following important arguments:</p>
<ul>
<li><code>formula</code>: a formula like in the <code>lm</code> function, specifying which factors to include as well as their interactions (by e.g. using an <code>*</code> operator to specify you want to include the main effects as well as their interactions. Note that unlike in the <code>lm</code> function, <strong>all terms must be factors</strong>.</li>
<li><code>data</code>: a <code>data.frame</code> containing data for all factors in the formula.</li>
<li><code>whichRandom</code>: a character vector specifying which factors are random. Random factors can be used to obtain a model similar to a repeated-measures ANOVA, or a (restricted) set of linear-mixed effects models (with only factors for the fixed effects).</li>
<li><code>whichModels</code>: a character vector specifying which models to compare. The allowed values are <code>"all"</code>, <code>"withmain"</code> (the default), <code>"top"</code>, and <code>"bottom"</code>. Setting <code>whichModels</code> to <code>"all"</code> will test all models that can be created by including or not including a main effect or interaction. <code>"top"</code> will test all models that can be created by removing or leaving in a main effect or interaction term from the full model. <code>"bottom"</code> creates models by adding single factors or interactions to the null model. <code>"withmain"</code> will test all models, with the constraint that if an interaction is included, the corresponding main effects are also included. Setting the argument to <code>top</code> produces model comparisons similar to the Type 3 procedure, comparing the full model to a restricted model with each effect removed. Setting the argument to <code>withMain</code> produces model comparisons similar to the Type 2 procedure, with model comparisons that respect the “principle of marginality”, such that tests of the main effects do not consider higher-order interactions, whilst a test of any interaction includes the main effects that constitute the elements in the interactions.</li>
<li><code>rscaleFixed</code>: prior scale for fixed effects. The value can be given numerically, or as one of three strings: <code>"medium"</code> (<span class="math inline">\(r = \tfrac{1}{2}\)</span>), <code>"wide"</code>: <span class="math inline">\(r = \tfrac{\sqrt{2}}{2}\)</span>, or <code>"ultrawide"</code> (<span class="math inline">\(r=1\)</span>). The default is "<code>medium"</code>.</li>
<li><code>rscaleRandom</code>: prior scale for random effects. Accepts the same strings as <code>rscaleFixed</code>, and in addition <code>"nuisance"</code> (<span class="math inline">\(r = 1\)</span>). The default is <code>"nuisance"</code>.</li>
<li><code>rscaleEffects</code>: a named vector with prior scales for individual factors.</li>
</ul>
<p>The <code>anovaBF</code> function will (as far as I can gather) <strong>always use <code>contr.sum()</code> contrasts for the factors</strong>. So setting your own contrasts will have no effect on the results. The exact contrast should not really matter for omnibus tests, and sum-to-zero are a reasonable choice in general (<code>contr.sum</code> implements what we called effect-coding before).<a href="#fn3" class="footnote-ref" id="fnref3"><sup>3</sup></a> While the <code>anovaBF</code> function always uses the JZS prior for any effects, it allows you to specify exactly which scaling factor to use for every effect, if so desired.</p>
<p>Let’s see what happens when we use a Bayesian ANOVA-type analysis for the data on experimenter beliefs in social priming. First, let’s load the data, and turn the variables reflecting the experimental manipulations into factors:</p>
<div class="sourceCode" id="cb341"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb341-1"><a href="bayesian-hypothesis-testing-through-bayes-factors.html#cb341-1"></a><span class="kw">data</span>(<span class="st">&quot;expBelief&quot;</span>)</span>
<span id="cb341-2"><a href="bayesian-hypothesis-testing-through-bayes-factors.html#cb341-2"></a>dat &lt;-<span class="st"> </span>expBelief</span>
<span id="cb341-3"><a href="bayesian-hypothesis-testing-through-bayes-factors.html#cb341-3"></a>dat<span class="op">$</span>primeCond &lt;-<span class="st"> </span><span class="kw">factor</span>(dat<span class="op">$</span>primeCond)</span>
<span id="cb341-4"><a href="bayesian-hypothesis-testing-through-bayes-factors.html#cb341-4"></a>dat<span class="op">$</span>experimenterBelief &lt;-<span class="st"> </span><span class="kw">factor</span>(dat<span class="op">$</span>experimenterBelief)</span></code></pre></div>
<p>We can now use the <code>anofaBF</code> function to compute the Bayes factors:</p>
<div class="sourceCode" id="cb342"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb342-1"><a href="bayesian-hypothesis-testing-through-bayes-factors.html#cb342-1"></a>bf_expB &lt;-<span class="st"> </span><span class="kw">anovaBF</span>(ApproachAdvantage <span class="op">~</span><span class="st"> </span>primeCond<span class="op">*</span>experimenterBelief, <span class="dt">data =</span> dat)</span>
<span id="cb342-2"><a href="bayesian-hypothesis-testing-through-bayes-factors.html#cb342-2"></a>bf_expB</span></code></pre></div>
<pre><code>## Bayes factor analysis
## --------------
## [1] experimenterBelief                                            : 537.3879  ±0%
## [2] primeCond                                                     : 0.1282136 ±0%
## [3] experimenterBelief + primeCond                                : 69.75452  ±0.99%
## [4] experimenterBelief + primeCond + experimenterBelief:primeCond : 15.18165  ±1.41%
## 
## Against denominator:
##   Intercept only 
## ---
## Bayes factor type: BFlinearModel, JZS</code></pre>
<p>A main thing to note here is that the comparisons of different versions of MODEL G are against the same MODEL R, which is an intercept-only model. We can see that all models which include <code>experimenterBelief</code> receive strong evidence against the intercept-only model, apart from the model which only includes <code>primeCond</code>, which has less evidence than the intercept-only model. Although this indicates that the <code>primeCond</code> effect might be ignorable, the comparisons are different from comparing reduced models to the general MODEL G with all effects included. We can obtain these Type 3 comparisons by setting the <code>whichModels</code> argument to `“top”``:</p>
<div class="sourceCode" id="cb344"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb344-1"><a href="bayesian-hypothesis-testing-through-bayes-factors.html#cb344-1"></a>bf_expB2 &lt;-<span class="st"> </span><span class="kw">anovaBF</span>(ApproachAdvantage <span class="op">~</span><span class="st"> </span>primeCond<span class="op">*</span>experimenterBelief, <span class="dt">data =</span> dat, <span class="dt">whichModels =</span> <span class="st">&quot;top&quot;</span>)</span>
<span id="cb344-2"><a href="bayesian-hypothesis-testing-through-bayes-factors.html#cb344-2"></a>bf_expB2</span></code></pre></div>
<pre><code>## Bayes factor top-down analysis
## --------------
## When effect is omitted from experimenterBelief + primeCond + experimenterBelief:primeCond , BF is...
## [1] Omit experimenterBelief:primeCond : 4.726269    ±3.59%
## [2] Omit primeCond                    : 8.262924    ±4.69%
## [3] Omit experimenterBelief           : 0.001940934 ±3.64%
## 
## Against denominator:
##   ApproachAdvantage ~ experimenterBelief + primeCond + experimenterBelief:primeCond 
## ---
## Bayes factor type: BFlinearModel, JZS</code></pre>
<p>It is very important to realise that the output now concerns the comparison of the reduced model (in the numerator, ie. the “top model”) against the full model (in the denominator, i.e. the “bottom model”), as is stated in the <code>Against denimonator</code> part of the output. That means that low values of the Bayes factor now indicate evidence for the alternative hypothesis that an effect is different from 0. We can change the output in a measure of the alternative model against the null model by inverting the Bayes factor as follows:</p>
<div class="sourceCode" id="cb346"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb346-1"><a href="bayesian-hypothesis-testing-through-bayes-factors.html#cb346-1"></a><span class="dv">1</span><span class="op">/</span>bf_expB2</span></code></pre></div>
<pre><code>##                                                                denominator
## numerator                                                       experimenterBelief + primeCond
##   experimenterBelief + primeCond + experimenterBelief:primeCond                      0.2115834
##                                                                denominator
## numerator                                                       experimenterBelief + experimenterBelief:primeCond
##   experimenterBelief + primeCond + experimenterBelief:primeCond                                         0.1210225
##                                                                denominator
## numerator                                                       primeCond + experimenterBelief:primeCond
##   experimenterBelief + primeCond + experimenterBelief:primeCond                                 515.2159</code></pre>
<p>which now shows strong evidence for the effect of <code>experimenterBelief</code> when we remove it from the full model.</p>
<p>The transitivity of the Bayes factor means that we can also obtain some of these results through a ratio of the Bayes factors obtained earlier. For instance, a Type 3 test of the effect of <code>experimenterBelief:primeCond</code> interaction can be obtained by comparing a model with all effects included to a model without this interaction. In the analysis stored in <code>bf_expB</code>, we compared a number of the possible models to an intercept-only model. By comparing the Bayes factors of the model which excludes the interaction to a model which includes it, we can obtain the same Bayes factor of that interaction as follows. In the output of <code>bf_expB</code>, the fourth element compared the full model to the intercept-only model, whilst in the third element, a model with only the main effects of <code>experimenterBelief</code> and <code>primeCond</code> are compared to an intercept-only model. The Type 3 test of the interaction can then be obtained through the ratio of these two Bayes factors:</p>
<div class="sourceCode" id="cb348"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb348-1"><a href="bayesian-hypothesis-testing-through-bayes-factors.html#cb348-1"></a>bf_expB[<span class="dv">4</span>]<span class="op">/</span>bf_expB[<span class="dv">3</span>]</span></code></pre></div>
<pre><code>## Bayes factor analysis
## --------------
## [1] experimenterBelief + primeCond + experimenterBelief:primeCond : 0.217644 ±1.72%
## 
## Against denominator:
##   ApproachAdvantage ~ experimenterBelief + primeCond 
## ---
## Bayes factor type: BFlinearModel, JZS</code></pre>
<p>which indicates evidence for the null hypothesis that there is no moderation of the effect of <code>experimenterbelief</code> by <code>primeCond</code>, as the Bayes factor is well below 1. We cannot replicate all Type 3 analyses with the results obtained earlier, unless we ask the function to compare every possible model against the intercept-only model, by specifying <code>whichModels = "all"</code>:</p>
<div class="sourceCode" id="cb350"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb350-1"><a href="bayesian-hypothesis-testing-through-bayes-factors.html#cb350-1"></a>bf_expB3 &lt;-<span class="st"> </span><span class="kw">anovaBF</span>(ApproachAdvantage <span class="op">~</span><span class="st"> </span>primeCond<span class="op">*</span>experimenterBelief, <span class="dt">data =</span> dat, <span class="dt">whichModels =</span> <span class="st">&quot;all&quot;</span>)</span>
<span id="cb350-2"><a href="bayesian-hypothesis-testing-through-bayes-factors.html#cb350-2"></a>bf_expB3</span></code></pre></div>
<pre><code>## Bayes factor analysis
## --------------
## [1] experimenterBelief                                            : 537.3879   ±0%
## [2] primeCond                                                     : 0.1282136  ±0%
## [3] experimenterBelief:primeCond                                  : 0.1613884  ±0%
## [4] experimenterBelief + primeCond                                : 67.2707    ±2.01%
## [5] experimenterBelief + experimenterBelief:primeCond             : 121.471    ±2.62%
## [6] primeCond + experimenterBelief:primeCond                      : 0.02731733 ±1.78%
## [7] experimenterBelief + primeCond + experimenterBelief:primeCond : 15.09079   ±1.38%
## 
## Against denominator:
##   Intercept only 
## ---
## Bayes factor type: BFlinearModel, JZS</code></pre>
<p>For instance, we can now obtain a Type 3 test for <code>experimenterBelief</code> by comparing the full model (the 7th element in the output) to a model which just excludes this effect (i.e. the 6th element):</p>
<div class="sourceCode" id="cb352"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb352-1"><a href="bayesian-hypothesis-testing-through-bayes-factors.html#cb352-1"></a>bf_expB3[<span class="dv">7</span>]<span class="op">/</span>bf_expB3[<span class="dv">6</span>]</span></code></pre></div>
<pre><code>## Bayes factor analysis
## --------------
## [1] experimenterBelief + primeCond + experimenterBelief:primeCond : 552.4256 ±2.25%
## 
## Against denominator:
##   ApproachAdvantage ~ primeCond + experimenterBelief:primeCond 
## ---
## Bayes factor type: BFlinearModel, JZS</code></pre>
<p>which reproduces mostly the result we obtained by setting <code>whichModel = "top"</code> before.</p>
</div>
<div id="bayesian-regression-and-ancova" class="section level3">
<h3><span class="header-section-number">9.1.4</span> Bayesian regression and ANCOVA</h3>
<p>Apart from different default values of the scaling factor <span class="math inline">\(r\)</span> in the scaled-Cauchy distribution, the <code>BayesFactor</code> package works in the same way for models which include metric predictors. In a multiple regression model with only metric predictors, we can use the convenience function <code>regressionBF</code>. If you want to mix metric and categorical predictors, as in an ANCOVA model, you will have to use the <code>generalTestBF</code> function. All functions discussed so far are really just convenience interfaces to the <code>generalTestBF</code>, which implements Bayes factors for the General Linear Model. These convenience functions are used to determine an appropriate scaling factor for the different terms in the model, but not much else of concern, so you can replicate all the previous analyses through the <code>generalTestBF</code>function, if you’d like.</p>
<!--
## Estimating Bayesian models with the `brms` package
-->

<div id="refs" class="references">
<div>
<p>Bates, Douglas, Martin Maechler, Ben Bolker, and Steven Walker. 2020. <em>Lme4: Linear Mixed-Effects Models Using Eigen and S4</em>. <a href="https://github.com/lme4/lme4/">https://github.com/lme4/lme4/</a>.</p>
</div>
<div>
<p>Fox, John, Sanford Weisberg, and Brad Price. 2020. <em>Car: Companion to Applied Regression</em>. <a href="https://CRAN.R-project.org/package=car">https://CRAN.R-project.org/package=car</a>.</p>
</div>
<div>
<p>Højsgaard, Ulrich Halekoh Søren. 2020. <em>Pbkrtest: Parametric Bootstrap and Kenward Roger Based Methods for Mixed Model Comparison</em>. <a href="http://people.math.aau.dk/~sorenh/software/pbkrtest/">http://people.math.aau.dk/~sorenh/software/pbkrtest/</a>.</p>
</div>
<div>
<p>Kuznetsova, Alexandra, Per Bruun Brockhoff, and Rune Haubo Bojesen Christensen. 2020. <em>LmerTest: Tests in Linear Mixed Effects Models</em>. <a href="https://github.com/runehaubo/lmerTestR">https://github.com/runehaubo/lmerTestR</a>.</p>
</div>
<div>
<p>Lenth, Russell. 2020. <em>Emmeans: Estimated Marginal Means, Aka Least-Squares Means</em>. <a href="https://github.com/rvlenth/emmeans">https://github.com/rvlenth/emmeans</a>.</p>
</div>
<div>
<p>Morey, Richard D., and Jeffrey N. Rouder. 2018. <em>BayesFactor: Computation of Bayes Factors for Common Designs</em>. <a href="https://richarddmorey.github.io/BayesFactor/">https://richarddmorey.github.io/BayesFactor/</a>.</p>
</div>
<div>
<p>Rouder, Jeffrey N, Paul L Speckman, Dongchu Sun, Richard D Morey, and Geoffrey Iverson. 2009. “Bayesian T Tests for Accepting and Rejecting the Null Hypothesis.” <em>Psychonomic Bulletin &amp; Review</em> 16 (2): 225–37.</p>
</div>
<div>
<p>Schloerke, Barret, Di Cook, Joseph Larmarange, Francois Briatte, Moritz Marbach, Edwin Thoen, Amos Elberg, and Jason Crowley. 2020. <em>GGally: Extension to Ggplot2</em>. <a href="https://CRAN.R-project.org/package=GGally">https://CRAN.R-project.org/package=GGally</a>.</p>
</div>
<div>
<p>Singmann, Henrik, Ben Bolker, Jake Westfall, Frederik Aust, and Mattan S. Ben-Shachar. 2020. <em>Afex: Analysis of Factorial Experiments</em>. <a href="https://CRAN.R-project.org/package=afex">https://CRAN.R-project.org/package=afex</a>.</p>
</div>
<div>
<p>Singmann, Henrik, and David Kellen. 2019. “An Introduction to Linear Mixed Modeling in Experimental Psychology.” In <em>New Methods in Cognitive Psychology</em>, 4–31. Psychology Press. <a href="http://singmann.org/download/publications/singmann_kellen-introduction-mixed-models.pdf,%20preprint">http://singmann.org/download/publications/singmann_kellen-introduction-mixed-models.pdf, preprint</a>.</p>
</div>
<div>
<p>Tingley, Dustin, Teppei Yamamoto, Kentaro Hirose, Luke Keele, Kosuke Imai, Minh Trinh, and Weihuang Wong. 2019. <em>Mediation: Causal Mediation Analysis</em>. <a href="https://imai.princeton.edu/projects/mechanisms.html">https://imai.princeton.edu/projects/mechanisms.html</a>.</p>
</div>
<div>
<p>Venables, Bill. 2018. <em>CodingMatrices: Alternative Factor Coding Matrices for Linear Model Formulae</em>. <a href="https://CRAN.R-project.org/package=codingMatrices">https://CRAN.R-project.org/package=codingMatrices</a>.</p>
</div>
<div>
<p>Wickham, Hadley, Winston Chang, Lionel Henry, Thomas Lin Pedersen, Kohske Takahashi, Claus Wilke, Kara Woo, Hiroaki Yutani, and Dewey Dunnington. 2020. <em>Ggplot2: Create Elegant Data Visualisations Using the Grammar of Graphics</em>. <a href="https://CRAN.R-project.org/package=ggplot2">https://CRAN.R-project.org/package=ggplot2</a>.</p>
</div>
<div>
<p>Wright, S Paul. 1992. “Adjusted P-Values for Simultaneous Inference.” <em>Biometrics</em>, 1005–13.</p>
</div>
</div>
</div>
</div>
</div>








<h3>References</h3>
<div id="refs" class="references">
<div id="ref-R-BayesFactor">
<p>Morey, Richard D., and Jeffrey N. Rouder. 2018. <em>BayesFactor: Computation of Bayes Factors for Common Designs</em>. <a href="https://richarddmorey.github.io/BayesFactor/">https://richarddmorey.github.io/BayesFactor/</a>.</p>
</div>
<div id="ref-rouder2009bayesian">
<p>Rouder, Jeffrey N, Paul L Speckman, Dongchu Sun, Richard D Morey, and Geoffrey Iverson. 2009. “Bayesian T Tests for Accepting and Rejecting the Null Hypothesis.” <em>Psychonomic Bulletin &amp; Review</em> 16 (2): 225–37.</p>
</div>
</div>
<div class="footnotes">
<hr />
<ol start="3">
<li id="fn3"><p>Curiously, a scaling factor of <span class="math inline">\(r = \tfrac{1}{2}\)</span> in this case corresponds to a scaling factor of <span class="math inline">\(r = \tfrac{\sqrt{2}}{2}\)</span>, which is something I don’t immediately understand, and will require further investigation.<a href="bayesian-hypothesis-testing-through-bayes-factors.html#fnref3" class="footnote-back">↩︎</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="linear-mixed-effects-models.html" class="navigation navigation-prev navigation-unique" aria-label="Previous page"><i class="fa fa-angle-left"></i></a>

    </div>
  </div>
<script src="book_assets/gitbook-2.6.7/js/app.min.js"></script>
<script src="book_assets/gitbook-2.6.7/js/lunr.js"></script>
<script src="book_assets/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="book_assets/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="book_assets/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="book_assets/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="book_assets/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="book_assets/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="book_assets/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": null,
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "subsection"
},
"source": null,
"search": true
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
