<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 13 Bayesian hypothesis testing with Bayes Factors | An R companion to Statistics: data analysis and modelling</title>
  <meta name="description" content="A book about how to use R related to the book Statistics: Data analysis and modelling." />
  <meta name="generator" content="bookdown 0.36 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 13 Bayesian hypothesis testing with Bayes Factors | An R companion to Statistics: data analysis and modelling" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="A book about how to use R related to the book Statistics: Data analysis and modelling." />
  <meta name="github-repo" content="mspeekenbrink/sdam-book" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 13 Bayesian hypothesis testing with Bayes Factors | An R companion to Statistics: data analysis and modelling" />
  
  <meta name="twitter:description" content="A book about how to use R related to the book Statistics: Data analysis and modelling." />
  

<meta name="author" content="Maarten Speekenbrink" />


<meta name="date" content="2023-11-20" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="bayesian-estimation-with-brms.html"/>
<link rel="next" href="reproducible-reports-with-rmarkdown.html"/>
<script src="book_assets/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="book_assets/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="book_assets/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="book_assets/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="book_assets/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="book_assets/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="book_assets/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="book_assets/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="book_assets/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="book_assets/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="book_assets/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>
<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a>
<ul>
<li class="chapter" data-level="0.1" data-path="index.html"><a href="index.html#acknowledgements"><i class="fa fa-check"></i><b>0.1</b> Acknowledgements</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="introduction.html"><a href="introduction.html"><i class="fa fa-check"></i><b>1</b> Introduction</a>
<ul>
<li class="chapter" data-level="1.1" data-path="introduction.html"><a href="introduction.html#what-is-r"><i class="fa fa-check"></i><b>1.1</b> What is R?</a></li>
<li class="chapter" data-level="1.2" data-path="introduction.html"><a href="introduction.html#getting-started"><i class="fa fa-check"></i><b>1.2</b> Getting started</a>
<ul>
<li class="chapter" data-level="1.2.1" data-path="introduction.html"><a href="introduction.html#download-r"><i class="fa fa-check"></i><b>1.2.1</b> Download R</a></li>
<li class="chapter" data-level="1.2.2" data-path="introduction.html"><a href="introduction.html#download-r-studio"><i class="fa fa-check"></i><b>1.2.2</b> Download R Studio</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="introduction.html"><a href="introduction.html#working-with-rstudio"><i class="fa fa-check"></i><b>1.3</b> Working with RStudio</a></li>
<li class="chapter" data-level="1.4" data-path="introduction.html"><a href="introduction.html#installing-packages"><i class="fa fa-check"></i><b>1.4</b> Installing packages</a>
<ul>
<li class="chapter" data-level="1.4.1" data-path="introduction.html"><a href="introduction.html#installing-the-sdamr-package"><i class="fa fa-check"></i><b>1.4.1</b> Installing the <code>sdamr</code> package</a></li>
<li class="chapter" data-level="1.4.2" data-path="introduction.html"><a href="introduction.html#loading-packages"><i class="fa fa-check"></i><b>1.4.2</b> Loading packages</a></li>
</ul></li>
<li class="chapter" data-level="1.5" data-path="introduction.html"><a href="introduction.html#getting-help"><i class="fa fa-check"></i><b>1.5</b> Getting help</a></li>
<li class="chapter" data-level="1.6" data-path="introduction.html"><a href="introduction.html#first-steps-r-as-a-calculator"><i class="fa fa-check"></i><b>1.6</b> First steps: R as a calculator</a></li>
<li class="chapter" data-level="1.7" data-path="introduction.html"><a href="introduction.html#data"><i class="fa fa-check"></i><b>1.7</b> Data</a>
<ul>
<li class="chapter" data-level="1.7.1" data-path="introduction.html"><a href="introduction.html#data-types"><i class="fa fa-check"></i><b>1.7.1</b> Data types</a></li>
<li class="chapter" data-level="1.7.2" data-path="introduction.html"><a href="introduction.html#objects"><i class="fa fa-check"></i><b>1.7.2</b> Objects</a></li>
<li class="chapter" data-level="1.7.3" data-path="introduction.html"><a href="introduction.html#importing-data"><i class="fa fa-check"></i><b>1.7.3</b> Importing data</a></li>
</ul></li>
<li class="chapter" data-level="1.8" data-path="introduction.html"><a href="introduction.html#exploring-data-descriptive-statistics"><i class="fa fa-check"></i><b>1.8</b> Exploring data: Descriptive statistics</a></li>
<li class="chapter" data-level="1.9" data-path="introduction.html"><a href="introduction.html#exploring-data-creating-plots"><i class="fa fa-check"></i><b>1.9</b> Exploring data: Creating plots</a>
<ul>
<li class="chapter" data-level="1.9.1" data-path="introduction.html"><a href="introduction.html#histogram"><i class="fa fa-check"></i><b>1.9.1</b> Histogram</a></li>
<li class="chapter" data-level="1.9.2" data-path="introduction.html"><a href="introduction.html#boxplot"><i class="fa fa-check"></i><b>1.9.2</b> Boxplot</a></li>
<li class="chapter" data-level="1.9.3" data-path="introduction.html"><a href="introduction.html#scatterplot"><i class="fa fa-check"></i><b>1.9.3</b> Scatterplot</a></li>
<li class="chapter" data-level="1.9.4" data-path="introduction.html"><a href="introduction.html#raincloud-plot"><i class="fa fa-check"></i><b>1.9.4</b> Raincloud plot</a></li>
</ul></li>
<li class="chapter" data-level="1.10" data-path="introduction.html"><a href="introduction.html#a-note-about-namespaces-and-loading-packages"><i class="fa fa-check"></i><b>1.10</b> A note about namespaces and loading packages</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="statistical-modelling.html"><a href="statistical-modelling.html"><i class="fa fa-check"></i><b>2</b> Statistical modelling</a>
<ul>
<li class="chapter" data-level="2.1" data-path="statistical-modelling.html"><a href="statistical-modelling.html#distributions"><i class="fa fa-check"></i><b>2.1</b> Distributions</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="statistical-modelling.html"><a href="statistical-modelling.html#generating-random-data"><i class="fa fa-check"></i><b>2.1.1</b> Generating random data</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="statistical-modelling.html"><a href="statistical-modelling.html#estimation"><i class="fa fa-check"></i><b>2.2</b> Estimation</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="statistical-modelling.html"><a href="statistical-modelling.html#the-likelihood-function"><i class="fa fa-check"></i><b>2.2.1</b> The likelihood function</a></li>
<li class="chapter" data-level="2.2.2" data-path="statistical-modelling.html"><a href="statistical-modelling.html#calculating-the-likelihood-ratio"><i class="fa fa-check"></i><b>2.2.2</b> Calculating the likelihood ratio</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="statistical-modelling.html"><a href="statistical-modelling.html#hypothesis-testing-directly-with-the-binomial-distribution"><i class="fa fa-check"></i><b>2.3</b> Hypothesis testing directly with the binomial distribution</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="the-one-sample-t-test.html"><a href="the-one-sample-t-test.html"><i class="fa fa-check"></i><b>3</b> The one-sample t-test</a>
<ul>
<li class="chapter" data-level="3.1" data-path="the-one-sample-t-test.html"><a href="the-one-sample-t-test.html#missing-values"><i class="fa fa-check"></i><b>3.1</b> Missing values</a></li>
<li class="chapter" data-level="3.2" data-path="the-one-sample-t-test.html"><a href="the-one-sample-t-test.html#selecting-subsets-of-data"><i class="fa fa-check"></i><b>3.2</b> Selecting subsets of data</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="the-one-sample-t-test.html"><a href="the-one-sample-t-test.html#indexing-variables"><i class="fa fa-check"></i><b>3.2.1</b> Indexing variables</a></li>
<li class="chapter" data-level="3.2.2" data-path="the-one-sample-t-test.html"><a href="the-one-sample-t-test.html#the-subset-function"><i class="fa fa-check"></i><b>3.2.2</b> The <code>subset</code> function</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="the-one-sample-t-test.html"><a href="the-one-sample-t-test.html#one-sample-t-test"><i class="fa fa-check"></i><b>3.3</b> One-sample t-test</a></li>
<li class="chapter" data-level="3.4" data-path="the-one-sample-t-test.html"><a href="the-one-sample-t-test.html#effect-size"><i class="fa fa-check"></i><b>3.4</b> Effect size</a></li>
<li class="chapter" data-level="3.5" data-path="the-one-sample-t-test.html"><a href="the-one-sample-t-test.html#nonparametric-bootstrap"><i class="fa fa-check"></i><b>3.5</b> Nonparametric bootstrap</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="regression.html"><a href="regression.html"><i class="fa fa-check"></i><b>4</b> Regression</a>
<ul>
<li class="chapter" data-level="4.1" data-path="regression.html"><a href="regression.html#estimating-an-testing-a-simple-regression-model"><i class="fa fa-check"></i><b>4.1</b> Estimating an testing a simple regression model</a></li>
<li class="chapter" data-level="4.2" data-path="regression.html"><a href="regression.html#model-comparisons"><i class="fa fa-check"></i><b>4.2</b> Model comparisons</a></li>
<li class="chapter" data-level="4.3" data-path="regression.html"><a href="regression.html#estimating-and-testing-a-multiple-regression-model"><i class="fa fa-check"></i><b>4.3</b> Estimating and testing a multiple regression model</a></li>
<li class="chapter" data-level="4.4" data-path="regression.html"><a href="regression.html#residuals-and-predicted-values"><i class="fa fa-check"></i><b>4.4</b> Residuals and predicted values</a></li>
<li class="chapter" data-level="4.5" data-path="regression.html"><a href="regression.html#plotting-pairwise-scatterplots-for-many-variables"><i class="fa fa-check"></i><b>4.5</b> Plotting pairwise scatterplots for many variables</a></li>
<li class="chapter" data-level="4.6" data-path="regression.html"><a href="regression.html#multicollinearity-and-outlier-detection"><i class="fa fa-check"></i><b>4.6</b> Multicollinearity and outlier detection</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="moderation-and-mediation.html"><a href="moderation-and-mediation.html"><i class="fa fa-check"></i><b>5</b> Moderation and mediation</a>
<ul>
<li class="chapter" data-level="5.1" data-path="moderation-and-mediation.html"><a href="moderation-and-mediation.html#moderation-in-linear-models"><i class="fa fa-check"></i><b>5.1</b> Moderation in linear models</a>
<ul>
<li class="chapter" data-level="5.1.1" data-path="moderation-and-mediation.html"><a href="moderation-and-mediation.html#a-reminder-about-namespaces"><i class="fa fa-check"></i><b>5.1.1</b> A reminder about namespaces</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="moderation-and-mediation.html"><a href="moderation-and-mediation.html#centering"><i class="fa fa-check"></i><b>5.2</b> Centering</a></li>
<li class="chapter" data-level="5.3" data-path="moderation-and-mediation.html"><a href="moderation-and-mediation.html#mediation-analysis"><i class="fa fa-check"></i><b>5.3</b> Mediation analysis</a>
<ul>
<li class="chapter" data-level="5.3.1" data-path="moderation-and-mediation.html"><a href="moderation-and-mediation.html#causal-steps"><i class="fa fa-check"></i><b>5.3.1</b> Causal steps</a></li>
<li class="chapter" data-level="5.3.2" data-path="moderation-and-mediation.html"><a href="moderation-and-mediation.html#investigating-the-mediated-indirect-effect-with-a-bootstrap-test"><i class="fa fa-check"></i><b>5.3.2</b> Investigating the mediated (indirect) effect with a bootstrap test</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="contrast-coding-and-oneway-anova.html"><a href="contrast-coding-and-oneway-anova.html"><i class="fa fa-check"></i><b>6</b> Contrast coding and oneway ANOVA</a>
<ul>
<li class="chapter" data-level="6.1" data-path="contrast-coding-and-oneway-anova.html"><a href="contrast-coding-and-oneway-anova.html#computing-contrast-coded-predictors"><i class="fa fa-check"></i><b>6.1</b> Computing contrast-coded predictors</a></li>
<li class="chapter" data-level="6.2" data-path="contrast-coding-and-oneway-anova.html"><a href="contrast-coding-and-oneway-anova.html#assigning-contrasts-to-factors"><i class="fa fa-check"></i><b>6.2</b> Assigning contrasts to factors</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="contrast-coding-and-oneway-anova.html"><a href="contrast-coding-and-oneway-anova.html#default-coding-schemes"><i class="fa fa-check"></i><b>6.2.1</b> Default coding schemes</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="factorial-anova.html"><a href="factorial-anova.html"><i class="fa fa-check"></i><b>7</b> Factorial ANOVA</a>
<ul>
<li class="chapter" data-level="7.1" data-path="factorial-anova.html"><a href="factorial-anova.html#rainclouds-for-factorial-designs"><i class="fa fa-check"></i><b>7.1</b> Rainclouds for factorial designs</a></li>
<li class="chapter" data-level="7.2" data-path="factorial-anova.html"><a href="factorial-anova.html#formulating-estimating-and-testing-a-factorial-anova"><i class="fa fa-check"></i><b>7.2</b> Formulating, estimating, and testing a factorial ANOVA</a>
<ul>
<li class="chapter" data-level="7.2.1" data-path="factorial-anova.html"><a href="factorial-anova.html#a-threeway-anova"><i class="fa fa-check"></i><b>7.2.1</b> A threeway ANOVA</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="factorial-anova.html"><a href="factorial-anova.html#type-1-2-and-3-sums-of-squares"><i class="fa fa-check"></i><b>7.3</b> Type 1, 2, and 3 Sums of Squares</a></li>
<li class="chapter" data-level="7.4" data-path="factorial-anova.html"><a href="factorial-anova.html#planned-comparisons-and-post-hoc-tests-with-emmeans"><i class="fa fa-check"></i><b>7.4</b> Planned comparisons and post-hoc tests with <code>emmeans</code></a>
<ul>
<li class="chapter" data-level="7.4.1" data-path="factorial-anova.html"><a href="factorial-anova.html#adjusted-p-values"><i class="fa fa-check"></i><b>7.4.1</b> Adjusted p-values</a></li>
</ul></li>
<li class="chapter" data-level="7.5" data-path="factorial-anova.html"><a href="factorial-anova.html#testing-general-contrasts-with-emmeans"><i class="fa fa-check"></i><b>7.5</b> Testing general contrasts with <code>emmeans</code></a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="repeated-measures-anova.html"><a href="repeated-measures-anova.html"><i class="fa fa-check"></i><b>8</b> Repeated-measures ANOVA</a>
<ul>
<li class="chapter" data-level="8.1" data-path="repeated-measures-anova.html"><a href="repeated-measures-anova.html#long-and-wide-data"><i class="fa fa-check"></i><b>8.1</b> Long and wide data</a></li>
<li class="chapter" data-level="8.2" data-path="repeated-measures-anova.html"><a href="repeated-measures-anova.html#repeated-measures-anova-with-separate-glms"><i class="fa fa-check"></i><b>8.2</b> Repeated-measures ANOVA with separate GLMs</a>
<ul>
<li class="chapter" data-level="8.2.1" data-path="repeated-measures-anova.html"><a href="repeated-measures-anova.html#computing-within-subjects-composite-scores"><i class="fa fa-check"></i><b>8.2.1</b> Computing within-subjects composite scores</a></li>
<li class="chapter" data-level="8.2.2" data-path="repeated-measures-anova.html"><a href="repeated-measures-anova.html#performing-a-repeated-measures-anova-with-separate-models"><i class="fa fa-check"></i><b>8.2.2</b> Performing a repeated-measures ANOVA with separate models</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="repeated-measures-anova.html"><a href="repeated-measures-anova.html#repeated-measures-anova-with-the-car-package"><i class="fa fa-check"></i><b>8.3</b> Repeated-measures ANOVA with the <code>car</code> package</a></li>
<li class="chapter" data-level="8.4" data-path="repeated-measures-anova.html"><a href="repeated-measures-anova.html#repeated-measures-anova-with-the-afex-package"><i class="fa fa-check"></i><b>8.4</b> Repeated-measures ANOVA with the <code>afex</code> package</a></li>
<li class="chapter" data-level="8.5" data-path="repeated-measures-anova.html"><a href="repeated-measures-anova.html#contrasts-with-the-emmeans-package"><i class="fa fa-check"></i><b>8.5</b> Contrasts with the <code>emmeans</code> package</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="linear-mixed-effects-models.html"><a href="linear-mixed-effects-models.html"><i class="fa fa-check"></i><b>9</b> Linear mixed-effects models</a>
<ul>
<li class="chapter" data-level="9.1" data-path="linear-mixed-effects-models.html"><a href="linear-mixed-effects-models.html#formulating-and-estimating-linear-mixed-effects-models-with-lme4"><i class="fa fa-check"></i><b>9.1</b> Formulating and estimating linear mixed-effects models with <code>lme4</code></a>
<ul>
<li class="chapter" data-level="9.1.1" data-path="linear-mixed-effects-models.html"><a href="linear-mixed-effects-models.html#random-intercepts-model"><i class="fa fa-check"></i><b>9.1.1</b> Random intercepts model</a></li>
<li class="chapter" data-level="9.1.2" data-path="linear-mixed-effects-models.html"><a href="linear-mixed-effects-models.html#visually-assessing-model-assumptions"><i class="fa fa-check"></i><b>9.1.2</b> Visually assessing model assumptions</a></li>
<li class="chapter" data-level="9.1.3" data-path="linear-mixed-effects-models.html"><a href="linear-mixed-effects-models.html#random-intercepts-and-slopes"><i class="fa fa-check"></i><b>9.1.3</b> Random intercepts and slopes</a></li>
<li class="chapter" data-level="9.1.4" data-path="linear-mixed-effects-models.html"><a href="linear-mixed-effects-models.html#likelihood-ratio-test-with-the-anova-function"><i class="fa fa-check"></i><b>9.1.4</b> Likelihood ratio test with the <code>anova</code> function</a></li>
<li class="chapter" data-level="9.1.5" data-path="linear-mixed-effects-models.html"><a href="linear-mixed-effects-models.html#confidence-intervals"><i class="fa fa-check"></i><b>9.1.5</b> Confidence intervals</a></li>
<li class="chapter" data-level="9.1.6" data-path="linear-mixed-effects-models.html"><a href="linear-mixed-effects-models.html#plotting-model-predictions"><i class="fa fa-check"></i><b>9.1.6</b> Plotting model predictions</a></li>
</ul></li>
<li class="chapter" data-level="9.2" data-path="linear-mixed-effects-models.html"><a href="linear-mixed-effects-models.html#obtaining-p-values-with-afexmixed"><i class="fa fa-check"></i><b>9.2</b> Obtaining p-values with <code>afex::mixed</code></a></li>
<li class="chapter" data-level="9.3" data-path="linear-mixed-effects-models.html"><a href="linear-mixed-effects-models.html#crossed-random-effects"><i class="fa fa-check"></i><b>9.3</b> Crossed random effects</a></li>
<li class="chapter" data-level="9.4" data-path="linear-mixed-effects-models.html"><a href="linear-mixed-effects-models.html#automatically-finding-optimal-random-effects-structures-with-the-buildmer-package"><i class="fa fa-check"></i><b>9.4</b> Automatically finding optimal random effects structures with the <code>buildmer</code> package</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html"><i class="fa fa-check"></i><b>10</b> Generalized linear models</a>
<ul>
<li class="chapter" data-level="10.1" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html#model-estimation-and-inference"><i class="fa fa-check"></i><b>10.1</b> Model estimation and inference</a></li>
<li class="chapter" data-level="10.2" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html#confidence-intervals-1"><i class="fa fa-check"></i><b>10.2</b> Confidence intervals</a></li>
<li class="chapter" data-level="10.3" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html#model-predictions"><i class="fa fa-check"></i><b>10.3</b> Model predictions</a></li>
<li class="chapter" data-level="10.4" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html#alternative-link-functions-for-logistic-regression"><i class="fa fa-check"></i><b>10.4</b> Alternative link functions for logistic regression</a></li>
<li class="chapter" data-level="10.5" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html#poisson-regression"><i class="fa fa-check"></i><b>10.5</b> Poisson regression</a>
<ul>
<li class="chapter" data-level="10.5.1" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html#quasi-poisson-regression"><i class="fa fa-check"></i><b>10.5.1</b> Quasi-Poisson regression</a></li>
</ul></li>
<li class="chapter" data-level="10.6" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html#log-linear-models"><i class="fa fa-check"></i><b>10.6</b> Log-linear models</a></li>
<li class="chapter" data-level="10.7" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html#multinomial-regression"><i class="fa fa-check"></i><b>10.7</b> Multinomial regression</a></li>
<li class="chapter" data-level="10.8" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html#generalized-linear-mixed-effects-models"><i class="fa fa-check"></i><b>10.8</b> Generalized linear mixed effects models</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="structural-equation-modelling-with-lavaan.html"><a href="structural-equation-modelling-with-lavaan.html"><i class="fa fa-check"></i><b>11</b> Structural Equation modelling with lavaan</a>
<ul>
<li class="chapter" data-level="11.1" data-path="structural-equation-modelling-with-lavaan.html"><a href="structural-equation-modelling-with-lavaan.html#lavaan"><i class="fa fa-check"></i><b>11.1</b> Lavaan</a>
<ul>
<li class="chapter" data-level="11.1.1" data-path="structural-equation-modelling-with-lavaan.html"><a href="structural-equation-modelling-with-lavaan.html#the-lavaan-model-syntax"><i class="fa fa-check"></i><b>11.1.1</b> The lavaan model syntax</a></li>
<li class="chapter" data-level="11.1.2" data-path="structural-equation-modelling-with-lavaan.html"><a href="structural-equation-modelling-with-lavaan.html#model-estimation"><i class="fa fa-check"></i><b>11.1.2</b> Model estimation</a></li>
<li class="chapter" data-level="11.1.3" data-path="structural-equation-modelling-with-lavaan.html"><a href="structural-equation-modelling-with-lavaan.html#extracting-results"><i class="fa fa-check"></i><b>11.1.3</b> Extracting results</a></li>
</ul></li>
<li class="chapter" data-level="11.2" data-path="structural-equation-modelling-with-lavaan.html"><a href="structural-equation-modelling-with-lavaan.html#plotting-sem-models-with-the-semplot-package"><i class="fa fa-check"></i><b>11.2</b> Plotting SEM models with the <code>semPlot</code> package</a></li>
<li class="chapter" data-level="11.3" data-path="structural-equation-modelling-with-lavaan.html"><a href="structural-equation-modelling-with-lavaan.html#path-models"><i class="fa fa-check"></i><b>11.3</b> Path models</a>
<ul>
<li class="chapter" data-level="11.3.1" data-path="structural-equation-modelling-with-lavaan.html"><a href="structural-equation-modelling-with-lavaan.html#regression-models"><i class="fa fa-check"></i><b>11.3.1</b> Regression models</a></li>
<li class="chapter" data-level="11.3.2" data-path="structural-equation-modelling-with-lavaan.html"><a href="structural-equation-modelling-with-lavaan.html#mediation-models"><i class="fa fa-check"></i><b>11.3.2</b> Mediation models</a></li>
<li class="chapter" data-level="11.3.3" data-path="structural-equation-modelling-with-lavaan.html"><a href="structural-equation-modelling-with-lavaan.html#a-more-complex-path-model"><i class="fa fa-check"></i><b>11.3.3</b> A more complex path model</a></li>
</ul></li>
<li class="chapter" data-level="11.4" data-path="structural-equation-modelling-with-lavaan.html"><a href="structural-equation-modelling-with-lavaan.html#modification-indices"><i class="fa fa-check"></i><b>11.4</b> Modification indices</a></li>
<li class="chapter" data-level="11.5" data-path="structural-equation-modelling-with-lavaan.html"><a href="structural-equation-modelling-with-lavaan.html#confirmatory-factor-analysis"><i class="fa fa-check"></i><b>11.5</b> Confirmatory factor analysis</a></li>
<li class="chapter" data-level="11.6" data-path="structural-equation-modelling-with-lavaan.html"><a href="structural-equation-modelling-with-lavaan.html#general-sem-models"><i class="fa fa-check"></i><b>11.6</b> General SEM models</a></li>
<li class="chapter" data-level="11.7" data-path="structural-equation-modelling-with-lavaan.html"><a href="structural-equation-modelling-with-lavaan.html#exploratory-factor-analysis-with-the-psych-package"><i class="fa fa-check"></i><b>11.7</b> Exploratory factor analysis with the <code>psych</code> package</a>
<ul>
<li class="chapter" data-level="11.7.1" data-path="structural-equation-modelling-with-lavaan.html"><a href="structural-equation-modelling-with-lavaan.html#determining-the-number-of-factors-with-parallel-analysis"><i class="fa fa-check"></i><b>11.7.1</b> Determining the number of factors with Parallel Analysis</a></li>
<li class="chapter" data-level="11.7.2" data-path="structural-equation-modelling-with-lavaan.html"><a href="structural-equation-modelling-with-lavaan.html#estimating-and-rotating-efa-solutions"><i class="fa fa-check"></i><b>11.7.2</b> Estimating and rotating EFA solutions</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="12" data-path="bayesian-estimation-with-brms.html"><a href="bayesian-estimation-with-brms.html"><i class="fa fa-check"></i><b>12</b> Bayesian estimation with brms</a>
<ul>
<li class="chapter" data-level="12.1" data-path="bayesian-estimation-with-brms.html"><a href="bayesian-estimation-with-brms.html#the-brms-package"><i class="fa fa-check"></i><b>12.1</b> The brms package</a>
<ul>
<li class="chapter" data-level="12.1.1" data-path="bayesian-estimation-with-brms.html"><a href="bayesian-estimation-with-brms.html#model-definition"><i class="fa fa-check"></i><b>12.1.1</b> Model definition</a></li>
<li class="chapter" data-level="12.1.2" data-path="bayesian-estimation-with-brms.html"><a href="bayesian-estimation-with-brms.html#priors"><i class="fa fa-check"></i><b>12.1.2</b> Priors</a></li>
</ul></li>
<li class="chapter" data-level="12.2" data-path="bayesian-estimation-with-brms.html"><a href="bayesian-estimation-with-brms.html#useful-plots-for-mcmc-samples"><i class="fa fa-check"></i><b>12.2</b> Useful plots for MCMC samples</a></li>
<li class="chapter" data-level="12.3" data-path="bayesian-estimation-with-brms.html"><a href="bayesian-estimation-with-brms.html#an-example-of-a-poisson-mixed-effects-regression-model"><i class="fa fa-check"></i><b>12.3</b> An example of a Poisson mixed-effects regression model</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="bayesian-hypothesis-testing-with-bayes-factors.html"><a href="bayesian-hypothesis-testing-with-bayes-factors.html"><i class="fa fa-check"></i><b>13</b> Bayesian hypothesis testing with Bayes Factors</a>
<ul>
<li class="chapter" data-level="13.1" data-path="bayesian-hypothesis-testing-with-bayes-factors.html"><a href="bayesian-hypothesis-testing-with-bayes-factors.html#the-bayesfactor-package"><i class="fa fa-check"></i><b>13.1</b> The <code>BayesFactor</code> package</a>
<ul>
<li class="chapter" data-level="13.1.1" data-path="bayesian-hypothesis-testing-with-bayes-factors.html"><a href="bayesian-hypothesis-testing-with-bayes-factors.html#a-bayesian-one-sample-t-test"><i class="fa fa-check"></i><b>13.1.1</b> A Bayesian one-sample t-test</a></li>
<li class="chapter" data-level="13.1.2" data-path="bayesian-hypothesis-testing-with-bayes-factors.html"><a href="bayesian-hypothesis-testing-with-bayes-factors.html#a-bayesian-two-sample-t-test"><i class="fa fa-check"></i><b>13.1.2</b> A Bayesian two-sample t-test</a></li>
<li class="chapter" data-level="13.1.3" data-path="bayesian-hypothesis-testing-with-bayes-factors.html"><a href="bayesian-hypothesis-testing-with-bayes-factors.html#a-bayesian-anova"><i class="fa fa-check"></i><b>13.1.3</b> A Bayesian ANOVA</a></li>
<li class="chapter" data-level="13.1.4" data-path="bayesian-hypothesis-testing-with-bayes-factors.html"><a href="bayesian-hypothesis-testing-with-bayes-factors.html#bayesian-regression-and-ancova"><i class="fa fa-check"></i><b>13.1.4</b> Bayesian regression and ANCOVA</a></li>
<li class="chapter" data-level="13.1.5" data-path="bayesian-hypothesis-testing-with-bayes-factors.html"><a href="bayesian-hypothesis-testing-with-bayes-factors.html#bayesian-repeated-measures-anova"><i class="fa fa-check"></i><b>13.1.5</b> Bayesian repeated-measures ANOVA</a></li>
<li class="chapter" data-level="13.1.6" data-path="bayesian-hypothesis-testing-with-bayes-factors.html"><a href="bayesian-hypothesis-testing-with-bayes-factors.html#parameter-estimates"><i class="fa fa-check"></i><b>13.1.6</b> Parameter estimates</a></li>
<li class="chapter" data-level="13.1.7" data-path="bayesian-hypothesis-testing-with-bayes-factors.html"><a href="bayesian-hypothesis-testing-with-bayes-factors.html#highest-density-interval"><i class="fa fa-check"></i><b>13.1.7</b> Highest-density interval</a></li>
</ul></li>
<li class="chapter" data-level="13.2" data-path="bayesian-hypothesis-testing-with-bayes-factors.html"><a href="bayesian-hypothesis-testing-with-bayes-factors.html#bayes-factors-for-brms-models"><i class="fa fa-check"></i><b>13.2</b> Bayes Factors for <code>brms</code> models</a>
<ul>
<li class="chapter" data-level="13.2.1" data-path="bayesian-hypothesis-testing-with-bayes-factors.html"><a href="bayesian-hypothesis-testing-with-bayes-factors.html#testing-simple-point-and-directional-hypotheses-for-parameters-of-brms-models"><i class="fa fa-check"></i><b>13.2.1</b> Testing simple point and directional hypotheses for parameters of <code>brms</code> models</a></li>
<li class="chapter" data-level="13.2.2" data-path="bayesian-hypothesis-testing-with-bayes-factors.html"><a href="bayesian-hypothesis-testing-with-bayes-factors.html#using-bridge-sampling-to-obtain-marginal-likelihoods"><i class="fa fa-check"></i><b>13.2.2</b> Using bridge sampling to obtain marginal likelihoods</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="14" data-path="reproducible-reports-with-rmarkdown.html"><a href="reproducible-reports-with-rmarkdown.html"><i class="fa fa-check"></i><b>14</b> Reproducible reports with RMarkdown</a>
<ul>
<li class="chapter" data-level="14.1" data-path="reproducible-reports-with-rmarkdown.html"><a href="reproducible-reports-with-rmarkdown.html#yaml-headers"><i class="fa fa-check"></i><b>14.1</b> YAML headers</a></li>
<li class="chapter" data-level="14.2" data-path="reproducible-reports-with-rmarkdown.html"><a href="reproducible-reports-with-rmarkdown.html#markdown-syntax"><i class="fa fa-check"></i><b>14.2</b> Markdown syntax</a>
<ul>
<li class="chapter" data-level="14.2.1" data-path="reproducible-reports-with-rmarkdown.html"><a href="reproducible-reports-with-rmarkdown.html#inline-formatting"><i class="fa fa-check"></i><b>14.2.1</b> Inline formatting</a></li>
<li class="chapter" data-level="14.2.2" data-path="reproducible-reports-with-rmarkdown.html"><a href="reproducible-reports-with-rmarkdown.html#block-level-elements"><i class="fa fa-check"></i><b>14.2.2</b> Block-level elements</a></li>
<li class="chapter" data-level="14.2.3" data-path="reproducible-reports-with-rmarkdown.html"><a href="reproducible-reports-with-rmarkdown.html#math-expressions"><i class="fa fa-check"></i><b>14.2.3</b> Math expressions</a></li>
</ul></li>
<li class="chapter" data-level="14.3" data-path="reproducible-reports-with-rmarkdown.html"><a href="reproducible-reports-with-rmarkdown.html#r-code"><i class="fa fa-check"></i><b>14.3</b> R code chunks and inline R code</a>
<ul>
<li class="chapter" data-level="14.3.1" data-path="reproducible-reports-with-rmarkdown.html"><a href="reproducible-reports-with-rmarkdown.html#figures"><i class="fa fa-check"></i><b>14.3.1</b> Figures</a></li>
<li class="chapter" data-level="14.3.2" data-path="reproducible-reports-with-rmarkdown.html"><a href="reproducible-reports-with-rmarkdown.html#tables"><i class="fa fa-check"></i><b>14.3.2</b> Tables</a></li>
</ul></li>
<li class="chapter" data-level="14.4" data-path="reproducible-reports-with-rmarkdown.html"><a href="reproducible-reports-with-rmarkdown.html#apa-documents-with-papaja"><i class="fa fa-check"></i><b>14.4</b> APA documents with <code>papaja</code></a>
<ul>
<li class="chapter" data-level="14.4.1" data-path="reproducible-reports-with-rmarkdown.html"><a href="reproducible-reports-with-rmarkdown.html#installation"><i class="fa fa-check"></i><b>14.4.1</b> Installation</a></li>
<li class="chapter" data-level="14.4.2" data-path="reproducible-reports-with-rmarkdown.html"><a href="reproducible-reports-with-rmarkdown.html#how-to-use-papaja"><i class="fa fa-check"></i><b>14.4.2</b> How to use papaja</a></li>
<li class="chapter" data-level="14.4.3" data-path="reproducible-reports-with-rmarkdown.html"><a href="reproducible-reports-with-rmarkdown.html#getting-help-1"><i class="fa fa-check"></i><b>14.4.3</b> Getting help</a></li>
<li class="chapter" data-level="14.4.4" data-path="reproducible-reports-with-rmarkdown.html"><a href="reproducible-reports-with-rmarkdown.html#other-related-r-packages"><i class="fa fa-check"></i><b>14.4.4</b> Other related R packages</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">An R companion to Statistics: data analysis and modelling</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="bayesian-hypothesis-testing-with-bayes-factors" class="section level1 hasAnchor" number="13">
<h1><span class="header-section-number">Chapter 13</span> Bayesian hypothesis testing with Bayes Factors<a href="bayesian-hypothesis-testing-with-bayes-factors.html#bayesian-hypothesis-testing-with-bayes-factors" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>In this chapter, we will discuss how to compute Bayes Factors for a variety of General Linear Models using the <code>BayesFactor</code> package <span class="citation">(<a href="#ref-R-BayesFactor">Morey and Rouder 2023</a>)</span>. The package implements the “default” priors discussed in the SDAM book. <!-- More complex Bayesian models, such as mixed-effects and multilevel models, can be estimated with the `brms` package, and we will briefly touch upon this at the end of the chapter. --></p>
<div id="the-bayesfactor-package" class="section level2 hasAnchor" number="13.1">
<h2><span class="header-section-number">13.1</span> The <code>BayesFactor</code> package<a href="bayesian-hypothesis-testing-with-bayes-factors.html#the-bayesfactor-package" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The <code>BayesFactor</code> package implements Bayesian model comparisons for General Linear Models (as well as some other models for e.g. contingency tables and proportions) using JZS-priors for the parameters, or fixing those parameters to 0. Because Bayes Factors are <strong>transitive</strong>, in the sense that a ratio of Bayes Factors is itself another Bayes factor:
<span class="math display">\[\begin{align}
\text{BF}_{1,2} &amp;= \frac{p(Y_1,\ldots,Y_n|\text{MODEL 1})}{p(Y_1,\ldots,Y_n|\text{MODEL 2})} \\
&amp;= \frac{p(Y_1,\ldots,Y_n|\text{MODEL 1})/p(Y_1,\ldots,Y_n|\text{MODEL 0})} {p(Y_1,\ldots,Y_n|\text{MODEL 2})/p(Y_1,\ldots,Y_n|\text{MODEL 0})} \\
&amp;= \frac{\text{BF}_{1,0}}{\text{BF}_{2,0}} ,
\end{align}\]</span>
you can compute many other Bayes Factors which might not be immediately provided by the package, by simply dividing the Bayes factors that the package does provide. This makes the procedure of model comparison very flexible.</p>
<p>If you haven’t installed the <code>BayesFactor</code> package yet, you need to do so first. Then you can load it as usual by:</p>
<div class="sourceCode" id="cb727"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb727-1"><a href="bayesian-hypothesis-testing-with-bayes-factors.html#cb727-1" tabindex="-1"></a><span class="fu">library</span>(BayesFactor)</span></code></pre></div>
<div id="a-bayesian-one-sample-t-test" class="section level3 hasAnchor" number="13.1.1">
<h3><span class="header-section-number">13.1.1</span> A Bayesian one-sample t-test<a href="bayesian-hypothesis-testing-with-bayes-factors.html#a-bayesian-one-sample-t-test" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>A Bayesian alternative to a <span class="math inline">\(t\)</span>-test is provided via the <code>ttestBF</code> function. Similar to the base R <code>t.test</code> function of the <code>stats</code> package, this function allows computation of a Bayes factor for a one-sample t-test or a two-sample t-tests (as well as a paired t-test, which we haven’t covered in the course). Let’s re-analyse the data we considered before, concerning participants’ judgements of the height of Mount Everest. The one-sample t-test we computed before, comparing the judgements to an assumed mean of <span class="math inline">\(\mu = 8848\)</span>, was:</p>
<div class="sourceCode" id="cb728"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb728-1"><a href="bayesian-hypothesis-testing-with-bayes-factors.html#cb728-1" tabindex="-1"></a><span class="co"># load the data</span></span>
<span id="cb728-2"><a href="bayesian-hypothesis-testing-with-bayes-factors.html#cb728-2" tabindex="-1"></a><span class="fu">library</span>(sdamr)</span>
<span id="cb728-3"><a href="bayesian-hypothesis-testing-with-bayes-factors.html#cb728-3" tabindex="-1"></a><span class="fu">data</span>(<span class="st">&quot;anchoring&quot;</span>)</span>
<span id="cb728-4"><a href="bayesian-hypothesis-testing-with-bayes-factors.html#cb728-4" tabindex="-1"></a><span class="co"># select the subset we analysed in Chapter 3</span></span>
<span id="cb728-5"><a href="bayesian-hypothesis-testing-with-bayes-factors.html#cb728-5" tabindex="-1"></a>dat <span class="ot">&lt;-</span> <span class="fu">subset</span>(anchoring,(referrer <span class="sc">==</span> <span class="st">&quot;swps&quot;</span> <span class="sc">|</span> referrer <span class="sc">==</span> <span class="st">&quot;swpson&quot;</span>) <span class="sc">&amp;</span> anchor <span class="sc">==</span> <span class="st">&quot;low&quot;</span>)</span>
<span id="cb728-6"><a href="bayesian-hypothesis-testing-with-bayes-factors.html#cb728-6" tabindex="-1"></a><span class="co"># compute the Frequentist one-sample t-test</span></span>
<span id="cb728-7"><a href="bayesian-hypothesis-testing-with-bayes-factors.html#cb728-7" tabindex="-1"></a><span class="fu">t.test</span>(dat<span class="sc">$</span>everest_meters, <span class="at">mu=</span><span class="dv">8848</span>)</span></code></pre></div>
<pre><code>## 
##  One Sample t-test
## 
## data:  dat$everest_meters
## t = -8.4429, df = 108, p-value = 1.558e-13
## alternative hypothesis: true mean is not equal to 8848
## 95 percent confidence interval:
##  5716.848 6907.537
## sample estimates:
## mean of x 
##  6312.193</code></pre>
<p>The syntax for the Bayesian alternative is <em>very</em> similar, namely:</p>
<div class="sourceCode" id="cb730"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb730-1"><a href="bayesian-hypothesis-testing-with-bayes-factors.html#cb730-1" tabindex="-1"></a>bf_anchor <span class="ot">&lt;-</span> <span class="fu">ttestBF</span>(dat<span class="sc">$</span>everest_meters, <span class="at">mu=</span><span class="dv">8848</span>)</span></code></pre></div>
<p>This code provides a test of the following models:</p>
<p><span class="math display">\[\begin{align}
H_0\!&amp;: \mu = 8848 \\
H_1\!&amp;: \frac{\mu - 8848}{\sigma_\epsilon} \sim \textbf{Cauchy}(r)
\end{align}\]</span></p>
<p>After computing the Bayes factor and storing it in an object <code>bf_anchor</code>, we just see the print-out of the result by typing in the name of the object:</p>
<div class="sourceCode" id="cb731"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb731-1"><a href="bayesian-hypothesis-testing-with-bayes-factors.html#cb731-1" tabindex="-1"></a>bf_anchor</span></code></pre></div>
<pre><code>## Bayes factor analysis
## --------------
## [1] Alt., r=0.707 : 46902934288 ±0%
## 
## Against denominator:
##   Null, mu = 8848 
## ---
## Bayes factor type: BFoneSample, JZS</code></pre>
<p>This output is quite sparse, which is by no means a bad thing. It shows a few important things. Under <code>Alt.</code> (which stands for the alternative hypothesis), we first see the scaling factor <span class="math inline">\(r\)</span> used for the JZS prior distribution on the effect size. We then see the value of the Bayes Factor, which is “extreme” (&gt;100), showing that the data increases the posterior odds ratio for the alternative model over the null model by a factor of 46,902,934,288. Quite clearly, the average judgements differed from the true height of Mount Everest! After the computed value of the Bayes factor, you will find a proportional error for the estimate of the Bayes factor. In general, the marginal likelihoods that constitute the numerator (“top model”) and denominator (“bottom model”) of the Bayes factor cannot be computed exactly, and have to be approximated by numerical integration routines or simulation. This results in some (hopefully small) error in computation, and the error estimate indicates the extend to which the true Bayes factor might differ from the computed one. In this case, the error is (proportionally) very small, and hence we can be assured that our conclusion is unlikely to be affected by error in the approximation.</p>
<p>As we didn’t set the scaling factor explicitly, the default value is used, which is the “medium” scale <span class="math inline">\(r = \frac{\sqrt{2}}{2} = 0.707\)</span>. Note that this is actually different from the default value of <span class="math inline">\(r=1\)</span> proposed in <span class="citation">Rouder et al. (<a href="#ref-rouder2009bayesian">2009</a>)</span>, which first introduced this version of the Bayesian <span class="math inline">\(t\)</span>-test to a psychological audience, and the one used to illustrate the method in the SDAM book. Whilst reducing the default value to <span class="math inline">\(r=0.707\)</span> is probably reasonable given the effect sizes generally encountered in psychological studies, a change in the default prior highlights the subjective nature of the prior distribution in the Bayesian model comparison procedure. You should also realise that different analyses, such as t-tests, ANOVA, and regression models, use different default values for the scaling factor. As shown in the SDAM book, the value of the Bayes factor depends on the choice for the scaling factor. Although the default value may be deemed reasonable, the choice should really be based on a consideration of the magnitude of the effect sizes you (yes, you!) expect in a particular study. This is not always easy, but you should pick one (the default value, for instance, if you can’t think of a better one) <em>before</em> conducting the analysis. If you feel that makes the test too subjective, you may may want to check the robustness of the result for different choices of the scaling factor. You can do this by computing the Bayes factor for a range of choices of the scaling factor, and then inspecting whether the strength of the evidence is in line with your choice for a reasonable range of values around your choice. The code below provides an example of this:</p>
<div class="sourceCode" id="cb733"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb733-1"><a href="bayesian-hypothesis-testing-with-bayes-factors.html#cb733-1" tabindex="-1"></a><span class="co"># create a vector with different values for the scaling factor r</span></span>
<span id="cb733-2"><a href="bayesian-hypothesis-testing-with-bayes-factors.html#cb733-2" tabindex="-1"></a>rscale <span class="ot">&lt;-</span> <span class="fu">seq</span>(.<span class="dv">001</span>, <span class="dv">3</span>, <span class="at">length=</span><span class="dv">100</span>)</span>
<span id="cb733-3"><a href="bayesian-hypothesis-testing-with-bayes-factors.html#cb733-3" tabindex="-1"></a></span>
<span id="cb733-4"><a href="bayesian-hypothesis-testing-with-bayes-factors.html#cb733-4" tabindex="-1"></a><span class="co"># create an empty vector to store the resulting Bayes factors</span></span>
<span id="cb733-5"><a href="bayesian-hypothesis-testing-with-bayes-factors.html#cb733-5" tabindex="-1"></a>BFs <span class="ot">&lt;-</span> <span class="fu">vector</span>(<span class="st">&quot;double&quot;</span>, <span class="at">length=</span><span class="dv">100</span>)</span>
<span id="cb733-6"><a href="bayesian-hypothesis-testing-with-bayes-factors.html#cb733-6" tabindex="-1"></a></span>
<span id="cb733-7"><a href="bayesian-hypothesis-testing-with-bayes-factors.html#cb733-7" tabindex="-1"></a><span class="co"># compute the Bayes factor for each value of r</span></span>
<span id="cb733-8"><a href="bayesian-hypothesis-testing-with-bayes-factors.html#cb733-8" tabindex="-1"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">100</span>) {</span>
<span id="cb733-9"><a href="bayesian-hypothesis-testing-with-bayes-factors.html#cb733-9" tabindex="-1"></a>  temp_bf <span class="ot">&lt;-</span> <span class="fu">ttestBF</span>(dat<span class="sc">$</span>everest_meters, <span class="at">mu=</span><span class="dv">8848</span>, <span class="at">r =</span> rscale[i])</span>
<span id="cb733-10"><a href="bayesian-hypothesis-testing-with-bayes-factors.html#cb733-10" tabindex="-1"></a>  <span class="co"># the object returned by the ttestBF function is a so-called S4 object</span></span>
<span id="cb733-11"><a href="bayesian-hypothesis-testing-with-bayes-factors.html#cb733-11" tabindex="-1"></a>  <span class="co"># this has &quot;slots&quot; which can be accessed through the &quot;@&quot; operator.</span></span>
<span id="cb733-12"><a href="bayesian-hypothesis-testing-with-bayes-factors.html#cb733-12" tabindex="-1"></a>  <span class="co"># The actual value of the BF is extracted by @bayesFactor$bf</span></span>
<span id="cb733-13"><a href="bayesian-hypothesis-testing-with-bayes-factors.html#cb733-13" tabindex="-1"></a>  <span class="co"># which is stored in a logarithmic scale, so we need to use &quot;exp&quot;</span></span>
<span id="cb733-14"><a href="bayesian-hypothesis-testing-with-bayes-factors.html#cb733-14" tabindex="-1"></a>  <span class="co"># to obtain the value of the actual Bayes factor:</span></span>
<span id="cb733-15"><a href="bayesian-hypothesis-testing-with-bayes-factors.html#cb733-15" tabindex="-1"></a>  BFs[i] <span class="ot">&lt;-</span> <span class="fu">exp</span>(temp_bf<span class="sc">@</span>bayesFactor<span class="sc">$</span>bf)</span>
<span id="cb733-16"><a href="bayesian-hypothesis-testing-with-bayes-factors.html#cb733-16" tabindex="-1"></a>}</span>
<span id="cb733-17"><a href="bayesian-hypothesis-testing-with-bayes-factors.html#cb733-17" tabindex="-1"></a><span class="co"># use ggplot to plot the values of the Bayes factor against the choice of r</span></span>
<span id="cb733-18"><a href="bayesian-hypothesis-testing-with-bayes-factors.html#cb733-18" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb733-19"><a href="bayesian-hypothesis-testing-with-bayes-factors.html#cb733-19" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="fu">data.frame</span>(<span class="at">r=</span>rscale,<span class="at">BF=</span>BFs),<span class="fu">aes</span>(<span class="at">x=</span>r,<span class="at">y=</span>BF)) <span class="sc">+</span> <span class="fu">geom_line</span>()</span></code></pre></div>
<p><img src="13-Bayes-Factors_files/figure-html/unnamed-chunk-5-1.png" width="672" /></p>
<p>Given the scale of the <span class="math inline">\(y\)</span>-axis (e.g., the first tick mark is at <code>1e+10</code> = 10,000,000,000), there is overwhelming evidence against the null-hypothesis for most choices of the scaling factor. Hence, the results seem rather robust to the exact choice of prior.</p>
</div>
<div id="a-bayesian-two-sample-t-test" class="section level3 hasAnchor" number="13.1.2">
<h3><span class="header-section-number">13.1.2</span> A Bayesian two-sample t-test<a href="bayesian-hypothesis-testing-with-bayes-factors.html#a-bayesian-two-sample-t-test" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>To compare the means of two groups, we can revisit the Tetris study, where we considered whether the number of memory intrusions is reduced after playing Tetris in combination with memory reactivation, compared to just memory reactivation by itself. The <code>ttestBF</code> function allows us to provide the data for one group as the <code>x</code> argument, and the data for the other group as the <code>y</code> argument, so we can perform our model comparison, by subsetting the dependent variable appropriately, as follows:</p>
<div class="sourceCode" id="cb734"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb734-1"><a href="bayesian-hypothesis-testing-with-bayes-factors.html#cb734-1" tabindex="-1"></a><span class="fu">data</span>(<span class="st">&quot;tetris2015&quot;</span>, <span class="at">message=</span><span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>## Warning in data(&quot;tetris2015&quot;, message = FALSE): data set &#39;FALSE&#39; not found</code></pre>
<div class="sourceCode" id="cb736"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb736-1"><a href="bayesian-hypothesis-testing-with-bayes-factors.html#cb736-1" tabindex="-1"></a>bf_tetr <span class="ot">&lt;-</span> <span class="fu">ttestBF</span>(<span class="at">x=</span><span class="fu">subset</span>(tetris2015, Condition <span class="sc">==</span> <span class="st">&quot;Reactivation&quot;</span>)<span class="sc">$</span>Days_One_to_Seven_Number_of_Intrusions, <span class="at">y =</span> <span class="fu">subset</span>(tetris2015, Condition <span class="sc">==</span> <span class="st">&quot;Tetris_Reactivation&quot;</span>)<span class="sc">$</span>Days_One_to_Seven_Number_of_Intrusions)</span>
<span id="cb736-2"><a href="bayesian-hypothesis-testing-with-bayes-factors.html#cb736-2" tabindex="-1"></a>bf_tetr</span></code></pre></div>
<pre><code>## Bayes factor analysis
## --------------
## [1] Alt., r=0.707 : 16.78482 ±0%
## 
## Against denominator:
##   Null, mu1-mu2 = 0 
## ---
## Bayes factor type: BFindepSample, JZS</code></pre>
<p>Which shows strong evidence for the alternative hypothesis over the null hypothesis that the means are identical (i.e. that the difference between the means is zero, <span class="math inline">\(\mu_1 - \mu_2 = 0\)</span>), as the alternative model is 2.82 times more likely than the null model, which sets the difference between the means to exactly <span class="math inline">\(\mu_1 - \mu_2 = 0\)</span>, rather than allowing different values of this difference through the prior distribution.</p>
<p>A two-sample t-test should really be identical to a two-group ANOVA model, as both concern the same General Linear Model (a model with a single contrast-coding predictor, with e.q. values of <span class="math inline">\(-\tfrac{1}{2}\)</span> and <span class="math inline">\(\tfrac{1}{2}\)</span>). Before fully discussing the way to perform an ANOVA-type analysis with the <code>BayesFactor</code> package, let’s just double-check this is indeed the case:</p>
<div class="sourceCode" id="cb738"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb738-1"><a href="bayesian-hypothesis-testing-with-bayes-factors.html#cb738-1" tabindex="-1"></a>dat <span class="ot">&lt;-</span> <span class="fu">subset</span>(tetris2015, Condition <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">&quot;Tetris_Reactivation&quot;</span>,<span class="st">&quot;Reactivation&quot;</span>))</span>
<span id="cb738-2"><a href="bayesian-hypothesis-testing-with-bayes-factors.html#cb738-2" tabindex="-1"></a><span class="co"># remove levels of Condition that are no longer needed due to subsetting</span></span>
<span id="cb738-3"><a href="bayesian-hypothesis-testing-with-bayes-factors.html#cb738-3" tabindex="-1"></a>dat<span class="sc">$</span>Condition <span class="ot">&lt;-</span> <span class="fu">droplevels</span>(dat<span class="sc">$</span>Condition)</span>
<span id="cb738-4"><a href="bayesian-hypothesis-testing-with-bayes-factors.html#cb738-4" tabindex="-1"></a><span class="co"># use the anovaBF function</span></span>
<span id="cb738-5"><a href="bayesian-hypothesis-testing-with-bayes-factors.html#cb738-5" tabindex="-1"></a>bf2_tetr <span class="ot">&lt;-</span> <span class="fu">anovaBF</span>(Days_One_to_Seven_Number_of_Intrusions <span class="sc">~</span> Condition, <span class="at">data =</span> dat)</span>
<span id="cb738-6"><a href="bayesian-hypothesis-testing-with-bayes-factors.html#cb738-6" tabindex="-1"></a>bf2_tetr</span></code></pre></div>
<pre><code>## Bayes factor analysis
## --------------
## [1] Condition : 16.78482 ±0%
## 
## Against denominator:
##   Intercept only 
## ---
## Bayes factor type: BFlinearModel, JZS</code></pre>
<p>The results are indeed identical. Note that this is because both the <code>ttestBF</code> and <code>anovaBF</code> function use the same prior distribution for the effect.</p>
</div>
<div id="a-bayesian-anova" class="section level3 hasAnchor" number="13.1.3">
<h3><span class="header-section-number">13.1.3</span> A Bayesian ANOVA<a href="bayesian-hypothesis-testing-with-bayes-factors.html#a-bayesian-anova" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>More general ANOVA-type models can be tested though the <code>anovaBF</code> function. This function takes the following important arguments:</p>
<ul>
<li><code>formula</code>: a formula like in the <code>lm</code> function, specifying which factors to include as well as their interactions (by e.g. using an <code>*</code> operator to specify you want to include the main effects as well as their interactions. Note that unlike in the <code>lm</code> function, <strong>all terms must be factors</strong>.</li>
<li><code>data</code>: a <code>data.frame</code> containing data for all factors in the formula.</li>
<li><code>whichRandom</code>: a character vector specifying which factors are random. Random factors can be used to obtain a model similar to a repeated-measures ANOVA, or a (restricted) set of linear-mixed effects models (with only factors for the fixed effects).</li>
<li><code>whichModels</code>: a character vector specifying which models to compare. The allowed values are <code>"all"</code>, <code>"withmain"</code> (the default), <code>"top"</code>, and <code>"bottom"</code>. Setting <code>whichModels</code> to <code>"all"</code> will test all models that can be created by including or not including a main effect or interaction. <code>"top"</code> will test all models that can be created by removing or leaving in a main effect or interaction term from the full model. <code>"bottom"</code> creates models by adding single factors or interactions to the null model. <code>"withmain"</code> will test all models, with the constraint that if an interaction is included, the corresponding main effects are also included. Setting the argument to <code>top</code> produces model comparisons similar to the Type 3 procedure, comparing the full model to a restricted model with each effect removed. Setting the argument to <code>withMain</code> produces model comparisons similar to the Type 2 procedure, with model comparisons that respect the “principle of marginality”, such that tests of the main effects do not consider higher-order interactions, whilst a test of any interaction includes the main effects that constitute the elements in the interactions.</li>
<li><code>rscaleFixed</code>: prior scale for fixed effects. The value can be given numerically, or as one of three strings: <code>"medium"</code> (<span class="math inline">\(r = \tfrac{1}{2}\)</span>), <code>"wide"</code>: <span class="math inline">\(r = \tfrac{\sqrt{2}}{2}\)</span>, or <code>"ultrawide"</code> (<span class="math inline">\(r=1\)</span>). The default is “<code>medium"</code>.</li>
<li><code>rscaleRandom</code>: prior scale for random effects. Accepts the same strings as <code>rscaleFixed</code>, and in addition <code>"nuisance"</code> (<span class="math inline">\(r = 1\)</span>). The default is <code>"nuisance"</code>.</li>
<li><code>rscaleEffects</code>: a named vector with prior scales for individual factors.</li>
</ul>
<p>The <code>anovaBF</code> function will (as far as I can gather) <strong>always use <code>contr.sum()</code> contrasts for the factors</strong>. So setting your own contrasts will have no effect on the results. The exact contrast should not really matter for omnibus tests, and sum-to-zero are a reasonable choice in general (<code>contr.sum</code> implements what we called effect-coding before).<a href="#fn3" class="footnote-ref" id="fnref3"><sup>3</sup></a> While the <code>anovaBF</code> function always uses the JZS prior for any effects, it allows you to specify exactly which scaling factor to use for every effect, if so desired. One perhaps confusing thing is that effect-sizes for ANOVA designs (as far as I can gather) are based on standardized treatment-effects, whilst those for the t-test designs are based on Cohens-<span class="math inline">\(d\)</span> effect sizes. Hence, the values of the scaling factor <span class="math inline">\(r\)</span> for “medium”, “wide”, and “ultrawide” are different for the Bayesian <span class="math inline">\(t\)</span>-test and ANOVA models (whilst they provide the same results for models with two conditions).</p>
<p>Let’s see what happens when we use a Bayesian ANOVA-type analysis for the data on experimenter beliefs in social priming. First, let’s load the data, and turn the variables reflecting the experimental manipulations into factors:</p>
<div class="sourceCode" id="cb740"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb740-1"><a href="bayesian-hypothesis-testing-with-bayes-factors.html#cb740-1" tabindex="-1"></a><span class="fu">data</span>(<span class="st">&quot;expBelief&quot;</span>)</span>
<span id="cb740-2"><a href="bayesian-hypothesis-testing-with-bayes-factors.html#cb740-2" tabindex="-1"></a>dat <span class="ot">&lt;-</span> expBelief</span>
<span id="cb740-3"><a href="bayesian-hypothesis-testing-with-bayes-factors.html#cb740-3" tabindex="-1"></a>dat<span class="sc">$</span>primeCond <span class="ot">&lt;-</span> <span class="fu">factor</span>(dat<span class="sc">$</span>primeCond)</span>
<span id="cb740-4"><a href="bayesian-hypothesis-testing-with-bayes-factors.html#cb740-4" tabindex="-1"></a>dat<span class="sc">$</span>experimenterBelief <span class="ot">&lt;-</span> <span class="fu">factor</span>(dat<span class="sc">$</span>experimenterBelief)</span></code></pre></div>
<p>We can now use the <code>anovaBF</code> function to compute the Bayes factors:</p>
<div class="sourceCode" id="cb741"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb741-1"><a href="bayesian-hypothesis-testing-with-bayes-factors.html#cb741-1" tabindex="-1"></a><span class="co"># this uses a sampling based approach</span></span>
<span id="cb741-2"><a href="bayesian-hypothesis-testing-with-bayes-factors.html#cb741-2" tabindex="-1"></a><span class="co"># set the seed to make it reproducible</span></span>
<span id="cb741-3"><a href="bayesian-hypothesis-testing-with-bayes-factors.html#cb741-3" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">202111208</span>) </span>
<span id="cb741-4"><a href="bayesian-hypothesis-testing-with-bayes-factors.html#cb741-4" tabindex="-1"></a>bf_expB <span class="ot">&lt;-</span> <span class="fu">anovaBF</span>(ApproachAdvantage <span class="sc">~</span> primeCond<span class="sc">*</span>experimenterBelief, <span class="at">data =</span> dat)</span>
<span id="cb741-5"><a href="bayesian-hypothesis-testing-with-bayes-factors.html#cb741-5" tabindex="-1"></a>bf_expB</span></code></pre></div>
<pre><code>## Bayes factor analysis
## --------------
## [1] experimenterBelief                                            : 537.3879  ±0%
## [2] primeCond                                                     : 0.1282136 ±0.12%
## [3] experimenterBelief + primeCond                                : 69.86988  ±0.98%
## [4] experimenterBelief + primeCond + experimenterBelief:primeCond : 15.62005  ±5.59%
## 
## Against denominator:
##   Intercept only 
## ---
## Bayes factor type: BFlinearModel, JZS</code></pre>
<p>A main thing to note here is that the comparisons of different versions of MODEL G are against the same MODEL R, which is an intercept-only model. We can see that all models which include <code>experimenterBelief</code> receive strong evidence against the intercept-only model, apart from the model which only includes <code>primeCond</code>, which has less evidence than the intercept-only model. Although this indicates that the <code>primeCond</code> effect might be ignorable, the comparisons are different from comparing reduced models to the general MODEL G with all effects included. We can obtain these Type 3 comparisons by setting the <code>whichModels</code> argument to `top``:</p>
<div class="sourceCode" id="cb743"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb743-1"><a href="bayesian-hypothesis-testing-with-bayes-factors.html#cb743-1" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">202111208</span>) </span>
<span id="cb743-2"><a href="bayesian-hypothesis-testing-with-bayes-factors.html#cb743-2" tabindex="-1"></a>bf_expB2 <span class="ot">&lt;-</span> <span class="fu">anovaBF</span>(ApproachAdvantage <span class="sc">~</span> primeCond<span class="sc">*</span>experimenterBelief, <span class="at">data =</span> dat, <span class="at">whichModels =</span> <span class="st">&quot;top&quot;</span>)</span>
<span id="cb743-3"><a href="bayesian-hypothesis-testing-with-bayes-factors.html#cb743-3" tabindex="-1"></a>bf_expB2</span></code></pre></div>
<pre><code>## Bayes factor top-down analysis
## --------------
## When effect is omitted from experimenterBelief + primeCond + experimenterBelief:primeCond , BF is...
## [1] Omit experimenterBelief:primeCond : 4.703731   ±1.7%
## [2] Omit primeCond                    : 7.674953   ±2.19%
## [3] Omit experimenterBelief           : 0.00188326 ±1.79%
## 
## Against denominator:
##   ApproachAdvantage ~ experimenterBelief + primeCond + experimenterBelief:primeCond 
## ---
## Bayes factor type: BFlinearModel, JZS</code></pre>
<p>It is very important to realise that the output now concerns the comparison of the reduced model (in the numerator, i.e. the “top model”) against the full model (in the denominator, i.e. the “bottom model”), as is stated in the <code>Against denimonator</code> part of the output. So these are <span class="math inline">\(\text{BF}_{0,1}\)</span> values, rather than <span class="math inline">\(\text{BF}_{1,0}\)</span> values. That means that low values of the Bayes factor now indicate evidence for the alternative hypothesis that an effect is different from 0. As we find a very low <span class="math inline">\(\text{BF}_{0,1}\)</span> value for the <code>experimenterBelief</code> effect, this thus shows strong evidence that this effect is different than 0. The <span class="math inline">\(\text{BF}_{0,1}\)</span> values for the other effects are larger than 1, which indicate more support for the null hypothesis than for the alternative hypothesis.</p>
<p>We can change the output from a <span class="math inline">\(\text{BF}_{0,1}\)</span> value to a <span class="math inline">\(\text{BF}_{1,0}\)</span> value by simply inverting the Bayes factors, as follows:</p>
<div class="sourceCode" id="cb745"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb745-1"><a href="bayesian-hypothesis-testing-with-bayes-factors.html#cb745-1" tabindex="-1"></a><span class="dv">1</span><span class="sc">/</span>bf_expB2</span></code></pre></div>
<pre><code>##                                                                denominator
## numerator                                                       experimenterBelief + primeCond
##   experimenterBelief + primeCond + experimenterBelief:primeCond                      0.2125972
##                                                                denominator
## numerator                                                       experimenterBelief + experimenterBelief:primeCond
##   experimenterBelief + primeCond + experimenterBelief:primeCond                                          0.130294
##                                                                denominator
## numerator                                                       primeCond + experimenterBelief:primeCond
##   experimenterBelief + primeCond + experimenterBelief:primeCond                                  530.994</code></pre>
<p>As we noted before, we again see strong evidence for the effect of <code>experimenterBelief</code> when we remove it from the full model, but not for the other effects.</p>
<p>The transitivity of the Bayes factor means that we can also obtain some of these results through a ratio of the Bayes factors obtained earlier. For instance, a Type 3 test of the effect of <code>experimenterBelief:primeCond</code> interaction can be obtained by comparing a model with all effects included to a model without this interaction. In the analysis stored in <code>bf_expB</code>, we compared a number of the possible models to an intercept-only model. By comparing the Bayes factors of the model which excludes the interaction to a model which includes it, we can obtain the same Bayes factor of that interaction as follows. In the output of <code>bf_expB</code>, the fourth element compared the full model to the intercept-only model, whilst in the third element, a model with only the main effects of <code>experimenterBelief</code> and <code>primeCond</code> are compared to an intercept-only model. The Type 3 test of the interaction can then be obtained through the ratio of these two Bayes factors:</p>
<div class="sourceCode" id="cb747"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb747-1"><a href="bayesian-hypothesis-testing-with-bayes-factors.html#cb747-1" tabindex="-1"></a>bf_expB[<span class="dv">4</span>]<span class="sc">/</span>bf_expB[<span class="dv">3</span>]</span></code></pre></div>
<pre><code>## Bayes factor analysis
## --------------
## [1] experimenterBelief + primeCond + experimenterBelief:primeCond : 0.2235591 ±5.68%
## 
## Against denominator:
##   ApproachAdvantage ~ experimenterBelief + primeCond 
## ---
## Bayes factor type: BFlinearModel, JZS</code></pre>
<p>which indicates evidence for the null hypothesis that there is no moderation of the effect of <code>experimenterbelief</code> by <code>primeCond</code>, as the Bayes factor is well below 1. We cannot replicate all Type 3 analyses with the results obtained earlier, unless we ask the function to compare every possible model against the intercept-only model, by specifying <code>whichModels = "all"</code>:</p>
<div class="sourceCode" id="cb749"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb749-1"><a href="bayesian-hypothesis-testing-with-bayes-factors.html#cb749-1" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">202111208</span>) </span>
<span id="cb749-2"><a href="bayesian-hypothesis-testing-with-bayes-factors.html#cb749-2" tabindex="-1"></a>bf_expB3 <span class="ot">&lt;-</span> <span class="fu">anovaBF</span>(ApproachAdvantage <span class="sc">~</span> primeCond<span class="sc">*</span>experimenterBelief, <span class="at">data =</span> dat, <span class="at">whichModels =</span> <span class="st">&quot;all&quot;</span>)</span>
<span id="cb749-3"><a href="bayesian-hypothesis-testing-with-bayes-factors.html#cb749-3" tabindex="-1"></a>bf_expB3</span></code></pre></div>
<pre><code>## Bayes factor analysis
## --------------
## [1] experimenterBelief                                            : 537.3879   ±0%
## [2] primeCond                                                     : 0.1282136  ±0.12%
## [3] experimenterBelief:primeCond                                  : 0.1613884  ±0.1%
## [4] experimenterBelief + primeCond                                : 69.86988   ±0.98%
## [5] experimenterBelief + experimenterBelief:primeCond             : 114.0048   ±1.69%
## [6] primeCond + experimenterBelief:primeCond                      : 0.02797422 ±1.13%
## [7] experimenterBelief + primeCond + experimenterBelief:primeCond : 14.85414   ±1.38%
## 
## Against denominator:
##   Intercept only 
## ---
## Bayes factor type: BFlinearModel, JZS</code></pre>
<p>For instance, we can now obtain a Type 3 test for <code>experimenterBelief</code> by comparing the full model (the 7th element in the output) to a model which just excludes this effect (i.e. the 6th element):</p>
<div class="sourceCode" id="cb751"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb751-1"><a href="bayesian-hypothesis-testing-with-bayes-factors.html#cb751-1" tabindex="-1"></a>bf_expB3[<span class="dv">7</span>]<span class="sc">/</span>bf_expB3[<span class="dv">6</span>]</span></code></pre></div>
<pre><code>## Bayes factor analysis
## --------------
## [1] experimenterBelief + primeCond + experimenterBelief:primeCond : 530.994 ±1.79%
## 
## Against denominator:
##   ApproachAdvantage ~ primeCond + experimenterBelief:primeCond 
## ---
## Bayes factor type: BFlinearModel, JZS</code></pre>
<p>which reproduces mostly the result we obtained by setting <code>whichModel = "top"</code> before.</p>
</div>
<div id="bayesian-regression-and-ancova" class="section level3 hasAnchor" number="13.1.4">
<h3><span class="header-section-number">13.1.4</span> Bayesian regression and ANCOVA<a href="bayesian-hypothesis-testing-with-bayes-factors.html#bayesian-regression-and-ancova" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Apart from different default values of the scaling factor <span class="math inline">\(r\)</span> in the scaled-Cauchy distribution, the <code>BayesFactor</code> package works in the same way for models which include metric predictors. In a multiple regression model with only metric predictors, we can use the convenience function <code>regressionBF</code>. If you want to mix metric and categorical predictors, as in an ANCOVA model, you will have to use the <code>generalTestBF</code> function. All functions discussed so far are really just convenience interfaces to the <code>generalTestBF</code>, which implements Bayes factors for the General Linear Model. These convenience functions are used to determine an appropriate scaling factor for the different terms in the model, but not much else of concern, so you can replicate all the previous analyses through the <code>generalTestBF</code>function, if you’d like.</p>
</div>
<div id="bayesian-repeated-measures-anova" class="section level3 hasAnchor" number="13.1.5">
<h3><span class="header-section-number">13.1.5</span> Bayesian repeated-measures ANOVA<a href="bayesian-hypothesis-testing-with-bayes-factors.html#bayesian-repeated-measures-anova" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>An analysis similar to a repeated-measures ANOVA can also be obtained. Just like the <code>afex</code> package, the <code>BayesFactor</code> package requires data in the long format. Let’s first prepare the data of the Cheerleader-effect experiment:</p>
<div class="sourceCode" id="cb753"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb753-1"><a href="bayesian-hypothesis-testing-with-bayes-factors.html#cb753-1" tabindex="-1"></a><span class="fu">data</span>(<span class="st">&quot;cheerleader&quot;</span>)</span>
<span id="cb753-2"><a href="bayesian-hypothesis-testing-with-bayes-factors.html#cb753-2" tabindex="-1"></a>dat <span class="ot">&lt;-</span> cheerleader</span>
<span id="cb753-3"><a href="bayesian-hypothesis-testing-with-bayes-factors.html#cb753-3" tabindex="-1"></a><span class="co"># remove participants which should be excluded</span></span>
<span id="cb753-4"><a href="bayesian-hypothesis-testing-with-bayes-factors.html#cb753-4" tabindex="-1"></a>dat <span class="ot">&lt;-</span> <span class="fu">subset</span>(dat, Excluded <span class="sc">==</span> <span class="dv">0</span>)</span>
<span id="cb753-5"><a href="bayesian-hypothesis-testing-with-bayes-factors.html#cb753-5" tabindex="-1"></a><span class="co"># get rid of unused factor levels in Item by </span></span>
<span id="cb753-6"><a href="bayesian-hypothesis-testing-with-bayes-factors.html#cb753-6" tabindex="-1"></a>dat<span class="sc">$</span>Item <span class="ot">&lt;-</span> <span class="fu">factor</span>(dat<span class="sc">$</span>Item)</span>
<span id="cb753-7"><a href="bayesian-hypothesis-testing-with-bayes-factors.html#cb753-7" tabindex="-1"></a>dat<span class="sc">$</span>Presentation <span class="ot">&lt;-</span> forcats<span class="sc">::</span><span class="fu">fct_recode</span>(dat<span class="sc">$</span>Item, <span class="at">Different =</span> <span class="st">&quot;Control_Group&quot;</span>, <span class="at">Similar =</span> <span class="st">&quot;Distractor_Manipulation&quot;</span>)</span>
<span id="cb753-8"><a href="bayesian-hypothesis-testing-with-bayes-factors.html#cb753-8" tabindex="-1"></a>dat<span class="sc">$</span>Version <span class="ot">&lt;-</span> forcats<span class="sc">::</span><span class="fu">fct_recode</span>(dat<span class="sc">$</span>Task, <span class="at">Identical =</span> <span class="st">&quot;Identical-Distractors&quot;</span>, <span class="at">Variant =</span> <span class="st">&quot;Self-Distractors&quot;</span>)</span></code></pre></div>
<p>The way the <code>BayesFactor</code> package deals with repeated-measures designs is a little different
from how we treated repeated-measures ANOVA. Rather than computing within-subjects
composite variables, the package effectively deals with individual differences
by adding random intercepts (like in a linear mixed-effects model). To do this,
we add <code>Participant</code> as an additive effect, and then classify it as a random
effect through the <code>whichRandom</code> argument. To obtain Type-3 comparisons,
we again set <code>whichModels</code> to <code>top</code>:</p>
<div class="sourceCode" id="cb754"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb754-1"><a href="bayesian-hypothesis-testing-with-bayes-factors.html#cb754-1" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">202111208</span>) </span>
<span id="cb754-2"><a href="bayesian-hypothesis-testing-with-bayes-factors.html#cb754-2" tabindex="-1"></a>bf_rmanova <span class="ot">&lt;-</span> <span class="fu">anovaBF</span>(Response <span class="sc">~</span> Task<span class="sc">*</span>Item <span class="sc">+</span> Participant, <span class="at">whichRandom =</span> <span class="st">&quot;Participant&quot;</span>, <span class="at">data=</span>dat, <span class="at">whichModels =</span> <span class="st">&quot;top&quot;</span>)</span>
<span id="cb754-3"><a href="bayesian-hypothesis-testing-with-bayes-factors.html#cb754-3" tabindex="-1"></a>bf_rmanova</span></code></pre></div>
<pre><code>## Bayes factor top-down analysis
## --------------
## When effect is omitted from Task + Item + Task:Item + Participant , BF is...
## [1] Omit Item:Task : 1.340752     ±9.36%
## [2] Omit Item      : 7.465094e-06 ±9.62%
## [3] Omit Task      : 1.439629     ±7.75%
## 
## Against denominator:
##   Response ~ Task + Item + Task:Item + Participant 
## ---
## Bayes factor type: BFlinearModel, JZS</code></pre>
<p>In this case, the proportional errors of the results may be deemed to high. We
can get more precise results by obtaining more samples (for these complex models,
the estimation of the Bayes factor is done with a sampling-based approximation).
We can do this, without the need to respecify the model, with the <code>recompute</code>
function, where we can increase the number of sampling iterations from the default
(10,000 iterations) to something higher:</p>
<div class="sourceCode" id="cb756"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb756-1"><a href="bayesian-hypothesis-testing-with-bayes-factors.html#cb756-1" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1234</span>)</span>
<span id="cb756-2"><a href="bayesian-hypothesis-testing-with-bayes-factors.html#cb756-2" tabindex="-1"></a>bf_rmanova2 <span class="ot">&lt;-</span> <span class="fu">recompute</span>(bf_rmanova, <span class="at">iterations=</span><span class="dv">100000</span>)</span>
<span id="cb756-3"><a href="bayesian-hypothesis-testing-with-bayes-factors.html#cb756-3" tabindex="-1"></a>bf_rmanova2</span></code></pre></div>
<pre><code>## Bayes factor top-down analysis
## --------------
## When effect is omitted from Task + Item + Task:Item + Participant , BF is...
## [1] Omit Item:Task : 1.230971     ±2.77%
## [2] Omit Item      : 7.194855e-06 ±2.85%
## [3] Omit Task      : 1.364189     ±2.46%
## 
## Against denominator:
##   Response ~ Task + Item + Task:Item + Participant 
## ---
## Bayes factor type: BFlinearModel, JZS</code></pre>
<p>This provides somewhat better results, although it would be better to increase
the number of iterations even more.</p>
<p>As before, the Bayes Factors are for the reduced model compared to the full model
and we can get more easily interpretable results by computing the inverse value</p>
<div class="sourceCode" id="cb758"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb758-1"><a href="bayesian-hypothesis-testing-with-bayes-factors.html#cb758-1" tabindex="-1"></a><span class="dv">1</span><span class="sc">/</span>bf_rmanova2</span></code></pre></div>
<pre><code>##                                        denominator
## numerator                               Task + Item + Participant
##   Task + Item + Task:Item + Participant                  0.812367
##                                        denominator
## numerator                               Task + Task:Item + Participant
##   Task + Item + Task:Item + Participant                       138988.2
##                                        denominator
## numerator                               Item + Task:Item + Participant
##   Task + Item + Task:Item + Participant                      0.7330362</code></pre>
<p>We can see that we obtain “extreme” evidence for the main effect of Item. For the other effects, the evidence is more in favour of the null-hypothesis.</p>
</div>
<div id="parameter-estimates" class="section level3 hasAnchor" number="13.1.6">
<h3><span class="header-section-number">13.1.6</span> Parameter estimates<a href="bayesian-hypothesis-testing-with-bayes-factors.html#parameter-estimates" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>By default, the Bayes Factor objects just provide the values of the
Bayes Factor. We don’t get estimates of the parameters.</p>
<p>To get (approximate) posterior distributions for the parameters, we can
first estimate the general MODEL G with the <code>lmBF</code> function. This function
is meant to compute a specific General Linear Model (rather than a set of such
models). For example, for the Social Priming example, we can estimate the
ANOVA model with <code>lmBF</code> as:</p>
<div class="sourceCode" id="cb760"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb760-1"><a href="bayesian-hypothesis-testing-with-bayes-factors.html#cb760-1" tabindex="-1"></a>dat <span class="ot">&lt;-</span> expBelief</span>
<span id="cb760-2"><a href="bayesian-hypothesis-testing-with-bayes-factors.html#cb760-2" tabindex="-1"></a>dat<span class="sc">$</span>primeCond <span class="ot">&lt;-</span> <span class="fu">factor</span>(dat<span class="sc">$</span>primeCond)</span>
<span id="cb760-3"><a href="bayesian-hypothesis-testing-with-bayes-factors.html#cb760-3" tabindex="-1"></a>dat<span class="sc">$</span>experimenterBelief <span class="ot">&lt;-</span> <span class="fu">factor</span>(dat<span class="sc">$</span>experimenterBelief)</span>
<span id="cb760-4"><a href="bayesian-hypothesis-testing-with-bayes-factors.html#cb760-4" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">202111208</span>) </span>
<span id="cb760-5"><a href="bayesian-hypothesis-testing-with-bayes-factors.html#cb760-5" tabindex="-1"></a>bflm_expB <span class="ot">&lt;-</span> <span class="fu">lmBF</span>(ApproachAdvantage <span class="sc">~</span> primeCond<span class="sc">*</span>experimenterBelief, <span class="at">data =</span> dat)</span></code></pre></div>
<p>We can then use this estimated model to obtain samples from the posterior
distribution over the model parameters. This is done with the <code>posterior</code>
function of the <code>Bayesfactor</code> package. We can determine the number
of samples through the <code>iterations</code> argument. This should generally
be a high number, to get more reliable estimates:</p>
<div class="sourceCode" id="cb761"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb761-1"><a href="bayesian-hypothesis-testing-with-bayes-factors.html#cb761-1" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1234</span>)</span>
<span id="cb761-2"><a href="bayesian-hypothesis-testing-with-bayes-factors.html#cb761-2" tabindex="-1"></a>post_samples <span class="ot">&lt;-</span> <span class="fu">posterior</span>(bflm_expB, <span class="at">iterations=</span><span class="dv">100000</span>)</span></code></pre></div>
<p>The <code>post_samples</code> object can be effectively treated as a matrix, with columns
corresponding to the different parameters, and in the rows the samples. So
we can obtain posterior means as the column-wise averages:</p>
<div class="sourceCode" id="cb762"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb762-1"><a href="bayesian-hypothesis-testing-with-bayes-factors.html#cb762-1" tabindex="-1"></a><span class="fu">colMeans</span>(post_samples)</span></code></pre></div>
<pre><code>##                                   mu                        primeCond-HPP 
##                            21.440783                             5.836911 
##                        primeCond-LPP                 experimenterBelief-H 
##                            -5.836911                            43.978650 
##                 experimenterBelief-L primeCond:experimenterBelief-HPP.&amp;.H 
##                           -43.978650                             8.725977 
## primeCond:experimenterBelief-HPP.&amp;.L primeCond:experimenterBelief-LPP.&amp;.H 
##                            -8.725977                            -8.725977 
## primeCond:experimenterBelief-LPP.&amp;.L                                 sig2 
##                             8.725977                         45920.258584 
##                          g_primeCond                 g_experimenterBelief 
##                             1.928212                             2.384292 
##       g_primeCond:experimenterBelief 
##                             1.435865</code></pre>
<p>Here, <code>mu</code> corresponds to the “grand mean” (i.e. the average of averages),
which is is the intercept in a GLM with sum-to-zero contrasts. The
next mean corresponds to the posterior mean of the treatment effect of the
high-power prime condition (<code>primeCond-HPP</code>). I.e., this is the marginal mean
of the high-power prime conditions, compared to the grand mean. The second effect
is the posterior mean of the treatment effect of the low-power prime condition (<code>primeCond-LPP</code>). As
there are only two power-prime conditions, this is exactly the negative value
of the posterior mean of the high-power prime treatment effect (the grand mean
is exactly halfway between these two treatment effects). We get similar
treatment effects for the main effect of experimenter belief, and the
interaction between power prime and experimenter belief. The posterior
mean labelled <code>sig2</code> is an estimate of the error variance. The columns
after this are values related to the specification of the prior, which
we will ignore for now.</p>
<p>We can do more than compute means for these samples from the posterior
distribution. For instance, we can plot the (approximate) posterior
distributions as well. For example, we can plot the posterior distribution
of the high-power prime treatment effect as:</p>
<div class="sourceCode" id="cb764"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb764-1"><a href="bayesian-hypothesis-testing-with-bayes-factors.html#cb764-1" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="fu">data.frame</span>(<span class="at">x=</span><span class="fu">as.numeric</span>(post_samples[,<span class="fu">c</span>(<span class="st">&quot;primeCond-HPP&quot;</span>)])), <span class="fu">aes</span>(<span class="at">x=</span>x)) <span class="sc">+</span> <span class="fu">geom_density</span>()</span></code></pre></div>
<p><img src="13-Bayes-Factors_files/figure-html/unnamed-chunk-22-1.png" width="672" />
and for the experimenter-belief-high treatment effect as</p>
<div class="sourceCode" id="cb765"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb765-1"><a href="bayesian-hypothesis-testing-with-bayes-factors.html#cb765-1" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="fu">data.frame</span>(<span class="at">x=</span><span class="fu">as.numeric</span>(post_samples[,<span class="fu">c</span>(<span class="st">&quot;experimenterBelief-H&quot;</span>)])), <span class="fu">aes</span>(<span class="at">x=</span>x)) <span class="sc">+</span> <span class="fu">geom_density</span>()</span></code></pre></div>
<p><img src="13-Bayes-Factors_files/figure-html/unnamed-chunk-23-1.png" width="672" />
The first plot indicates that the posterior probability is quite high at the value of 0. In the second plot, the mass of the posterior distribution is clearly quite far removed from 0. This is in line with earlier results from the Bayes Factors, which showed little evidence for the main effect of power prime, but strong evidence for the effect of experimenter belief.</p>
</div>
<div id="highest-density-interval" class="section level3 hasAnchor" number="13.1.7">
<h3><span class="header-section-number">13.1.7</span> Highest-density interval<a href="bayesian-hypothesis-testing-with-bayes-factors.html#highest-density-interval" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>A convenient way to obtain highest-density intervals, is by using the <code>hdi</code> function from the <code>HDInterval</code> package <span class="citation">(<a href="#ref-R-HDInterval"><strong>R-HDInterval?</strong></a>)</span>. This function is defined for
a variety of objects, including those returned by the <code>BayesFactor::posterior()</code> function. The function has, in addition
to the object, one more argument called <code>credMass</code>, which specifies the
width of the credible interval (<code>credMass = .95</code> is the default). For example,
the 95% HDI interval for the two parameters that we plotted above are obtained as follows:</p>
<div class="sourceCode" id="cb766"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb766-1"><a href="bayesian-hypothesis-testing-with-bayes-factors.html#cb766-1" tabindex="-1"></a>HDInterval<span class="sc">::</span><span class="fu">hdi</span>(post_samples[,<span class="fu">c</span>(<span class="st">&quot;primeCond-HPP&quot;</span>)], <span class="at">credMass=</span><span class="fl">0.95</span>)</span></code></pre></div>
<pre><code>##            var1
## lower -14.74079
## upper  26.47933
## attr(,&quot;credMass&quot;)
## [1] 0.95</code></pre>
<div class="sourceCode" id="cb768"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb768-1"><a href="bayesian-hypothesis-testing-with-bayes-factors.html#cb768-1" tabindex="-1"></a><span class="co"># (don&#39;t have to specify credMass, as we want the default value)</span></span>
<span id="cb768-2"><a href="bayesian-hypothesis-testing-with-bayes-factors.html#cb768-2" tabindex="-1"></a>HDInterval<span class="sc">::</span><span class="fu">hdi</span>(post_samples[,<span class="fu">c</span>(<span class="st">&quot;experimenterBelief-H&quot;</span>)])</span></code></pre></div>
<pre><code>##           var1
## lower 23.57900
## upper 65.49569
## attr(,&quot;credMass&quot;)
## [1] 0.95</code></pre>
<p>The output shows the lower and upper bound for each HDI. We see that the 95% HDI for power prime effect includes 0, whilst the 95% HDI for the experimenter belief effect does not. Again, this corresponds to what we observed earlier, that there is strong evidence for the experimenter belief effect, but not for the power prime effect.</p>
<!--
## Estimating Bayesian models with the `brms` package
-->
</div>
</div>
<div id="bayes-factors-for-brms-models" class="section level2 hasAnchor" number="13.2">
<h2><span class="header-section-number">13.2</span> Bayes Factors for <code>brms</code> models<a href="bayesian-hypothesis-testing-with-bayes-factors.html#bayes-factors-for-brms-models" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The <code>BayesFactor</code> package computes Bayes Factors for a number of standard analyses, using the default priors set in the package. We may want to compute Bayes Factors to test hypotheses for more complex models. In general, we can compare any models by first computing the marginal likelihood for each model, and then computing the Bayes Factor as the ratio of these marginal likelihoods. Computing marginal likelihoods is not always straightforward, but a general procedure that often works reasonably well is called “bridge sampling” <span class="citation">(<a href="#ref-gronau2017tutorial">Quentin F. Gronau et al. 2017</a>)</span>, and has been implemented in the <code>bridgesampling</code> <span class="citation">(<a href="#ref-R-bridgesampling">Quentin F. Gronau and Singmann 2021</a>)</span> package. Before discussing how to use this, we will first discuss a simpler way to compute Bayes Factors for particular comparisons within the context of a <code>brms</code> model.</p>
<p>For the following examples, we will start with the multiple regression model for the <code>trump2016</code> data that we also estimated in the previous chapter, but now setting the prior distributions to more informative ones, as is advisable when computing Bayes Factors:</p>
<div class="sourceCode" id="cb770"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb770-1"><a href="bayesian-hypothesis-testing-with-bayes-factors.html#cb770-1" tabindex="-1"></a><span class="co"># load the data</span></span>
<span id="cb770-2"><a href="bayesian-hypothesis-testing-with-bayes-factors.html#cb770-2" tabindex="-1"></a><span class="fu">library</span>(brms)</span></code></pre></div>
<pre><code>## Loading required package: Rcpp</code></pre>
<pre><code>## Loading &#39;brms&#39; package (version 2.20.4). Useful instructions
## can be found by typing help(&#39;brms&#39;). A more detailed introduction
## to the package is available through vignette(&#39;brms_overview&#39;).</code></pre>
<pre><code>## 
## Attaching package: &#39;brms&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:stats&#39;:
## 
##     ar</code></pre>
<div class="sourceCode" id="cb775"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb775-1"><a href="bayesian-hypothesis-testing-with-bayes-factors.html#cb775-1" tabindex="-1"></a><span class="fu">data</span>(<span class="st">&quot;trump2016&quot;</span>, <span class="at">package=</span><span class="st">&quot;sdamr&quot;</span>)</span>
<span id="cb775-2"><a href="bayesian-hypothesis-testing-with-bayes-factors.html#cb775-2" tabindex="-1"></a>dat <span class="ot">&lt;-</span> <span class="fu">subset</span>(trump2016,state <span class="sc">!=</span> <span class="st">&quot;District of Columbia&quot;</span>)</span>
<span id="cb775-3"><a href="bayesian-hypothesis-testing-with-bayes-factors.html#cb775-3" tabindex="-1"></a></span>
<span id="cb775-4"><a href="bayesian-hypothesis-testing-with-bayes-factors.html#cb775-4" tabindex="-1"></a><span class="co"># define the prior distributions</span></span>
<span id="cb775-5"><a href="bayesian-hypothesis-testing-with-bayes-factors.html#cb775-5" tabindex="-1"></a>mod_priors <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="co"># intercept</span></span>
<span id="cb775-6"><a href="bayesian-hypothesis-testing-with-bayes-factors.html#cb775-6" tabindex="-1"></a>                <span class="fu">prior</span>(<span class="fu">normal</span>(<span class="dv">80</span>, <span class="dv">10</span>), <span class="at">class =</span> Intercept), </span>
<span id="cb775-7"><a href="bayesian-hypothesis-testing-with-bayes-factors.html#cb775-7" tabindex="-1"></a>                <span class="co"># slopes</span></span>
<span id="cb775-8"><a href="bayesian-hypothesis-testing-with-bayes-factors.html#cb775-8" tabindex="-1"></a>                <span class="fu">prior</span>(<span class="fu">normal</span>(<span class="dv">0</span>, <span class="dv">1</span>), <span class="at">class =</span> b, <span class="at">coef =</span> <span class="st">&quot;hate_groups_per_million&quot;</span>),</span>
<span id="cb775-9"><a href="bayesian-hypothesis-testing-with-bayes-factors.html#cb775-9" tabindex="-1"></a>                <span class="fu">prior</span>(<span class="fu">normal</span>(<span class="dv">0</span>, <span class="dv">1</span>), <span class="at">class =</span> b, <span class="at">coef =</span> <span class="st">&quot;percent_bachelors_degree_or_higher&quot;</span>),</span>
<span id="cb775-10"><a href="bayesian-hypothesis-testing-with-bayes-factors.html#cb775-10" tabindex="-1"></a>                <span class="co"># error SD</span></span>
<span id="cb775-11"><a href="bayesian-hypothesis-testing-with-bayes-factors.html#cb775-11" tabindex="-1"></a>                <span class="fu">prior</span>(<span class="fu">normal</span>(<span class="dv">0</span>, <span class="dv">2</span>), <span class="at">class =</span> sigma))</span>
<span id="cb775-12"><a href="bayesian-hypothesis-testing-with-bayes-factors.html#cb775-12" tabindex="-1"></a></span>
<span id="cb775-13"><a href="bayesian-hypothesis-testing-with-bayes-factors.html#cb775-13" tabindex="-1"></a><span class="co"># estimate the model</span></span>
<span id="cb775-14"><a href="bayesian-hypothesis-testing-with-bayes-factors.html#cb775-14" tabindex="-1"></a>mod_regression <span class="ot">&lt;-</span> brms<span class="sc">::</span><span class="fu">brm</span>(<span class="at">formula =</span> percent_Trump_votes <span class="sc">~</span> hate_groups_per_million <span class="sc">+</span> percent_bachelors_degree_or_higher, </span>
<span id="cb775-15"><a href="bayesian-hypothesis-testing-with-bayes-factors.html#cb775-15" tabindex="-1"></a>                 <span class="at">data=</span>dat, <span class="at">seed=</span><span class="dv">20221213</span>, <span class="at">prior =</span> mod_priors, <span class="at">sample_prior=</span><span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## Compiling Stan program...</code></pre>
<pre><code>## Start sampling</code></pre>
<pre><code>## 
## SAMPLING FOR MODEL &#39;anon_model&#39; NOW (CHAIN 1).
## Chain 1: 
## Chain 1: Gradient evaluation took 1.6e-05 seconds
## Chain 1: 1000 transitions using 10 leapfrog steps per transition would take 0.16 seconds.
## Chain 1: Adjust your expectations accordingly!
## Chain 1: 
## Chain 1: 
## Chain 1: Iteration:    1 / 2000 [  0%]  (Warmup)
## Chain 1: Iteration:  200 / 2000 [ 10%]  (Warmup)
## Chain 1: Iteration:  400 / 2000 [ 20%]  (Warmup)
## Chain 1: Iteration:  600 / 2000 [ 30%]  (Warmup)
## Chain 1: Iteration:  800 / 2000 [ 40%]  (Warmup)
## Chain 1: Iteration: 1000 / 2000 [ 50%]  (Warmup)
## Chain 1: Iteration: 1001 / 2000 [ 50%]  (Sampling)
## Chain 1: Iteration: 1200 / 2000 [ 60%]  (Sampling)
## Chain 1: Iteration: 1400 / 2000 [ 70%]  (Sampling)
## Chain 1: Iteration: 1600 / 2000 [ 80%]  (Sampling)
## Chain 1: Iteration: 1800 / 2000 [ 90%]  (Sampling)
## Chain 1: Iteration: 2000 / 2000 [100%]  (Sampling)
## Chain 1: 
## Chain 1:  Elapsed Time: 0.037 seconds (Warm-up)
## Chain 1:                0.034 seconds (Sampling)
## Chain 1:                0.071 seconds (Total)
## Chain 1: 
## 
## SAMPLING FOR MODEL &#39;anon_model&#39; NOW (CHAIN 2).
## Chain 2: 
## Chain 2: Gradient evaluation took 5e-06 seconds
## Chain 2: 1000 transitions using 10 leapfrog steps per transition would take 0.05 seconds.
## Chain 2: Adjust your expectations accordingly!
## Chain 2: 
## Chain 2: 
## Chain 2: Iteration:    1 / 2000 [  0%]  (Warmup)
## Chain 2: Iteration:  200 / 2000 [ 10%]  (Warmup)
## Chain 2: Iteration:  400 / 2000 [ 20%]  (Warmup)
## Chain 2: Iteration:  600 / 2000 [ 30%]  (Warmup)
## Chain 2: Iteration:  800 / 2000 [ 40%]  (Warmup)
## Chain 2: Iteration: 1000 / 2000 [ 50%]  (Warmup)
## Chain 2: Iteration: 1001 / 2000 [ 50%]  (Sampling)
## Chain 2: Iteration: 1200 / 2000 [ 60%]  (Sampling)
## Chain 2: Iteration: 1400 / 2000 [ 70%]  (Sampling)
## Chain 2: Iteration: 1600 / 2000 [ 80%]  (Sampling)
## Chain 2: Iteration: 1800 / 2000 [ 90%]  (Sampling)
## Chain 2: Iteration: 2000 / 2000 [100%]  (Sampling)
## Chain 2: 
## Chain 2:  Elapsed Time: 0.038 seconds (Warm-up)
## Chain 2:                0.029 seconds (Sampling)
## Chain 2:                0.067 seconds (Total)
## Chain 2: 
## 
## SAMPLING FOR MODEL &#39;anon_model&#39; NOW (CHAIN 3).
## Chain 3: 
## Chain 3: Gradient evaluation took 5e-06 seconds
## Chain 3: 1000 transitions using 10 leapfrog steps per transition would take 0.05 seconds.
## Chain 3: Adjust your expectations accordingly!
## Chain 3: 
## Chain 3: 
## Chain 3: Iteration:    1 / 2000 [  0%]  (Warmup)
## Chain 3: Iteration:  200 / 2000 [ 10%]  (Warmup)
## Chain 3: Iteration:  400 / 2000 [ 20%]  (Warmup)
## Chain 3: Iteration:  600 / 2000 [ 30%]  (Warmup)
## Chain 3: Iteration:  800 / 2000 [ 40%]  (Warmup)
## Chain 3: Iteration: 1000 / 2000 [ 50%]  (Warmup)
## Chain 3: Iteration: 1001 / 2000 [ 50%]  (Sampling)
## Chain 3: Iteration: 1200 / 2000 [ 60%]  (Sampling)
## Chain 3: Iteration: 1400 / 2000 [ 70%]  (Sampling)
## Chain 3: Iteration: 1600 / 2000 [ 80%]  (Sampling)
## Chain 3: Iteration: 1800 / 2000 [ 90%]  (Sampling)
## Chain 3: Iteration: 2000 / 2000 [100%]  (Sampling)
## Chain 3: 
## Chain 3:  Elapsed Time: 0.038 seconds (Warm-up)
## Chain 3:                0.033 seconds (Sampling)
## Chain 3:                0.071 seconds (Total)
## Chain 3: 
## 
## SAMPLING FOR MODEL &#39;anon_model&#39; NOW (CHAIN 4).
## Chain 4: 
## Chain 4: Gradient evaluation took 5e-06 seconds
## Chain 4: 1000 transitions using 10 leapfrog steps per transition would take 0.05 seconds.
## Chain 4: Adjust your expectations accordingly!
## Chain 4: 
## Chain 4: 
## Chain 4: Iteration:    1 / 2000 [  0%]  (Warmup)
## Chain 4: Iteration:  200 / 2000 [ 10%]  (Warmup)
## Chain 4: Iteration:  400 / 2000 [ 20%]  (Warmup)
## Chain 4: Iteration:  600 / 2000 [ 30%]  (Warmup)
## Chain 4: Iteration:  800 / 2000 [ 40%]  (Warmup)
## Chain 4: Iteration: 1000 / 2000 [ 50%]  (Warmup)
## Chain 4: Iteration: 1001 / 2000 [ 50%]  (Sampling)
## Chain 4: Iteration: 1200 / 2000 [ 60%]  (Sampling)
## Chain 4: Iteration: 1400 / 2000 [ 70%]  (Sampling)
## Chain 4: Iteration: 1600 / 2000 [ 80%]  (Sampling)
## Chain 4: Iteration: 1800 / 2000 [ 90%]  (Sampling)
## Chain 4: Iteration: 2000 / 2000 [100%]  (Sampling)
## Chain 4: 
## Chain 4:  Elapsed Time: 0.037 seconds (Warm-up)
## Chain 4:                0.034 seconds (Sampling)
## Chain 4:                0.071 seconds (Total)
## Chain 4:</code></pre>
<p>The results of this model are</p>
<div class="sourceCode" id="cb779"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb779-1"><a href="bayesian-hypothesis-testing-with-bayes-factors.html#cb779-1" tabindex="-1"></a><span class="fu">summary</span>(mod_regression)</span></code></pre></div>
<pre><code>##  Family: gaussian 
##   Links: mu = identity; sigma = identity 
## Formula: percent_Trump_votes ~ hate_groups_per_million + percent_bachelors_degree_or_higher 
##    Data: dat (Number of observations: 50) 
##   Draws: 4 chains, each with iter = 2000; warmup = 1000; thin = 1;
##          total post-warmup draws = 4000
## 
## Population-Level Effects: 
##                                    Estimate Est.Error l-95% CI u-95% CI Rhat
## Intercept                             82.80      5.61    71.76    94.12 1.00
## hate_groups_per_million                1.09      0.42     0.22     1.92 1.00
## percent_bachelors_degree_or_higher    -1.21      0.17    -1.56    -0.88 1.00
##                                    Bulk_ESS Tail_ESS
## Intercept                              3733     2538
## hate_groups_per_million                3744     3113
## percent_bachelors_degree_or_higher     3978     2624
## 
## Family Specific Parameters: 
##       Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS
## sigma     6.18      0.55     5.19     7.33 1.00     3887     2870
## 
## Draws were sampled using sampling(NUTS). For each parameter, Bulk_ESS
## and Tail_ESS are effective sample size measures, and Rhat is the potential
## scale reduction factor on split chains (at convergence, Rhat = 1).</code></pre>
<div id="testing-simple-point-and-directional-hypotheses-for-parameters-of-brms-models" class="section level3 hasAnchor" number="13.2.1">
<h3><span class="header-section-number">13.2.1</span> Testing simple point and directional hypotheses for parameters of <code>brms</code> models<a href="bayesian-hypothesis-testing-with-bayes-factors.html#testing-simple-point-and-directional-hypotheses-for-parameters-of-brms-models" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The <code>brms::hypothesis()</code> function can be used to test hypotheses about single parameters of <code>brms</code> models. This requires to set the argument <code>sample_prior=TRUE</code> in the <code>brms::brm()</code> function. The <code>brms::hypothesis()</code> function will <strong>not</strong> work properly without this. The <code>brms::hypothesis()</code> function has the following important arguments:</p>
<ul>
<li><code>x</code>: a model of class <code>brmsfit</code> as fitted by <code>brms::brm()</code>. It can also be a <code>data.frame</code> with posterior draws (in rows) of parameters (in columns).</li>
<li><code>hypothesis</code>: a character vector describing hypotheses to be tested.</li>
<li><code>class</code>: a string specifying the class of parameter(s) tested (<code>"b"</code> is common and the default, other common options are <code>"sd"</code> and <code>"cor"</code>). This argument is not necessary, but can be handy to avoid having to specify the full names of the parameters.</li>
<li><code>group</code>: a string characterising the grouping factor to evaluate only group-level effects parameters.</li>
<li><code>alpha</code>: used to specify the width of the HDI (e.g. <code>alpha = .05</code> for a 95% HDI)</li>
<li><code>seed</code>: seed for the random number generator to make the results reproducible.</li>
</ul>
<p>The specification of the <code>hypothesis</code> argument is rather flexible. For example, we can test the (null) hypothesis that the slope of <code>hate_groups_per_million</code> equals 0 by specifying the hypothesis as <code>"hate_groups_per_million = 0"</code>:</p>
<div class="sourceCode" id="cb781"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb781-1"><a href="bayesian-hypothesis-testing-with-bayes-factors.html#cb781-1" tabindex="-1"></a>brms<span class="sc">::</span><span class="fu">hypothesis</span>(mod_regression, <span class="at">hypothesis=</span><span class="st">&quot;hate_groups_per_million = 0&quot;</span>)</span></code></pre></div>
<pre><code>## Hypothesis Tests for class b:
##                 Hypothesis Estimate Est.Error CI.Lower CI.Upper Evid.Ratio
## 1 (hate_groups_per_... = 0     1.09      0.42     0.22     1.92       0.12
##   Post.Prob Star
## 1      0.11    *
## ---
## &#39;CI&#39;: 90%-CI for one-sided and 95%-CI for two-sided hypotheses.
## &#39;*&#39;: For one-sided hypotheses, the posterior probability exceeds 95%;
## for two-sided hypotheses, the value tested against lies outside the 95%-CI.
## Posterior probabilities of point hypotheses assume equal prior probabilities.</code></pre>
<p>This compares <code>mod_regression</code> to an alternative model where the prior for the slope of <code>hate_groups_per_million</code> is set to a point-prior at 0 (i.e. only the value 0 is allowed). The output of the function repeats some values that are also provided in the output of the <code>summary()</code> function (the posterior mean, standard deviation, and lower- and upper-bound of the 95% HDI). In addition, we find values of <code>Evid.Ratio</code> and <code>Post.Prob</code>. The <strong>Evidence Ratio</strong> (<code>Evid.Ratio</code>) is the value of the Bayes Factor <span class="math inline">\(\text{BF}_{01}\)</span> comparing the model specified in the hypothesis (MODEl R) to the less restrictive MODEL G (<code>mod_regression</code>). So values larger than 1 indicate that the data provides evidence for the tested hypothesis (MODEL R) to MODEL G. Conversely, values smaller than 1 indicate evidence for MODEL G over MODEL R. The value found here (<span class="math inline">\(\text{BF}_{01} = 0.1180559\)</span>) can be considered “moderate” evidence for MODEL G which allows <code>hate_groups_per_million</code> to have an effect, compared to MODEL R which fixes the effect to 0. The Bayes Factor in this procedure is calculated via the so-called Savage-Dickey density ratio <span class="citation">(<a href="#ref-wagenmakers2010bayesian">Wagenmakers et al. 2010</a>)</span>. The <strong>Posterior Probability</strong> is the posterior probability that the hypothesis is true. For this point-hypothesis, this is the posterior probability of the model with the point-prior (MODEL R), assuming equal prior probabilities for this model and MODEL G.</p>
<p>Directional hypotheses can also be tested. For example, we can test the hypothesis that the slope of <code>hate_groups_per_million</code> is larger than 0 by specifying the hypothesis as <code>"hate_groups_per_million &gt; 0"</code>:</p>
<div class="sourceCode" id="cb783"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb783-1"><a href="bayesian-hypothesis-testing-with-bayes-factors.html#cb783-1" tabindex="-1"></a>brms<span class="sc">::</span><span class="fu">hypothesis</span>(mod_regression, <span class="at">hypothesis=</span><span class="st">&quot;hate_groups_per_million &gt; 0&quot;</span>)</span></code></pre></div>
<pre><code>## Hypothesis Tests for class b:
##                 Hypothesis Estimate Est.Error CI.Lower CI.Upper Evid.Ratio
## 1 (hate_groups_per_... &gt; 0     1.09      0.42     0.37     1.78     152.85
##   Post.Prob Star
## 1      0.99    *
## ---
## &#39;CI&#39;: 90%-CI for one-sided and 95%-CI for two-sided hypotheses.
## &#39;*&#39;: For one-sided hypotheses, the posterior probability exceeds 95%;
## for two-sided hypotheses, the value tested against lies outside the 95%-CI.
## Posterior probabilities of point hypotheses assume equal prior probabilities.</code></pre>
<p>Whilst the output is similar as before, for these directional tests, a different procedure is used to compute the “evidence ratio”. Here, the evidence ratio is the posterior probability that the parameter is larger than 0, divided by the posterior probability that the parameter value is smaller than 0, e.g.:
<span class="math display">\[\text{Evidence ratio} = \frac{p(\beta &gt; 0|\text{data})}{p(\beta &lt; 0|\text{data})}\]</span>
which is estimated simply by the proportion of posterior samples that are larger than 0 (which is also stated under <code>Post.Prob</code>), divided by the proportion of posterior samples smaller than 0 (which equals <span class="math inline">\(1-\)</span><code>Post.Prob</code>). You can also use the procedure to test some “wacky” hypotheses, such as that the slope of <code>hate_groups_per_million</code> is smaller than the slope of <code>percent_bachelors_degree_or_higher</code>:</p>
<div class="sourceCode" id="cb785"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb785-1"><a href="bayesian-hypothesis-testing-with-bayes-factors.html#cb785-1" tabindex="-1"></a>brms<span class="sc">::</span><span class="fu">hypothesis</span>(mod_regression, <span class="at">hypothesis=</span><span class="st">&quot;hate_groups_per_million &lt; percent_bachelors_degree_or_higher&quot;</span>)</span></code></pre></div>
<pre><code>## Hypothesis Tests for class b:
##                 Hypothesis Estimate Est.Error CI.Lower CI.Upper Evid.Ratio
## 1 (hate_groups_per_... &lt; 0      2.3      0.41     1.62     2.97          0
##   Post.Prob Star
## 1         0     
## ---
## &#39;CI&#39;: 90%-CI for one-sided and 95%-CI for two-sided hypotheses.
## &#39;*&#39;: For one-sided hypotheses, the posterior probability exceeds 95%;
## for two-sided hypotheses, the value tested against lies outside the 95%-CI.
## Posterior probabilities of point hypotheses assume equal prior probabilities.</code></pre>
<p>As the scales of <code>hate_groups_per_million</code> and <code>percent_bachelors_degree_or_higher</code> are quite different, this hypotheses does not necessarily make too much sense from a scientific viewpoint. The example was mainly meant to show the flexibility of the procedure.</p>
</div>
<div id="using-bridge-sampling-to-obtain-marginal-likelihoods" class="section level3 hasAnchor" number="13.2.2">
<h3><span class="header-section-number">13.2.2</span> Using bridge sampling to obtain marginal likelihoods<a href="bayesian-hypothesis-testing-with-bayes-factors.html#using-bridge-sampling-to-obtain-marginal-likelihoods" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Bridge sampling <span class="citation">(<a href="#ref-bennett1976efficient">Bennett 1976</a>; <a href="#ref-meng1996simulating">Meng and Wong 1996</a>; <a href="#ref-gronau2017tutorial">Quentin F. Gronau et al. 2017</a>)</span> provides a general method to estimate the marginal likelihood from MCMC samples. We won’t go into the details of this algorithm here <span class="citation">(<a href="#ref-gronau2017tutorial">Quentin F. Gronau et al. 2017</a> provide a relatively readable introduction to this)</span>, but note that it is a sampling-based approximation, and the accuracy of the method will depend on how many samples are used (and whether the MCMC algorithm has converged to sampling from the posterior distribution).</p>
<p>The implementation of bridge sampling in the <code>bridgesampling</code>, for which the <code>brms::bridge_sampler()</code> function provides a simple wrapper, requires that all parameters of the model are sampled at each step. This can be requested by setting the option <code>save_pars = save_pars(all = TRUE)</code> in the call to <code>brms::brm()</code>. We did not do this before, so to be able to use the <code>brms::bridge_sampler()</code> function, we should first re-estimate the model with:</p>
<div class="sourceCode" id="cb787"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb787-1"><a href="bayesian-hypothesis-testing-with-bayes-factors.html#cb787-1" tabindex="-1"></a>mod_regression <span class="ot">&lt;-</span> brms<span class="sc">::</span><span class="fu">brm</span>(<span class="at">formula =</span> percent_Trump_votes <span class="sc">~</span> hate_groups_per_million <span class="sc">+</span> percent_bachelors_degree_or_higher, </span>
<span id="cb787-2"><a href="bayesian-hypothesis-testing-with-bayes-factors.html#cb787-2" tabindex="-1"></a>                 <span class="at">data=</span>dat, <span class="at">seed=</span><span class="dv">20221213</span>, <span class="at">prior =</span> mod_priors, </span>
<span id="cb787-3"><a href="bayesian-hypothesis-testing-with-bayes-factors.html#cb787-3" tabindex="-1"></a>                 <span class="at">save_pars =</span> <span class="fu">save_pars</span>(<span class="at">all =</span> <span class="cn">TRUE</span>))</span></code></pre></div>
<pre><code>## Compiling Stan program...</code></pre>
<pre><code>## Start sampling</code></pre>
<pre><code>## 
## SAMPLING FOR MODEL &#39;anon_model&#39; NOW (CHAIN 1).
## Chain 1: 
## Chain 1: Gradient evaluation took 1.3e-05 seconds
## Chain 1: 1000 transitions using 10 leapfrog steps per transition would take 0.13 seconds.
## Chain 1: Adjust your expectations accordingly!
## Chain 1: 
## Chain 1: 
## Chain 1: Iteration:    1 / 2000 [  0%]  (Warmup)
## Chain 1: Iteration:  200 / 2000 [ 10%]  (Warmup)
## Chain 1: Iteration:  400 / 2000 [ 20%]  (Warmup)
## Chain 1: Iteration:  600 / 2000 [ 30%]  (Warmup)
## Chain 1: Iteration:  800 / 2000 [ 40%]  (Warmup)
## Chain 1: Iteration: 1000 / 2000 [ 50%]  (Warmup)
## Chain 1: Iteration: 1001 / 2000 [ 50%]  (Sampling)
## Chain 1: Iteration: 1200 / 2000 [ 60%]  (Sampling)
## Chain 1: Iteration: 1400 / 2000 [ 70%]  (Sampling)
## Chain 1: Iteration: 1600 / 2000 [ 80%]  (Sampling)
## Chain 1: Iteration: 1800 / 2000 [ 90%]  (Sampling)
## Chain 1: Iteration: 2000 / 2000 [100%]  (Sampling)
## Chain 1: 
## Chain 1:  Elapsed Time: 0.045 seconds (Warm-up)
## Chain 1:                0.031 seconds (Sampling)
## Chain 1:                0.076 seconds (Total)
## Chain 1: 
## 
## SAMPLING FOR MODEL &#39;anon_model&#39; NOW (CHAIN 2).
## Chain 2: 
## Chain 2: Gradient evaluation took 6e-06 seconds
## Chain 2: 1000 transitions using 10 leapfrog steps per transition would take 0.06 seconds.
## Chain 2: Adjust your expectations accordingly!
## Chain 2: 
## Chain 2: 
## Chain 2: Iteration:    1 / 2000 [  0%]  (Warmup)
## Chain 2: Iteration:  200 / 2000 [ 10%]  (Warmup)
## Chain 2: Iteration:  400 / 2000 [ 20%]  (Warmup)
## Chain 2: Iteration:  600 / 2000 [ 30%]  (Warmup)
## Chain 2: Iteration:  800 / 2000 [ 40%]  (Warmup)
## Chain 2: Iteration: 1000 / 2000 [ 50%]  (Warmup)
## Chain 2: Iteration: 1001 / 2000 [ 50%]  (Sampling)
## Chain 2: Iteration: 1200 / 2000 [ 60%]  (Sampling)
## Chain 2: Iteration: 1400 / 2000 [ 70%]  (Sampling)
## Chain 2: Iteration: 1600 / 2000 [ 80%]  (Sampling)
## Chain 2: Iteration: 1800 / 2000 [ 90%]  (Sampling)
## Chain 2: Iteration: 2000 / 2000 [100%]  (Sampling)
## Chain 2: 
## Chain 2:  Elapsed Time: 0.042 seconds (Warm-up)
## Chain 2:                0.036 seconds (Sampling)
## Chain 2:                0.078 seconds (Total)
## Chain 2: 
## 
## SAMPLING FOR MODEL &#39;anon_model&#39; NOW (CHAIN 3).
## Chain 3: 
## Chain 3: Gradient evaluation took 6e-06 seconds
## Chain 3: 1000 transitions using 10 leapfrog steps per transition would take 0.06 seconds.
## Chain 3: Adjust your expectations accordingly!
## Chain 3: 
## Chain 3: 
## Chain 3: Iteration:    1 / 2000 [  0%]  (Warmup)
## Chain 3: Iteration:  200 / 2000 [ 10%]  (Warmup)
## Chain 3: Iteration:  400 / 2000 [ 20%]  (Warmup)
## Chain 3: Iteration:  600 / 2000 [ 30%]  (Warmup)
## Chain 3: Iteration:  800 / 2000 [ 40%]  (Warmup)
## Chain 3: Iteration: 1000 / 2000 [ 50%]  (Warmup)
## Chain 3: Iteration: 1001 / 2000 [ 50%]  (Sampling)
## Chain 3: Iteration: 1200 / 2000 [ 60%]  (Sampling)
## Chain 3: Iteration: 1400 / 2000 [ 70%]  (Sampling)
## Chain 3: Iteration: 1600 / 2000 [ 80%]  (Sampling)
## Chain 3: Iteration: 1800 / 2000 [ 90%]  (Sampling)
## Chain 3: Iteration: 2000 / 2000 [100%]  (Sampling)
## Chain 3: 
## Chain 3:  Elapsed Time: 0.041 seconds (Warm-up)
## Chain 3:                0.036 seconds (Sampling)
## Chain 3:                0.077 seconds (Total)
## Chain 3: 
## 
## SAMPLING FOR MODEL &#39;anon_model&#39; NOW (CHAIN 4).
## Chain 4: 
## Chain 4: Gradient evaluation took 6e-06 seconds
## Chain 4: 1000 transitions using 10 leapfrog steps per transition would take 0.06 seconds.
## Chain 4: Adjust your expectations accordingly!
## Chain 4: 
## Chain 4: 
## Chain 4: Iteration:    1 / 2000 [  0%]  (Warmup)
## Chain 4: Iteration:  200 / 2000 [ 10%]  (Warmup)
## Chain 4: Iteration:  400 / 2000 [ 20%]  (Warmup)
## Chain 4: Iteration:  600 / 2000 [ 30%]  (Warmup)
## Chain 4: Iteration:  800 / 2000 [ 40%]  (Warmup)
## Chain 4: Iteration: 1000 / 2000 [ 50%]  (Warmup)
## Chain 4: Iteration: 1001 / 2000 [ 50%]  (Sampling)
## Chain 4: Iteration: 1200 / 2000 [ 60%]  (Sampling)
## Chain 4: Iteration: 1400 / 2000 [ 70%]  (Sampling)
## Chain 4: Iteration: 1600 / 2000 [ 80%]  (Sampling)
## Chain 4: Iteration: 1800 / 2000 [ 90%]  (Sampling)
## Chain 4: Iteration: 2000 / 2000 [100%]  (Sampling)
## Chain 4: 
## Chain 4:  Elapsed Time: 0.041 seconds (Warm-up)
## Chain 4:                0.036 seconds (Sampling)
## Chain 4:                0.077 seconds (Total)
## Chain 4:</code></pre>
<p>Having set <code>save_pars = save_pars(all = TRUE)</code>, we can then call the <code>brms::bridge_sampler()</code> function on the estimated model as:</p>
<div class="sourceCode" id="cb791"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb791-1"><a href="bayesian-hypothesis-testing-with-bayes-factors.html#cb791-1" tabindex="-1"></a><span class="co"># compute (log) marginal likelihood and store it</span></span>
<span id="cb791-2"><a href="bayesian-hypothesis-testing-with-bayes-factors.html#cb791-2" tabindex="-1"></a>marg_lik_mod_regression <span class="ot">&lt;-</span> brms<span class="sc">::</span><span class="fu">bridge_sampler</span>(mod_regression)</span></code></pre></div>
<pre><code>## Iteration: 1
## Iteration: 2
## Iteration: 3
## Iteration: 4
## Iteration: 5</code></pre>
<div class="sourceCode" id="cb793"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb793-1"><a href="bayesian-hypothesis-testing-with-bayes-factors.html#cb793-1" tabindex="-1"></a><span class="co"># print result</span></span>
<span id="cb793-2"><a href="bayesian-hypothesis-testing-with-bayes-factors.html#cb793-2" tabindex="-1"></a>marg_lik_mod_regression</span></code></pre></div>
<pre><code>## Bridge sampling estimate of the log marginal likelihood: -180.6181
## Estimate obtained in 5 iteration(s) via method &quot;normal&quot;.</code></pre>
<p>This function returns the approximate (natural) logarithm of the marginal likelihood, i.e.
<span class="math display">\[\widehat{\log p}(\text{data}|\text{MODEL})\]</span>
To compute a Bayes Factor, we will also need the (log) marginal likelihood for an alternative model. For example, we can set the prior for the slope of <code>hate_groups_per_million</code> to be a point-prior at 0 by specifying the prior distribution for that parameter as <code>constant(0)</code>:</p>
<div class="sourceCode" id="cb795"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb795-1"><a href="bayesian-hypothesis-testing-with-bayes-factors.html#cb795-1" tabindex="-1"></a>mod_priors_alt <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="co"># intercept</span></span>
<span id="cb795-2"><a href="bayesian-hypothesis-testing-with-bayes-factors.html#cb795-2" tabindex="-1"></a>                <span class="fu">prior</span>(<span class="fu">normal</span>(<span class="dv">80</span>, <span class="dv">10</span>), <span class="at">class =</span> Intercept), </span>
<span id="cb795-3"><a href="bayesian-hypothesis-testing-with-bayes-factors.html#cb795-3" tabindex="-1"></a>                <span class="co"># slopes</span></span>
<span id="cb795-4"><a href="bayesian-hypothesis-testing-with-bayes-factors.html#cb795-4" tabindex="-1"></a>                <span class="fu">prior</span>(<span class="fu">constant</span>(<span class="dv">0</span>), <span class="at">class =</span> b, <span class="at">coef =</span> <span class="st">&quot;hate_groups_per_million&quot;</span>),</span>
<span id="cb795-5"><a href="bayesian-hypothesis-testing-with-bayes-factors.html#cb795-5" tabindex="-1"></a>                <span class="fu">prior</span>(<span class="fu">normal</span>(<span class="dv">0</span>, <span class="dv">1</span>), <span class="at">class =</span> b, <span class="at">coef =</span> <span class="st">&quot;percent_bachelors_degree_or_higher&quot;</span>),</span>
<span id="cb795-6"><a href="bayesian-hypothesis-testing-with-bayes-factors.html#cb795-6" tabindex="-1"></a>                <span class="co"># error SD</span></span>
<span id="cb795-7"><a href="bayesian-hypothesis-testing-with-bayes-factors.html#cb795-7" tabindex="-1"></a>                <span class="fu">prior</span>(<span class="fu">normal</span>(<span class="dv">0</span>, <span class="dv">2</span>), <span class="at">class =</span> sigma))</span>
<span id="cb795-8"><a href="bayesian-hypothesis-testing-with-bayes-factors.html#cb795-8" tabindex="-1"></a></span>
<span id="cb795-9"><a href="bayesian-hypothesis-testing-with-bayes-factors.html#cb795-9" tabindex="-1"></a>mod_regression_alt <span class="ot">&lt;-</span> brms<span class="sc">::</span><span class="fu">brm</span>(<span class="at">formula =</span> percent_Trump_votes <span class="sc">~</span> hate_groups_per_million <span class="sc">+</span> percent_bachelors_degree_or_higher, </span>
<span id="cb795-10"><a href="bayesian-hypothesis-testing-with-bayes-factors.html#cb795-10" tabindex="-1"></a>                 <span class="at">data=</span>dat, <span class="at">seed=</span><span class="dv">20221213</span>, <span class="at">prior =</span> mod_priors_alt,</span>
<span id="cb795-11"><a href="bayesian-hypothesis-testing-with-bayes-factors.html#cb795-11" tabindex="-1"></a>                 <span class="at">save_pars =</span> <span class="fu">save_pars</span>(<span class="at">all =</span> <span class="cn">TRUE</span>))</span></code></pre></div>
<pre><code>## Compiling Stan program...</code></pre>
<pre><code>## Start sampling</code></pre>
<pre><code>## 
## SAMPLING FOR MODEL &#39;anon_model&#39; NOW (CHAIN 1).
## Chain 1: 
## Chain 1: Gradient evaluation took 1.6e-05 seconds
## Chain 1: 1000 transitions using 10 leapfrog steps per transition would take 0.16 seconds.
## Chain 1: Adjust your expectations accordingly!
## Chain 1: 
## Chain 1: 
## Chain 1: Iteration:    1 / 2000 [  0%]  (Warmup)
## Chain 1: Iteration:  200 / 2000 [ 10%]  (Warmup)
## Chain 1: Iteration:  400 / 2000 [ 20%]  (Warmup)
## Chain 1: Iteration:  600 / 2000 [ 30%]  (Warmup)
## Chain 1: Iteration:  800 / 2000 [ 40%]  (Warmup)
## Chain 1: Iteration: 1000 / 2000 [ 50%]  (Warmup)
## Chain 1: Iteration: 1001 / 2000 [ 50%]  (Sampling)
## Chain 1: Iteration: 1200 / 2000 [ 60%]  (Sampling)
## Chain 1: Iteration: 1400 / 2000 [ 70%]  (Sampling)
## Chain 1: Iteration: 1600 / 2000 [ 80%]  (Sampling)
## Chain 1: Iteration: 1800 / 2000 [ 90%]  (Sampling)
## Chain 1: Iteration: 2000 / 2000 [100%]  (Sampling)
## Chain 1: 
## Chain 1:  Elapsed Time: 0.038 seconds (Warm-up)
## Chain 1:                0.032 seconds (Sampling)
## Chain 1:                0.07 seconds (Total)
## Chain 1: 
## 
## SAMPLING FOR MODEL &#39;anon_model&#39; NOW (CHAIN 2).
## Chain 2: 
## Chain 2: Gradient evaluation took 6e-06 seconds
## Chain 2: 1000 transitions using 10 leapfrog steps per transition would take 0.06 seconds.
## Chain 2: Adjust your expectations accordingly!
## Chain 2: 
## Chain 2: 
## Chain 2: Iteration:    1 / 2000 [  0%]  (Warmup)
## Chain 2: Iteration:  200 / 2000 [ 10%]  (Warmup)
## Chain 2: Iteration:  400 / 2000 [ 20%]  (Warmup)
## Chain 2: Iteration:  600 / 2000 [ 30%]  (Warmup)
## Chain 2: Iteration:  800 / 2000 [ 40%]  (Warmup)
## Chain 2: Iteration: 1000 / 2000 [ 50%]  (Warmup)
## Chain 2: Iteration: 1001 / 2000 [ 50%]  (Sampling)
## Chain 2: Iteration: 1200 / 2000 [ 60%]  (Sampling)
## Chain 2: Iteration: 1400 / 2000 [ 70%]  (Sampling)
## Chain 2: Iteration: 1600 / 2000 [ 80%]  (Sampling)
## Chain 2: Iteration: 1800 / 2000 [ 90%]  (Sampling)
## Chain 2: Iteration: 2000 / 2000 [100%]  (Sampling)
## Chain 2: 
## Chain 2:  Elapsed Time: 0.037 seconds (Warm-up)
## Chain 2:                0.026 seconds (Sampling)
## Chain 2:                0.063 seconds (Total)
## Chain 2: 
## 
## SAMPLING FOR MODEL &#39;anon_model&#39; NOW (CHAIN 3).
## Chain 3: 
## Chain 3: Gradient evaluation took 6e-06 seconds
## Chain 3: 1000 transitions using 10 leapfrog steps per transition would take 0.06 seconds.
## Chain 3: Adjust your expectations accordingly!
## Chain 3: 
## Chain 3: 
## Chain 3: Iteration:    1 / 2000 [  0%]  (Warmup)
## Chain 3: Iteration:  200 / 2000 [ 10%]  (Warmup)
## Chain 3: Iteration:  400 / 2000 [ 20%]  (Warmup)
## Chain 3: Iteration:  600 / 2000 [ 30%]  (Warmup)
## Chain 3: Iteration:  800 / 2000 [ 40%]  (Warmup)
## Chain 3: Iteration: 1000 / 2000 [ 50%]  (Warmup)
## Chain 3: Iteration: 1001 / 2000 [ 50%]  (Sampling)
## Chain 3: Iteration: 1200 / 2000 [ 60%]  (Sampling)
## Chain 3: Iteration: 1400 / 2000 [ 70%]  (Sampling)
## Chain 3: Iteration: 1600 / 2000 [ 80%]  (Sampling)
## Chain 3: Iteration: 1800 / 2000 [ 90%]  (Sampling)
## Chain 3: Iteration: 2000 / 2000 [100%]  (Sampling)
## Chain 3: 
## Chain 3:  Elapsed Time: 0.033 seconds (Warm-up)
## Chain 3:                0.028 seconds (Sampling)
## Chain 3:                0.061 seconds (Total)
## Chain 3: 
## 
## SAMPLING FOR MODEL &#39;anon_model&#39; NOW (CHAIN 4).
## Chain 4: 
## Chain 4: Gradient evaluation took 5e-06 seconds
## Chain 4: 1000 transitions using 10 leapfrog steps per transition would take 0.05 seconds.
## Chain 4: Adjust your expectations accordingly!
## Chain 4: 
## Chain 4: 
## Chain 4: Iteration:    1 / 2000 [  0%]  (Warmup)
## Chain 4: Iteration:  200 / 2000 [ 10%]  (Warmup)
## Chain 4: Iteration:  400 / 2000 [ 20%]  (Warmup)
## Chain 4: Iteration:  600 / 2000 [ 30%]  (Warmup)
## Chain 4: Iteration:  800 / 2000 [ 40%]  (Warmup)
## Chain 4: Iteration: 1000 / 2000 [ 50%]  (Warmup)
## Chain 4: Iteration: 1001 / 2000 [ 50%]  (Sampling)
## Chain 4: Iteration: 1200 / 2000 [ 60%]  (Sampling)
## Chain 4: Iteration: 1400 / 2000 [ 70%]  (Sampling)
## Chain 4: Iteration: 1600 / 2000 [ 80%]  (Sampling)
## Chain 4: Iteration: 1800 / 2000 [ 90%]  (Sampling)
## Chain 4: Iteration: 2000 / 2000 [100%]  (Sampling)
## Chain 4: 
## Chain 4:  Elapsed Time: 0.034 seconds (Warm-up)
## Chain 4:                0.028 seconds (Sampling)
## Chain 4:                0.062 seconds (Total)
## Chain 4:</code></pre>
<p>We can now use the <code>brms::bridge_sampler()</code> function to compute the (log) marginal likelihood for this estimated model as:</p>
<div class="sourceCode" id="cb799"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb799-1"><a href="bayesian-hypothesis-testing-with-bayes-factors.html#cb799-1" tabindex="-1"></a><span class="co"># compute (log) marginal likelihood and store it</span></span>
<span id="cb799-2"><a href="bayesian-hypothesis-testing-with-bayes-factors.html#cb799-2" tabindex="-1"></a>marg_lik_mod_regression_alt <span class="ot">&lt;-</span> brms<span class="sc">::</span><span class="fu">bridge_sampler</span>(mod_regression_alt)</span></code></pre></div>
<pre><code>## Iteration: 1
## Iteration: 2
## Iteration: 3
## Iteration: 4</code></pre>
<div class="sourceCode" id="cb801"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb801-1"><a href="bayesian-hypothesis-testing-with-bayes-factors.html#cb801-1" tabindex="-1"></a><span class="co"># print result</span></span>
<span id="cb801-2"><a href="bayesian-hypothesis-testing-with-bayes-factors.html#cb801-2" tabindex="-1"></a>marg_lik_mod_regression_alt</span></code></pre></div>
<pre><code>## Bridge sampling estimate of the log marginal likelihood: -182.9612
## Estimate obtained in 4 iteration(s) via method &quot;normal&quot;.</code></pre>
<p>We now have two (log) marginal likelihoods. To compute the actual Bayes Factor, we can use the factor that:
<span class="math display">\[\begin{aligned}
\log \left( \frac{p(\text{data}|\text{MODEL 1})}{p(\text{data}|\text{MODEL 1})} \right) &amp;= \log p(\text{data}|\text{MODEL 1}) - \log p(\text{data}|\text{MODEL 2}) \\
\frac{p(\text{data}|\text{MODEL 1})}{p(\text{data}|\text{MODEL 1})} &amp;= \exp \left( \log p(\text{data}|\text{MODEL 1}) - \log p(\text{data}|\text{MODEL 2}) \right)
\end{aligned}\]</span>
So we can compute the Bayes factor by taking the difference between the log marginal likelihoods, and then exponentiating:</p>
<div class="sourceCode" id="cb803"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb803-1"><a href="bayesian-hypothesis-testing-with-bayes-factors.html#cb803-1" tabindex="-1"></a><span class="fu">exp</span>(marg_lik_mod_regression<span class="sc">$</span>logml <span class="sc">-</span> marg_lik_mod_regression_alt<span class="sc">$</span>logml)</span></code></pre></div>
<pre><code>## [1] 10.4133</code></pre>
<p>where we have used that each object returned by the <code>brms::bridge_sampler()</code> is a list with the named element <code>logml</code> being equal to the (approximate) marginal log likelihood.</p>
<p>Using this explicit computation can be avoided by calling the <code>bridgesampling::bf()</code> function, which will provide the actual Bayes Factor from the log marginal likelihoods:</p>
<div class="sourceCode" id="cb805"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb805-1"><a href="bayesian-hypothesis-testing-with-bayes-factors.html#cb805-1" tabindex="-1"></a>bridgesampling<span class="sc">::</span><span class="fu">bf</span>(marg_lik_mod_regression, marg_lik_mod_regression_alt)</span></code></pre></div>
<pre><code>## Estimated Bayes factor in favor of marg_lik_mod_regression over marg_lik_mod_regression_alt: 10.41330</code></pre>

</div>
</div>
</div>
<h3>References<a href="references.html#references" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div id="refs" class="references csl-bib-body hanging-indent">
<div id="ref-bennett1976efficient" class="csl-entry">
Bennett, Charles H. 1976. <span>“Efficient Estimation of Free Energy Differences from <span>M</span>onte <span>C</span>arlo Data.”</span> <em>Journal of Computational Physics</em> 22 (2): 245–68.
</div>
<div id="ref-gronau2017tutorial" class="csl-entry">
Gronau, Quentin F, Alexandra Sarafoglou, Dora Matzke, Alexander Ly, Udo Boehm, Maarten Marsman, David S Leslie, Jonathan J Forster, Eric-Jan Wagenmakers, and Helen Steingroever. 2017. <span>“A Tutorial on Bridge Sampling.”</span> <em>Journal of Mathematical Psychology</em> 81: 80–97.
</div>
<div id="ref-R-bridgesampling" class="csl-entry">
Gronau, Quentin F., and Henrik Singmann. 2021. <em>Bridgesampling: Bridge Sampling for Marginal Likelihoods and Bayes Factors</em>. <a href="https://github.com/quentingronau/bridgesampling">https://github.com/quentingronau/bridgesampling</a>.
</div>
<div id="ref-meng1996simulating" class="csl-entry">
Meng, Xiao-Li, and Wing Hung Wong. 1996. <span>“Simulating Ratios of Normalizing Constants via a Simple Identity: A Theoretical Exploration.”</span> <em>Statistica Sinica</em>, 831–60.
</div>
<div id="ref-R-BayesFactor" class="csl-entry">
Morey, Richard D., and Jeffrey N. Rouder. 2023. <em>BayesFactor: Computation of Bayes Factors for Common Designs</em>. <a href="https://richarddmorey.github.io/BayesFactor/">https://richarddmorey.github.io/BayesFactor/</a>.
</div>
<div id="ref-rouder2009bayesian" class="csl-entry">
Rouder, Jeffrey N, Paul L Speckman, Dongchu Sun, Richard D Morey, and Geoffrey Iverson. 2009. <span>“Bayesian t Tests for Accepting and Rejecting the Null Hypothesis.”</span> <em>Psychonomic Bulletin &amp; Review</em> 16 (2): 225–37.
</div>
<div id="ref-wagenmakers2010bayesian" class="csl-entry">
Wagenmakers, Eric-Jan, Tom Lodewyckx, Himanshu Kuriyal, and Raoul Grasman. 2010. <span>“Bayesian Hypothesis Testing for Psychologists: A Tutorial on the <span>S</span>avage–<span>D</span>ickey Method.”</span> <em>Cognitive Psychology</em> 60 (3): 158–89.
</div>
</div>
<div class="footnotes">
<hr />
<ol start="3">
<li id="fn3"><p>Curiously, a scaling factor of <span class="math inline">\(r = \tfrac{1}{2}\)</span> in this case corresponds to a scaling factor of <span class="math inline">\(r = \tfrac{\sqrt{2}}{2}\)</span>, which is something I don’t immediately understand, and will require further investigation.<a href="bayesian-hypothesis-testing-with-bayes-factors.html#fnref3" class="footnote-back">↩︎</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="bayesian-estimation-with-brms.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="reproducible-reports-with-rmarkdown.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="book_assets/gitbook-2.6.7/js/app.min.js"></script>
<script src="book_assets/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="book_assets/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="book_assets/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="book_assets/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="book_assets/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="book_assets/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="book_assets/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": null,
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
},
"source": null
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
