<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 9 Linear mixed-effects models | An R companion to Statistics: data analysis and modelling</title>
  <meta name="description" content="A book about how to use R related to the book Statistics: Data analysis and modelling." />
  <meta name="generator" content="bookdown 0.24 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 9 Linear mixed-effects models | An R companion to Statistics: data analysis and modelling" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="A book about how to use R related to the book Statistics: Data analysis and modelling." />
  <meta name="github-repo" content="mspeekenbrink/sdam-book" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 9 Linear mixed-effects models | An R companion to Statistics: data analysis and modelling" />
  
  <meta name="twitter:description" content="A book about how to use R related to the book Statistics: Data analysis and modelling." />
  

<meta name="author" content="Maarten Speekenbrink" />


<meta name="date" content="2021-11-26" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="repeated-measures-anova.html"/>
<link rel="next" href="bayesian-hypothesis-testing-through-bayes-factors.html"/>
<script src="book_assets/header-attrs-2.11/header-attrs.js"></script>
<script src="book_assets/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="book_assets/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="book_assets/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="book_assets/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="book_assets/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="book_assets/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="book_assets/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="book_assets/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="book_assets/anchor-sections-1.0.1/anchor-sections.css" rel="stylesheet" />
<script src="book_assets/anchor-sections-1.0.1/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a>
<ul>
<li class="chapter" data-level="0.1" data-path="index.html"><a href="index.html#acknowledgements"><i class="fa fa-check"></i><b>0.1</b> Acknowledgements</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="introduction.html"><a href="introduction.html"><i class="fa fa-check"></i><b>1</b> Introduction</a>
<ul>
<li class="chapter" data-level="1.1" data-path="introduction.html"><a href="introduction.html#what-is-r"><i class="fa fa-check"></i><b>1.1</b> What is R?</a></li>
<li class="chapter" data-level="1.2" data-path="introduction.html"><a href="introduction.html#getting-started"><i class="fa fa-check"></i><b>1.2</b> Getting started</a>
<ul>
<li class="chapter" data-level="1.2.1" data-path="introduction.html"><a href="introduction.html#download-r"><i class="fa fa-check"></i><b>1.2.1</b> Download R</a></li>
<li class="chapter" data-level="1.2.2" data-path="introduction.html"><a href="introduction.html#download-r-studio"><i class="fa fa-check"></i><b>1.2.2</b> Download R Studio</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="introduction.html"><a href="introduction.html#working-with-rstudio"><i class="fa fa-check"></i><b>1.3</b> Working with RStudio</a></li>
<li class="chapter" data-level="1.4" data-path="introduction.html"><a href="introduction.html#installing-packages"><i class="fa fa-check"></i><b>1.4</b> Installing packages</a>
<ul>
<li class="chapter" data-level="1.4.1" data-path="introduction.html"><a href="introduction.html#installing-the-sdamr-package"><i class="fa fa-check"></i><b>1.4.1</b> Installing the <code>sdamr</code> package</a></li>
</ul></li>
<li class="chapter" data-level="1.5" data-path="introduction.html"><a href="introduction.html#getting-help"><i class="fa fa-check"></i><b>1.5</b> Getting help</a></li>
<li class="chapter" data-level="1.6" data-path="introduction.html"><a href="introduction.html#first-steps-r-as-a-calculator"><i class="fa fa-check"></i><b>1.6</b> First steps: R as a calculator</a></li>
<li class="chapter" data-level="1.7" data-path="introduction.html"><a href="introduction.html#data"><i class="fa fa-check"></i><b>1.7</b> Data</a>
<ul>
<li class="chapter" data-level="1.7.1" data-path="introduction.html"><a href="introduction.html#data-types"><i class="fa fa-check"></i><b>1.7.1</b> Data types</a></li>
<li class="chapter" data-level="1.7.2" data-path="introduction.html"><a href="introduction.html#objects"><i class="fa fa-check"></i><b>1.7.2</b> Objects</a></li>
<li class="chapter" data-level="1.7.3" data-path="introduction.html"><a href="introduction.html#importing-data"><i class="fa fa-check"></i><b>1.7.3</b> Importing data</a></li>
</ul></li>
<li class="chapter" data-level="1.8" data-path="introduction.html"><a href="introduction.html#exploring-data-descriptive-statistics"><i class="fa fa-check"></i><b>1.8</b> Exploring data: Descriptive statistics</a></li>
<li class="chapter" data-level="1.9" data-path="introduction.html"><a href="introduction.html#exploring-data-creating-plots"><i class="fa fa-check"></i><b>1.9</b> Exploring data: Creating plots</a>
<ul>
<li class="chapter" data-level="1.9.1" data-path="introduction.html"><a href="introduction.html#histogram"><i class="fa fa-check"></i><b>1.9.1</b> Histogram</a></li>
<li class="chapter" data-level="1.9.2" data-path="introduction.html"><a href="introduction.html#boxplot"><i class="fa fa-check"></i><b>1.9.2</b> Boxplot</a></li>
</ul></li>
<li class="chapter" data-level="1.10" data-path="introduction.html"><a href="introduction.html#scatterplot"><i class="fa fa-check"></i><b>1.10</b> Scatterplot</a></li>
<li class="chapter" data-level="1.11" data-path="introduction.html"><a href="introduction.html#raincloud-plot"><i class="fa fa-check"></i><b>1.11</b> Raincloud plot</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="statistical-modelling.html"><a href="statistical-modelling.html"><i class="fa fa-check"></i><b>2</b> Statistical modelling</a>
<ul>
<li class="chapter" data-level="2.1" data-path="statistical-modelling.html"><a href="statistical-modelling.html#distributions"><i class="fa fa-check"></i><b>2.1</b> Distributions</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="statistical-modelling.html"><a href="statistical-modelling.html#generating-random-data"><i class="fa fa-check"></i><b>2.1.1</b> Generating random data</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="statistical-modelling.html"><a href="statistical-modelling.html#estimation"><i class="fa fa-check"></i><b>2.2</b> Estimation</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="statistical-modelling.html"><a href="statistical-modelling.html#the-likelihood-function"><i class="fa fa-check"></i><b>2.2.1</b> The likelihood function</a></li>
<li class="chapter" data-level="2.2.2" data-path="statistical-modelling.html"><a href="statistical-modelling.html#calculating-the-likelihood-ratio"><i class="fa fa-check"></i><b>2.2.2</b> Calculating the likelihood ratio</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="statistical-modelling.html"><a href="statistical-modelling.html#hypothesis-testing-directly-with-the-binomial-distribution"><i class="fa fa-check"></i><b>2.3</b> Hypothesis testing directly with the binomial distribution</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="the-one-sample-t-test.html"><a href="the-one-sample-t-test.html"><i class="fa fa-check"></i><b>3</b> The one-sample t-test</a>
<ul>
<li class="chapter" data-level="3.1" data-path="the-one-sample-t-test.html"><a href="the-one-sample-t-test.html#missing-values"><i class="fa fa-check"></i><b>3.1</b> Missing values</a></li>
<li class="chapter" data-level="3.2" data-path="the-one-sample-t-test.html"><a href="the-one-sample-t-test.html#selecting-subsets-of-data"><i class="fa fa-check"></i><b>3.2</b> Selecting subsets of data</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="the-one-sample-t-test.html"><a href="the-one-sample-t-test.html#indexing-variables"><i class="fa fa-check"></i><b>3.2.1</b> Indexing variables</a></li>
<li class="chapter" data-level="3.2.2" data-path="the-one-sample-t-test.html"><a href="the-one-sample-t-test.html#the-subset-function"><i class="fa fa-check"></i><b>3.2.2</b> The <code>subset</code> function</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="the-one-sample-t-test.html"><a href="the-one-sample-t-test.html#one-sample-t-test"><i class="fa fa-check"></i><b>3.3</b> One-sample t-test</a></li>
<li class="chapter" data-level="3.4" data-path="the-one-sample-t-test.html"><a href="the-one-sample-t-test.html#effect-size"><i class="fa fa-check"></i><b>3.4</b> Effect size</a></li>
<li class="chapter" data-level="3.5" data-path="the-one-sample-t-test.html"><a href="the-one-sample-t-test.html#nonparametric-bootstrap"><i class="fa fa-check"></i><b>3.5</b> Nonparametric bootstrap</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="regression.html"><a href="regression.html"><i class="fa fa-check"></i><b>4</b> Regression</a>
<ul>
<li class="chapter" data-level="4.1" data-path="regression.html"><a href="regression.html#estimating-an-testing-a-simple-regression-model"><i class="fa fa-check"></i><b>4.1</b> Estimating an testing a simple regression model</a></li>
<li class="chapter" data-level="4.2" data-path="regression.html"><a href="regression.html#model-comparisons"><i class="fa fa-check"></i><b>4.2</b> Model comparisons</a></li>
<li class="chapter" data-level="4.3" data-path="regression.html"><a href="regression.html#estimating-and-testing-a-multiple-regression-model"><i class="fa fa-check"></i><b>4.3</b> Estimating and testing a multiple regression model</a></li>
<li class="chapter" data-level="4.4" data-path="regression.html"><a href="regression.html#residuals-and-predicted-values"><i class="fa fa-check"></i><b>4.4</b> Residuals and predicted values</a></li>
<li class="chapter" data-level="4.5" data-path="regression.html"><a href="regression.html#plotting-pairwise-scatterplots-for-many-variables"><i class="fa fa-check"></i><b>4.5</b> Plotting pairwise scatterplots for many variables</a></li>
<li class="chapter" data-level="4.6" data-path="regression.html"><a href="regression.html#multicollinearity-and-outlier-detection"><i class="fa fa-check"></i><b>4.6</b> Multicollinearity and outlier detection</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="moderation-and-mediation.html"><a href="moderation-and-mediation.html"><i class="fa fa-check"></i><b>5</b> Moderation and mediation</a>
<ul>
<li class="chapter" data-level="5.1" data-path="moderation-and-mediation.html"><a href="moderation-and-mediation.html#moderation-in-linear-models"><i class="fa fa-check"></i><b>5.1</b> Moderation in linear models</a>
<ul>
<li class="chapter" data-level="5.1.1" data-path="moderation-and-mediation.html"><a href="moderation-and-mediation.html#a-bit-about-namespaces"><i class="fa fa-check"></i><b>5.1.1</b> A bit about namespaces</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="moderation-and-mediation.html"><a href="moderation-and-mediation.html#centering"><i class="fa fa-check"></i><b>5.2</b> Centering</a></li>
<li class="chapter" data-level="5.3" data-path="moderation-and-mediation.html"><a href="moderation-and-mediation.html#mediation-analysis"><i class="fa fa-check"></i><b>5.3</b> Mediation analysis</a>
<ul>
<li class="chapter" data-level="5.3.1" data-path="moderation-and-mediation.html"><a href="moderation-and-mediation.html#causal-steps"><i class="fa fa-check"></i><b>5.3.1</b> Causal steps</a></li>
<li class="chapter" data-level="5.3.2" data-path="moderation-and-mediation.html"><a href="moderation-and-mediation.html#investigating-the-moderated-indirect-effect-with-a-bootstrap-test"><i class="fa fa-check"></i><b>5.3.2</b> Investigating the moderated (indirect) effect with a bootstrap test</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="contrast-coding-and-oneway-anova.html"><a href="contrast-coding-and-oneway-anova.html"><i class="fa fa-check"></i><b>6</b> Contrast coding and oneway ANOVA</a>
<ul>
<li class="chapter" data-level="6.1" data-path="contrast-coding-and-oneway-anova.html"><a href="contrast-coding-and-oneway-anova.html#computing-contrast-coding-predictors"><i class="fa fa-check"></i><b>6.1</b> Computing contrast-coding predictors</a></li>
<li class="chapter" data-level="6.2" data-path="contrast-coding-and-oneway-anova.html"><a href="contrast-coding-and-oneway-anova.html#assigning-contrasts-to-factors"><i class="fa fa-check"></i><b>6.2</b> Assigning contrasts to factors</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="contrast-coding-and-oneway-anova.html"><a href="contrast-coding-and-oneway-anova.html#default-coding-schemes"><i class="fa fa-check"></i><b>6.2.1</b> Default coding schemes</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="factorial-anova.html"><a href="factorial-anova.html"><i class="fa fa-check"></i><b>7</b> Factorial ANOVA</a>
<ul>
<li class="chapter" data-level="7.1" data-path="factorial-anova.html"><a href="factorial-anova.html#rainclouds-for-factorial-designs"><i class="fa fa-check"></i><b>7.1</b> Rainclouds for factorial designs</a></li>
<li class="chapter" data-level="7.2" data-path="factorial-anova.html"><a href="factorial-anova.html#formulating-estimating-and-testing-a-factorial-anova"><i class="fa fa-check"></i><b>7.2</b> Formulating, estimating, and testing a factorial ANOVA</a>
<ul>
<li class="chapter" data-level="7.2.1" data-path="factorial-anova.html"><a href="factorial-anova.html#a-threeway-anova"><i class="fa fa-check"></i><b>7.2.1</b> A threeway ANOVA</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="factorial-anova.html"><a href="factorial-anova.html#type-1-2-and-3-sums-of-squares"><i class="fa fa-check"></i><b>7.3</b> Type 1, 2, and 3 Sums of Squares</a></li>
<li class="chapter" data-level="7.4" data-path="factorial-anova.html"><a href="factorial-anova.html#planned-comparisons-and-post-hoc-tests-with-emmeans"><i class="fa fa-check"></i><b>7.4</b> Planned comparisons and post-hoc tests with <code>emmeans</code></a>
<ul>
<li class="chapter" data-level="7.4.1" data-path="factorial-anova.html"><a href="factorial-anova.html#adjusted-p-values"><i class="fa fa-check"></i><b>7.4.1</b> Adjusted p-values</a></li>
</ul></li>
<li class="chapter" data-level="7.5" data-path="factorial-anova.html"><a href="factorial-anova.html#testing-general-contrasts-with-emmeans"><i class="fa fa-check"></i><b>7.5</b> Testing general contrasts with <code>emmeans</code></a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="repeated-measures-anova.html"><a href="repeated-measures-anova.html"><i class="fa fa-check"></i><b>8</b> Repeated-measures ANOVA</a>
<ul>
<li class="chapter" data-level="8.1" data-path="repeated-measures-anova.html"><a href="repeated-measures-anova.html#long-and-wide-data"><i class="fa fa-check"></i><b>8.1</b> Long and wide data</a></li>
<li class="chapter" data-level="8.2" data-path="repeated-measures-anova.html"><a href="repeated-measures-anova.html#repeated-measures-anova-with-separate-glms"><i class="fa fa-check"></i><b>8.2</b> Repeated-measures ANOVA with separate GLMs</a>
<ul>
<li class="chapter" data-level="8.2.1" data-path="repeated-measures-anova.html"><a href="repeated-measures-anova.html#computing-within-subjects-composite-scores"><i class="fa fa-check"></i><b>8.2.1</b> Computing within-subjects composite scores</a></li>
<li class="chapter" data-level="8.2.2" data-path="repeated-measures-anova.html"><a href="repeated-measures-anova.html#performing-a-repeated-measures-anova-with-separate-models"><i class="fa fa-check"></i><b>8.2.2</b> Performing a repeated-measures ANOVA with separate models</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="repeated-measures-anova.html"><a href="repeated-measures-anova.html#repeated-measures-anova-with-the-car-package"><i class="fa fa-check"></i><b>8.3</b> Repeated-measures ANOVA with the <code>car</code> package</a></li>
<li class="chapter" data-level="8.4" data-path="repeated-measures-anova.html"><a href="repeated-measures-anova.html#repeated-measures-anova-with-the-afex-package"><i class="fa fa-check"></i><b>8.4</b> Repeated-measures ANOVA with the <code>afex</code> package</a></li>
<li class="chapter" data-level="8.5" data-path="repeated-measures-anova.html"><a href="repeated-measures-anova.html#contrasts-with-the-emmeans-package"><i class="fa fa-check"></i><b>8.5</b> Contrasts with the <code>emmeans</code> package</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="linear-mixed-effects-models.html"><a href="linear-mixed-effects-models.html"><i class="fa fa-check"></i><b>9</b> Linear mixed-effects models</a>
<ul>
<li class="chapter" data-level="9.1" data-path="linear-mixed-effects-models.html"><a href="linear-mixed-effects-models.html#formulating-and-estimating-linear-mixed-effects-models-with-lme4"><i class="fa fa-check"></i><b>9.1</b> Formulating and estimating linear mixed-effects models with <code>lme4</code></a>
<ul>
<li class="chapter" data-level="9.1.1" data-path="linear-mixed-effects-models.html"><a href="linear-mixed-effects-models.html#random-intercepts-model"><i class="fa fa-check"></i><b>9.1.1</b> Random intercepts model</a></li>
<li class="chapter" data-level="9.1.2" data-path="linear-mixed-effects-models.html"><a href="linear-mixed-effects-models.html#visually-assessing-model-assumptions"><i class="fa fa-check"></i><b>9.1.2</b> Visually assessing model assumptions</a></li>
<li class="chapter" data-level="9.1.3" data-path="linear-mixed-effects-models.html"><a href="linear-mixed-effects-models.html#random-intercepts-and-slopes"><i class="fa fa-check"></i><b>9.1.3</b> Random intercepts and slopes</a></li>
<li class="chapter" data-level="9.1.4" data-path="linear-mixed-effects-models.html"><a href="linear-mixed-effects-models.html#likelihood-ratio-test-with-the-anova-function"><i class="fa fa-check"></i><b>9.1.4</b> Likelihood ratio test with the <code>anova</code> function</a></li>
<li class="chapter" data-level="9.1.5" data-path="linear-mixed-effects-models.html"><a href="linear-mixed-effects-models.html#confidence-intervals"><i class="fa fa-check"></i><b>9.1.5</b> Confidence intervals</a></li>
<li class="chapter" data-level="9.1.6" data-path="linear-mixed-effects-models.html"><a href="linear-mixed-effects-models.html#plotting-model-predictions"><i class="fa fa-check"></i><b>9.1.6</b> Plotting model predictions</a></li>
</ul></li>
<li class="chapter" data-level="9.2" data-path="linear-mixed-effects-models.html"><a href="linear-mixed-effects-models.html#obtaining-p-values-with-afexmixed"><i class="fa fa-check"></i><b>9.2</b> Obtaining p-values with <code>afex::mixed</code></a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="bayesian-hypothesis-testing-through-bayes-factors.html"><a href="bayesian-hypothesis-testing-through-bayes-factors.html"><i class="fa fa-check"></i><b>10</b> Bayesian hypothesis testing through Bayes Factors</a>
<ul>
<li class="chapter" data-level="10.1" data-path="bayesian-hypothesis-testing-through-bayes-factors.html"><a href="bayesian-hypothesis-testing-through-bayes-factors.html#the-bayesfactor-package"><i class="fa fa-check"></i><b>10.1</b> The <code>BayesFactor</code> package</a>
<ul>
<li class="chapter" data-level="10.1.1" data-path="bayesian-hypothesis-testing-through-bayes-factors.html"><a href="bayesian-hypothesis-testing-through-bayes-factors.html#a-bayesian-one-sample-t-test"><i class="fa fa-check"></i><b>10.1.1</b> A Bayesian one-sample t-test</a></li>
<li class="chapter" data-level="10.1.2" data-path="bayesian-hypothesis-testing-through-bayes-factors.html"><a href="bayesian-hypothesis-testing-through-bayes-factors.html#a-bayesian-two-sample-t-test"><i class="fa fa-check"></i><b>10.1.2</b> A Bayesian two-sample t-test</a></li>
<li class="chapter" data-level="10.1.3" data-path="bayesian-hypothesis-testing-through-bayes-factors.html"><a href="bayesian-hypothesis-testing-through-bayes-factors.html#a-bayesian-anova"><i class="fa fa-check"></i><b>10.1.3</b> A Bayesian ANOVA</a></li>
<li class="chapter" data-level="10.1.4" data-path="bayesian-hypothesis-testing-through-bayes-factors.html"><a href="bayesian-hypothesis-testing-through-bayes-factors.html#bayesian-regression-and-ancova"><i class="fa fa-check"></i><b>10.1.4</b> Bayesian regression and ANCOVA</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="11" data-path="reproducible-reports-with-rmarkdown.html"><a href="reproducible-reports-with-rmarkdown.html"><i class="fa fa-check"></i><b>11</b> Reproducible reports with RMarkdown</a>
<ul>
<li class="chapter" data-level="11.1" data-path="reproducible-reports-with-rmarkdown.html"><a href="reproducible-reports-with-rmarkdown.html#yaml-headers"><i class="fa fa-check"></i><b>11.1</b> YAML headers</a></li>
<li class="chapter" data-level="11.2" data-path="reproducible-reports-with-rmarkdown.html"><a href="reproducible-reports-with-rmarkdown.html#markdown-syntax"><i class="fa fa-check"></i><b>11.2</b> Markdown syntax</a>
<ul>
<li class="chapter" data-level="11.2.1" data-path="reproducible-reports-with-rmarkdown.html"><a href="reproducible-reports-with-rmarkdown.html#inline-formatting"><i class="fa fa-check"></i><b>11.2.1</b> Inline formatting</a></li>
<li class="chapter" data-level="11.2.2" data-path="reproducible-reports-with-rmarkdown.html"><a href="reproducible-reports-with-rmarkdown.html#block-level-elements"><i class="fa fa-check"></i><b>11.2.2</b> Block-level elements</a></li>
<li class="chapter" data-level="11.2.3" data-path="reproducible-reports-with-rmarkdown.html"><a href="reproducible-reports-with-rmarkdown.html#math-expressions"><i class="fa fa-check"></i><b>11.2.3</b> Math expressions</a></li>
</ul></li>
<li class="chapter" data-level="11.3" data-path="reproducible-reports-with-rmarkdown.html"><a href="reproducible-reports-with-rmarkdown.html#r-code"><i class="fa fa-check"></i><b>11.3</b> R code chunks and inline R code</a>
<ul>
<li class="chapter" data-level="11.3.1" data-path="reproducible-reports-with-rmarkdown.html"><a href="reproducible-reports-with-rmarkdown.html#figures"><i class="fa fa-check"></i><b>11.3.1</b> Figures</a></li>
<li class="chapter" data-level="11.3.2" data-path="reproducible-reports-with-rmarkdown.html"><a href="reproducible-reports-with-rmarkdown.html#tables"><i class="fa fa-check"></i><b>11.3.2</b> Tables</a></li>
</ul></li>
<li class="chapter" data-level="11.4" data-path="reproducible-reports-with-rmarkdown.html"><a href="reproducible-reports-with-rmarkdown.html#apa-documents-with-papaja"><i class="fa fa-check"></i><b>11.4</b> APA documents with <code>papaja</code></a>
<ul>
<li class="chapter" data-level="11.4.1" data-path="reproducible-reports-with-rmarkdown.html"><a href="reproducible-reports-with-rmarkdown.html#installation"><i class="fa fa-check"></i><b>11.4.1</b> Installation</a></li>
<li class="chapter" data-level="11.4.2" data-path="reproducible-reports-with-rmarkdown.html"><a href="reproducible-reports-with-rmarkdown.html#how-to-use-papaja"><i class="fa fa-check"></i><b>11.4.2</b> How to use papaja</a></li>
<li class="chapter" data-level="11.4.3" data-path="reproducible-reports-with-rmarkdown.html"><a href="reproducible-reports-with-rmarkdown.html#getting-help-1"><i class="fa fa-check"></i><b>11.4.3</b> Getting help</a></li>
<li class="chapter" data-level="11.4.4" data-path="reproducible-reports-with-rmarkdown.html"><a href="reproducible-reports-with-rmarkdown.html#other-related-r-packages"><i class="fa fa-check"></i><b>11.4.4</b> Other related R packages</a></li>
</ul></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">An R companion to Statistics: data analysis and modelling</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="linear-mixed-effects-models" class="section level1" number="9">
<h1><span class="header-section-number">Chapter 9</span> Linear mixed-effects models</h1>
<p>In this Chapter, we will look at how to estimate and perform hypothesis tests for linear mixed-effects models. The main workhorse for estimating linear mixed-effects models is the <code>lme4</code> package. This package allows you to formulate a wide variety of mixed-effects and multilevel models through an extension of the R formula syntax. It is a really good package. But the main author of the package, Douglas Bates, has chosen not to provide <span class="math inline">\(p\)</span>-values for the model parameters. We will therefore also consider the <code>afex</code> package, which provides an interface to the two main approximations (Kenward-Roger and Satterthwaite) to provide the degrees of freedom to compute <span class="math inline">\(p\)</span>-values for <span class="math inline">\(F\)</span> tests. While the <code>mixed</code> function it provides is in principle all you need to estimate the models <em>and</em> get the estimates, I think it is useful to also understand the underlying <code>lme4</code> package <span class="citation">(<a href="#ref-R-lme4" role="doc-biblioref">Bates et al. 2021</a>)</span>, so we will start with a discussion of this, and then move to the <code>afex</code> package <span class="citation">(<a href="#ref-R-afex" role="doc-biblioref">Singmann et al. 2021</a>)</span>. If you install the <code>afex</code> package, it will install quite a few other packages on which it relies. So to get all the required packages for this chapter, you can just type</p>
<div class="sourceCode" id="cb387"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb387-1"><a href="linear-mixed-effects-models.html#cb387-1" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">&quot;afex&quot;</span>)</span></code></pre></div>
<p>In the R package, and you should have everything you need.</p>
<div id="formulating-and-estimating-linear-mixed-effects-models-with-lme4" class="section level2" number="9.1">
<h2><span class="header-section-number">9.1</span> Formulating and estimating linear mixed-effects models with <code>lme4</code></h2>
<p>The gold standard for fitting linear mixed-effects models in R is the <code>lmer()</code> (for <code>l</code>inear <code>m</code>ixed-<code>e</code>ffects <code>r</code>egression) in the <code>lme4</code> package. This function takes the following arguments (amongst others, for the full list of arguments, see <code>?lmer</code>):</p>
<ul>
<li><code>formula</code>: a two-sided linear formula describing both the fixed-effects and random-effects part of the model, with the response on the left of the <code>~</code> operator and predictors and random effects on the right-hand side of the <code>~</code> operator.</li>
<li><code>data</code>: A <code>data.frame</code>, which needs to be in the so-called “long” format, with a single row per observation. This may be different from what you might be used to when dealing with repeated-measures. A repeated-measures ANOVA in SPSS requires data in the “wide” format, where you use columns for the different repeated measures. Data in the “wide” format has a single row for each participants. In the “long” format, you will have multiple rows for the data from a single grouping level (e.g., participant, lab, etc.).<br />
</li>
<li><code>REML</code>: A logical variable whether to estimate the model with restricted maximum likelihood (<code>REML = TRUE</code>, the default) or with maximum likelihood (<code>REML = FALSE</code>).</li>
</ul>
<p>As correct use of the formula interface is vital, let’s first consider again how the formula interface works in general. Formulas allow you to specify a linear model succinctly (and by default, any model created with a formula will include an intercept, unless explicitly removed). Here are some examples (adapted from <span class="citation"><a href="#ref-Singmann2019-mixed" role="doc-biblioref">Singmann and Kellen</a> (<a href="#ref-Singmann2019-mixed" role="doc-biblioref">2019</a>)</span>):</p>
<table>
<colgroup>
<col width="12%" />
<col width="88%" />
</colgroup>
<thead>
<tr class="header">
<th>Formula</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>a + b</code></td>
<td>main effects of <code>a</code> and <code>b</code> (and no interaction)</td>
</tr>
<tr class="even">
<td><code>a:b</code></td>
<td>only interaction of <code>a</code> and <code>b</code> (and no main effects)</td>
</tr>
<tr class="odd">
<td><code>a * b</code></td>
<td>main effects and interaction of <code>a</code> and <code>b</code> (expands to: <code>a + b + a:b</code>)</td>
</tr>
<tr class="even">
<td><code>(a+b+c)^2</code></td>
<td>main effects and two-way interactions, but no three-way interaction (expands to: <code>a + b + c + a:b + b:c + a:c</code>)</td>
</tr>
<tr class="odd">
<td><code>(a+b)*c</code></td>
<td>all main effects and pairwise interactions between <code>c</code> and <code>a</code> or <code>b</code> (expands to: <code>a + b + c + a:c + b:c</code>)</td>
</tr>
<tr class="even">
<td><code>0 + a</code></td>
<td><code>0</code> suppresses the intercept resulting in a model that has one parameter per level of <code>a</code> (identical to: <code>a - 1</code>)</td>
</tr>
</tbody>
</table>
<p>The <code>lme4</code> package extends the formula interface to specify random effects structures. Random effects are added to the formula by writing elements between parentheses <code>()</code>. Within these parentheses, you provide the specification of the random effects to be included on the left-hand side of a conditional sign <code>|</code>. On the right-hand side of the sign, you specify the grouping factor, or grouping factors, on which these random effects depend. The grouping factors _need to be of class <code>factor</code>__ (i.e., they can __not_ be numeric variables). Here are some examples of such specifications (again adapted from <span class="citation"><a href="#ref-Singmann2019-mixed" role="doc-biblioref">Singmann and Kellen</a> (<a href="#ref-Singmann2019-mixed" role="doc-biblioref">2019</a>)</span>):</p>
<table>
<colgroup>
<col width="12%" />
<col width="88%" />
</colgroup>
<thead>
<tr class="header">
<th>Formula</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>(1|s)</code></td>
<td>random intercepts for unique level of the factor <code>s</code></td>
</tr>
<tr class="even">
<td><code>(1|s) + (1|i)</code></td>
<td>random intercepts for each unique level of <code>s</code> and for each unique level of <code>i</code></td>
</tr>
<tr class="odd">
<td><code>(a|s)</code></td>
<td>random intercepts and random slopes for <code>a</code>, for each level of <code>s</code>. Correlations between the intercept and slope effects are also estimated. (identical to <code>(a*b|s)</code>)</td>
</tr>
<tr class="even">
<td><code>(a*b|s)</code></td>
<td>random intercepts and slopes for <code>a</code>, <code>b</code>, and the <code>a:b</code> interaction, for each level of <code>s</code>. Correlations between all the random effects are estimated.</td>
</tr>
</tbody>
</table>
<p><code>(0+a|s)</code> | random slopes for <code>a</code> for each level of <code>s</code>, but no random intercepts
<code>(a||s)</code> | random intercepts and random slopes for <code>a</code>, for each level of <code>s</code>, but no correlations between the random effects (i.e. they are set to 0). This expands to: <code>(0+a|s) + (1|s)</code>)
<code>0 + a</code> | <code>0</code> suppresses the intercept resulting in a model that has one parameter per level of <code>a</code></p>
<div id="random-intercepts-model" class="section level3" number="9.1.1">
<h3><span class="header-section-number">9.1.1</span> Random intercepts model</h3>
<p>Now let’s try to define a relatively simple linear mixed-effects model for the <code>anchoring</code> data set in the <code>sdamr</code> package. We will use the data from all the <code>referrers</code> try a few variations to get acquinted with the <code>lmer()</code> function. First, let’s load the packages and the data:</p>
<div class="sourceCode" id="cb388"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb388-1"><a href="linear-mixed-effects-models.html#cb388-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sdamr)</span>
<span id="cb388-2"><a href="linear-mixed-effects-models.html#cb388-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lme4)</span>
<span id="cb388-3"><a href="linear-mixed-effects-models.html#cb388-3" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">&quot;anchoring&quot;</span>)</span></code></pre></div>
<p>Now let’s estimate a first linear mixed-effects model, with a fixed effect for anchor, and random intercepts, using <code>everest_feet</code> as the dependent variable. We will first ensure that <code>anchor</code> is a factor and associate a sum-to-zero contrast to it. We will also make <code>referrer</code> a factor; the contrast for this shouldn’t really matter, so we’ll leave it as a dummy code. We then set up the model, using <code>(1|referrer)</code> to specify that random intercept-effects should be included for each level of the <code>referrer</code> factor. Finally, we use the <code>summary()</code> function on the estimated model to obtain the estimates of the parameters.</p>
<div class="sourceCode" id="cb389"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb389-1"><a href="linear-mixed-effects-models.html#cb389-1" aria-hidden="true" tabindex="-1"></a>anchoring<span class="sc">$</span>anchor <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(anchoring<span class="sc">$</span>anchor)</span>
<span id="cb389-2"><a href="linear-mixed-effects-models.html#cb389-2" aria-hidden="true" tabindex="-1"></a><span class="fu">contrasts</span>(anchoring<span class="sc">$</span>anchor) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span><span class="sc">/</span><span class="dv">2</span>, <span class="sc">-</span><span class="dv">1</span><span class="sc">/</span><span class="dv">2</span>) <span class="co"># alphabetical order, so high before low</span></span>
<span id="cb389-3"><a href="linear-mixed-effects-models.html#cb389-3" aria-hidden="true" tabindex="-1"></a><span class="co"># define a lmer</span></span>
<span id="cb389-4"><a href="linear-mixed-effects-models.html#cb389-4" aria-hidden="true" tabindex="-1"></a>mod <span class="ot">&lt;-</span> <span class="fu">lmer</span>(everest_feet <span class="sc">~</span> anchor <span class="sc">+</span> (<span class="dv">1</span><span class="sc">|</span>referrer), <span class="at">data=</span>anchoring)</span>
<span id="cb389-5"><a href="linear-mixed-effects-models.html#cb389-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod)</span></code></pre></div>
<pre><code>## Linear mixed model fit by REML. t-tests use Satterthwaite&#39;s method [&#39;lmerModLmerTest&#39;]
## Formula: everest_feet ~ anchor + (1 | referrer)
##    Data: anchoring
## 
## REML criterion at convergence: 98195.5
## 
## Scaled residuals: 
##     Min      1Q  Median      3Q     Max 
## -3.4433 -0.7178 -0.1361  0.7419  3.5546 
## 
## Random effects:
##  Groups   Name        Variance Std.Dev.
##  referrer (Intercept)  2717134 1648    
##  Residual             93929988 9692    
## Number of obs: 4632, groups:  referrer, 31
## 
## Fixed effects:
##             Estimate Std. Error       df t value Pr(&gt;|t|)    
## (Intercept) 22788.30     346.85    29.17   65.70   &lt;2e-16 ***
## anchor1     23047.34     285.80  4617.54   80.64   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Correlation of Fixed Effects:
##         (Intr)
## anchor1 0.022</code></pre>
<p>The output first shows some information about the structure of the model, and the value of the optimized “-2 log REML” (the logarithm of the minus two restricted maximum likelihood). Then some summary statistics for the <em>standardized residuals</em> are shown (these are the “raw” residuals divided by the estimated standard deviation of the residuals).</p>
<p>Under the <code>Random effects:</code> header, you will find a table with estimates of the variance and standard deviation of the random effects terms for each grouping factor (just <code>referrer</code> in this case). So the estimated standard deviation of the random intercept: <span class="math inline">\(\hat{\sigma}_{\gamma_0} = 1648\)</span>. You will also find an estimate of the variance and standard deviation of the residuals in this table: <span class="math inline">\(\hat{\sigma}_\epsilon = 9692\)</span>}.</p>
<p>Under the <code>Fixed effects:</code> header, you will find a table with an estimate for each fixed effect, as well as the standard error of this estimate, and an associated <span class="math inline">\(t\)</span> statistic. This output is much like the output of calling the <code>summary()</code> function on a standard model estimated with the <code>lm</code> function. But you won’t find the <span class="math inline">\(p\)</span>-value for these estimates. This is because the author of the <code>lme4</code> package, perhaps rightly, finds none of the approximations to the error degrees of freedom good enough for general usage. Opinions on this will vary. It is agreed that the true Type 1 error rate when using one of the approximations will not be exactly equal to the <span class="math inline">\(\alpha\)</span> level. In some cases, the difference may be substantial, but often the approximation will be reasonable enough to be useful in practice. For further information on this, there is a section in a very useful <a href="https://bbolker.github.io/mixedmodels-misc/glmmFAQ.html#why-doesnt-lme4-display-denominator-degrees-of-freedomp-values-what-other-options-do-i-have">GLMM FAQ</a>. You can also see <code>?lme4::pvalues</code> for some information about various approaches to obtaining <span class="math inline">\(p\)</span>-values.</p>
<p>The final table, under the <code>Correlation of Fixed Effects</code>, shows the approximate correlation between the estimators of the fixed effects. You can think of it as the expected correlation between the estimates of the fixed effects over all different datasets that you might obtain (assuming that the predictors have the same values in each). It is not something you generally need to be concerned about.</p>
</div>
<div id="visually-assessing-model-assumptions" class="section level3" number="9.1.2">
<h3><span class="header-section-number">9.1.2</span> Visually assessing model assumptions</h3>
<p>You can use the <code>predict</code> and <code>residuals</code> function to obtain the predicted values and residuals for a linear mixed effects model. You can then plot these, using e.g. <code>ggplot2</code>, as follows:</p>
<div class="sourceCode" id="cb391"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb391-1"><a href="linear-mixed-effects-models.html#cb391-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb391-2"><a href="linear-mixed-effects-models.html#cb391-2" aria-hidden="true" tabindex="-1"></a>tdat <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">predicted=</span><span class="fu">predict</span>(mod), <span class="at">residual =</span> <span class="fu">residuals</span>(mod))</span>
<span id="cb391-3"><a href="linear-mixed-effects-models.html#cb391-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(tdat,<span class="fu">aes</span>(<span class="at">x=</span>predicted,<span class="at">y=</span>residual)) <span class="sc">+</span> <span class="fu">geom_point</span>() <span class="sc">+</span> <span class="fu">geom_hline</span>(<span class="at">yintercept=</span><span class="dv">0</span>, <span class="at">lty=</span><span class="dv">3</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-227-1.svg" width="672" style="display: block; margin: auto;" /></p>
<p>It might be cool to colour the residuals by referrer as follows:</p>
<div class="sourceCode" id="cb392"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb392-1"><a href="linear-mixed-effects-models.html#cb392-1" aria-hidden="true" tabindex="-1"></a>tdat <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">predicted=</span><span class="fu">predict</span>(mod), <span class="at">residual =</span> <span class="fu">residuals</span>(mod), <span class="at">referrer=</span>anchoring<span class="sc">$</span>referrer)</span>
<span id="cb392-2"><a href="linear-mixed-effects-models.html#cb392-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(tdat,<span class="fu">aes</span>(<span class="at">x=</span>predicted,<span class="at">y=</span>residual, <span class="at">colour=</span>referrer)) <span class="sc">+</span> <span class="fu">geom_point</span>() <span class="sc">+</span> <span class="fu">geom_hline</span>(<span class="at">yintercept=</span><span class="dv">0</span>, <span class="at">lty=</span><span class="dv">3</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-228-1.svg" width="672" style="display: block; margin: auto;" />
If the legend gets in the way, you can turn it off as follows:</p>
<div class="sourceCode" id="cb393"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb393-1"><a href="linear-mixed-effects-models.html#cb393-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(tdat,<span class="fu">aes</span>(<span class="at">x=</span>predicted,<span class="at">y=</span>residual, <span class="at">colour=</span>referrer)) <span class="sc">+</span> <span class="fu">geom_point</span>() <span class="sc">+</span> <span class="fu">geom_hline</span>(<span class="at">yintercept=</span><span class="dv">0</span>, <span class="at">lty=</span><span class="dv">3</span>) <span class="sc">+</span> <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">&quot;none&quot;</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-229-1.svg" width="672" style="display: block; margin: auto;" />
The <code>theme</code> function allows for lots of functionality (check <code>?theme</code>). You can also get a quick predicted vs residual plot by simply calling <code>plot(mod)</code>.</p>
<p>We can get a histogram of the residuals, and a QQ plot, as follows:</p>
<div class="sourceCode" id="cb394"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb394-1"><a href="linear-mixed-effects-models.html#cb394-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(tdat,<span class="fu">aes</span>(<span class="at">x=</span>residual)) <span class="sc">+</span> <span class="fu">geom_histogram</span>(<span class="at">bins=</span><span class="dv">20</span>, <span class="at">color=</span><span class="st">&quot;black&quot;</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-230-1.svg" width="672" style="display: block; margin: auto;" /></p>
<div class="sourceCode" id="cb395"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb395-1"><a href="linear-mixed-effects-models.html#cb395-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(tdat,<span class="fu">aes</span>(<span class="at">sample=</span>residual)) <span class="sc">+</span> <span class="fu">stat_qq</span>() <span class="sc">+</span> <span class="fu">stat_qq_line</span>()</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-230-2.svg" width="672" style="display: block; margin: auto;" /></p>
</div>
<div id="random-intercepts-and-slopes" class="section level3" number="9.1.3">
<h3><span class="header-section-number">9.1.3</span> Random intercepts and slopes</h3>
<p>Now let’s estimate a model with random intercepts and random slopes for <code>anchor</code>. To do so, we can simply add <code>anchor</code> in the mixed effects structure specification, as follows:</p>
<div class="sourceCode" id="cb396"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb396-1"><a href="linear-mixed-effects-models.html#cb396-1" aria-hidden="true" tabindex="-1"></a>modg <span class="ot">&lt;-</span> <span class="fu">lmer</span>(everest_feet <span class="sc">~</span> anchor <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">+</span> anchor<span class="sc">|</span>referrer), <span class="at">data=</span>anchoring)</span>
<span id="cb396-2"><a href="linear-mixed-effects-models.html#cb396-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modg)</span></code></pre></div>
<pre><code>## Linear mixed model fit by REML. t-tests use Satterthwaite&#39;s method [&#39;lmerModLmerTest&#39;]
## Formula: everest_feet ~ anchor + (1 + anchor | referrer)
##    Data: anchoring
## 
## REML criterion at convergence: 97944.4
## 
## Scaled residuals: 
##     Min      1Q  Median      3Q     Max 
## -3.5558 -0.6374 -0.1029  0.6551  3.8431 
## 
## Random effects:
##  Groups   Name        Variance Std.Dev. Corr 
##  referrer (Intercept)  2470481 1572          
##           anchor1     36036021 6003     -0.80
##  Residual             87887265 9375          
## Number of obs: 4632, groups:  referrer, 31
## 
## Fixed effects:
##             Estimate Std. Error       df t value Pr(&gt;|t|)    
## (Intercept) 22840.77     329.42    27.49   69.34   &lt;2e-16 ***
## anchor1     23578.76    1138.95    27.32   20.70   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Correlation of Fixed Effects:
##         (Intr)
## anchor1 -0.658</code></pre>
<p>As you can see, the model now estimates a variance of the random slopes effects, as well as a correlation between the random intercept and slope effects. We could try to get a model without the correlations as follows:</p>
<div class="sourceCode" id="cb398"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb398-1"><a href="linear-mixed-effects-models.html#cb398-1" aria-hidden="true" tabindex="-1"></a>modr <span class="ot">&lt;-</span> <span class="fu">lmer</span>(everest_feet <span class="sc">~</span> anchor <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">+</span> anchor<span class="sc">||</span>referrer), <span class="at">data=</span>anchoring)</span></code></pre></div>
<p>As you can see in the warning messages, this leads to various estimation issues. Moreover, the correlation is actually still there!</p>
<div class="sourceCode" id="cb399"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb399-1"><a href="linear-mixed-effects-models.html#cb399-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modr)</span></code></pre></div>
<pre><code>## Linear mixed model fit by REML. t-tests use Satterthwaite&#39;s method [&#39;lmerModLmerTest&#39;]
## Formula: everest_feet ~ anchor + (1 + anchor || referrer)
##    Data: anchoring
## 
## REML criterion at convergence: 97944.4
## 
## Scaled residuals: 
##     Min      1Q  Median      3Q     Max 
## -3.5558 -0.6374 -0.1029  0.6551  3.8431 
## 
## Random effects:
##  Groups     Name        Variance Std.Dev. Corr 
##  referrer   (Intercept)    72369  269          
##  referrer.1 anchorhigh   3835401 1958          
##             anchorlow   18979098 4357     -0.77
##  Residual               87887261 9375          
## Number of obs: 4632, groups:  referrer, 31
## 
## Fixed effects:
##             Estimate Std. Error       df t value Pr(&gt;|t|)    
## (Intercept) 22840.77     329.41    27.49   69.34   &lt;2e-16 ***
## anchor1     23578.76    1138.97    27.32   20.70   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Correlation of Fixed Effects:
##         (Intr)
## anchor1 -0.658
## optimizer (nloptwrap) convergence code: 0 (OK)
## unable to evaluate scaled gradient
## Model failed to converge: degenerate  Hessian with 1 negative eigenvalues</code></pre>
<p>As it turns out, the <code>||</code> notation <strong>does not work with factors</strong>!. It only works with metric predictors. We can get the desired model by defining a contrast-coding predictor for <code>anchor</code> explicitly, as follows:</p>
<div class="sourceCode" id="cb401"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb401-1"><a href="linear-mixed-effects-models.html#cb401-1" aria-hidden="true" tabindex="-1"></a>anchoring<span class="sc">$</span>anchor_contrast <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">/</span><span class="dv">2</span></span>
<span id="cb401-2"><a href="linear-mixed-effects-models.html#cb401-2" aria-hidden="true" tabindex="-1"></a>anchoring<span class="sc">$</span>anchor_contrast[anchoring<span class="sc">$</span>anchor <span class="sc">==</span> <span class="st">&quot;low&quot;</span>] <span class="ot">&lt;-</span> <span class="sc">-</span><span class="dv">1</span><span class="sc">/</span><span class="dv">2</span></span>
<span id="cb401-3"><a href="linear-mixed-effects-models.html#cb401-3" aria-hidden="true" tabindex="-1"></a>modr <span class="ot">&lt;-</span> <span class="fu">lmer</span>(everest_feet <span class="sc">~</span> anchor_contrast <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">+</span> anchor_contrast<span class="sc">||</span>referrer), <span class="at">data=</span>anchoring)</span>
<span id="cb401-4"><a href="linear-mixed-effects-models.html#cb401-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modr)</span></code></pre></div>
<pre><code>## Linear mixed model fit by REML. t-tests use Satterthwaite&#39;s method [&#39;lmerModLmerTest&#39;]
## Formula: everest_feet ~ anchor_contrast + (1 + anchor_contrast || referrer)
##    Data: anchoring
## 
## REML criterion at convergence: 97960.2
## 
## Scaled residuals: 
##     Min      1Q  Median      3Q     Max 
## -3.6330 -0.6464 -0.1011  0.6732  3.8333 
## 
## Random effects:
##  Groups     Name            Variance Std.Dev.
##  referrer   (Intercept)      2350312 1533    
##  referrer.1 anchor_contrast 36126381 6011    
##  Residual                   87899463 9375    
## Number of obs: 4632, groups:  referrer, 31
## 
## Fixed effects:
##                 Estimate Std. Error       df t value Pr(&gt;|t|)    
## (Intercept)     22773.65     326.69    29.08   69.71   &lt;2e-16 ***
## anchor_contrast 23526.08    1141.84    28.22   20.60   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Correlation of Fixed Effects:
##             (Intr)
## anchr_cntrs 0.011</code></pre>
<p>That is a little annoying, especially if you have a factor with lots of levels, in which case you would have to specify a lot of contrast-coding predictors. The <code>lmer_alt()</code> function in the <code>afex</code> package will automatically generate the contrast-coding predictors needed, which will be convenient. You can try this by running:</p>
<div class="sourceCode" id="cb403"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb403-1"><a href="linear-mixed-effects-models.html#cb403-1" aria-hidden="true" tabindex="-1"></a>modr <span class="ot">&lt;-</span> afex<span class="sc">::</span><span class="fu">lmer_alt</span>(everest_feet <span class="sc">~</span> anchor <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">+</span> anchor<span class="sc">||</span>referrer), <span class="at">set_data_arg =</span> <span class="cn">TRUE</span>, <span class="at">data=</span>anchoring)</span>
<span id="cb403-2"><a href="linear-mixed-effects-models.html#cb403-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modr)</span></code></pre></div>
<pre><code>## Linear mixed model fit by REML. t-tests use Satterthwaite&#39;s method [&#39;lmerModLmerTest&#39;]
## Formula: everest_feet ~ anchor + (1 + re1.anchor1 || referrer)
##    Data: anchoring
## 
## REML criterion at convergence: 97960.2
## 
## Scaled residuals: 
##     Min      1Q  Median      3Q     Max 
## -3.6330 -0.6464 -0.1011  0.6732  3.8333 
## 
## Random effects:
##  Groups     Name        Variance Std.Dev.
##  referrer   (Intercept)  2350312 1533    
##  referrer.1 re1.anchor1 36126381 6011    
##  Residual               87899463 9375    
## Number of obs: 4632, groups:  referrer, 31
## 
## Fixed effects:
##             Estimate Std. Error       df t value Pr(&gt;|t|)    
## (Intercept) 22773.65     326.69    29.08   69.71   &lt;2e-16 ***
## anchor1     23526.08    1141.84    28.22   20.60   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Correlation of Fixed Effects:
##         (Intr)
## anchor1 0.011</code></pre>
<p>Note the use of the additional <code>set_data_arg = TRUE</code> argument, which is necessary to later use the object for model comparisons with the likelihood ratio test in the next section. Also note that the parameters now do come with <span class="math inline">\(p\)</span>-values (using the Satterthwaite approximation).</p>
</div>
<div id="likelihood-ratio-test-with-the-anova-function" class="section level3" number="9.1.4">
<h3><span class="header-section-number">9.1.4</span> Likelihood ratio test with the <code>anova</code> function</h3>
<p>We now have two versions of our random intercepts + slopes model, one which estimates the correlation between the random intercept and slope, and one which sets this to 0. A likelihood-ratio test comparing these two models is easily obtained as:</p>
<div class="sourceCode" id="cb405"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb405-1"><a href="linear-mixed-effects-models.html#cb405-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(modr,modg)</span></code></pre></div>
<pre><code>## Data: anchoring
## Models:
## modr: everest_feet ~ anchor + (1 + re1.anchor1 || referrer)
## modg: everest_feet ~ anchor + (1 + anchor | referrer)
##      npar   AIC   BIC logLik deviance  Chisq Df Pr(&gt;Chisq)    
## modr    5 98000 98032 -48995    97990                         
## modg    6 97985 98024 -48987    97973 16.339  1  5.296e-05 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Note the message <code>refitting model(s) with ML (instead of REML)</code>. The likelihood-ratio test requires that the models are estimated by maximum likelihood, rather than restricted maximum likelihood (REML). The <code>lme4</code> package is clever enough to realize this, and first re-estimates the model before computing the likelihood ratio test. Also note that the test statistic is now called “Chisq,” for Chi-squared. This is the one we want. The test result is significant, and hence we can reject the null hypothesis that the correlation between the random intercept and slope is <span class="math inline">\(\rho_{\gamma_0,\gamma_1} = 0\)</span>.</p>
</div>
<div id="confidence-intervals" class="section level3" number="9.1.5">
<h3><span class="header-section-number">9.1.5</span> Confidence intervals</h3>
<p>While the <code>lme4</code> package does not provide <span class="math inline">\(p\)</span>-values, it does have functionality to compute confidence intervals via the <code>confint()</code> function. The default option is to compute so-called profile likelihood confidence intervals for all (fixed and random) parameters:</p>
<div class="sourceCode" id="cb407"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb407-1"><a href="linear-mixed-effects-models.html#cb407-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(modg)</span></code></pre></div>
<pre><code>##                    2.5 %        97.5 %
## .sig01       1083.558297  2187.2825617
## .sig02         -0.956541    -0.5042915
## .sig03       4471.113419  7999.4737204
## .sigma       9185.991570  9570.4663804
## (Intercept) 22184.246089 23499.3202067
## anchor1     21298.714977 25838.8350190</code></pre>
<p>Note that <code>.sig01</code> refers to the standard deviation of the random intercept (i.e. <span class="math inline">\(\sigma{\gamma_0}\)</span>), <code>.sig02</code> refers to the correlation between the random intercept and random slope (i.e. <span class="math inline">\(\rho_{\gamma_0,\gamma_1}\)</span>), and <code>.sig03</code> to the standard deviation of the random slope (i.e. <span class="math inline">\(\sigma_{\gamma_1}\)</span>). The value of <code>.sig</code> refers to the standard deviation of the error term (i.e. <span class="math inline">\(\sigma_\epsilon\)</span>). Unfortunately, these are not the most informative labels, so it pays to check the values reported in <code>summary(modg)</code> to match them to the output here.</p>
<p>Parametric bootstrap confidence (via simulation) can be obtained by setting the argument <code>method = "boot"</code>. This is a very computationally intensive procedure, so you will have to wait some time for the results! Moreover, due to the random simulation involved, the results will vary (hopefully a little) every time you run the procedure:</p>
<div class="sourceCode" id="cb409"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb409-1"><a href="linear-mixed-effects-models.html#cb409-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">20201201</span>)</span>
<span id="cb409-2"><a href="linear-mixed-effects-models.html#cb409-2" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(modg, <span class="at">method=</span><span class="st">&quot;boot&quot;</span>)</span></code></pre></div>
<pre><code>##                 2.5 %        97.5 %
## .sig01       1041.469  2111.5327662
## .sig02         -1.000    -0.5192476
## .sig03       4369.214  7716.5436429
## .sigma       9171.071  9573.5222532
## (Intercept) 22138.746 23535.5279557
## anchor1     21366.564 26111.6466861</code></pre>
<div class="sourceCode" id="cb411"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb411-1"><a href="linear-mixed-effects-models.html#cb411-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(modg, <span class="at">method=</span><span class="st">&quot;boot&quot;</span>)</span></code></pre></div>
<pre><code>##                     2.5 %        97.5 %
## .sig01       1045.6131551  2151.4335327
## .sig02         -0.9976517    -0.5486075
## .sig03       4296.8794715  7695.7776431
## .sigma       9164.6786544  9584.8451898
## (Intercept) 22141.6525509 23504.3587997
## anchor1     21047.7038556 25819.4349753</code></pre>
<p>Note the warning messages. By default, the bootstrap simulates <code>nsim=500</code> datasets and re-estimates the model for each. In some of the simulated datasets, the estimation may fail, which provides the resulting warning messages. While confidence intervals and hypothesis tests, in the case of “standard” linear models give the same results, this is not necessarily the case for mixed models, as the <span class="math inline">\(F\)</span> tests for the fixed effects involve approximation of the error degrees of freedom (<span class="math inline">\(\text{df}_2\)</span>), whilst the computation of the confidence intervals rely on other forms of approximation (e.g. simulation for the parametric bootstrap). As confidence intervals are included by default in <code>lme4</code>, it seems like the author of the package believes these are perhaps more principled than the <span class="math inline">\(F\)</span> tests for the fixed effects.</p>
</div>
<div id="plotting-model-predictions" class="section level3" number="9.1.6">
<h3><span class="header-section-number">9.1.6</span> Plotting model predictions</h3>
<p>It can be useful to plot the model predictions for each level of the random grouping factor. We can obtain such a plot by storing the model predictions with the data. By adding the <code>group =</code> and <code>colour =</code> arguments in the <code>aes()</code> function, you can then get separate results for all levels of the random effect factor (<code>referrer</code> here). For instance, we can plot the predictions for the different levels of the <code>anchor</code> factor with connecting lines as follows:</p>
<div class="sourceCode" id="cb413"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb413-1"><a href="linear-mixed-effects-models.html#cb413-1" aria-hidden="true" tabindex="-1"></a>anchoring<span class="sc">$</span>pred <span class="ot">&lt;-</span> <span class="fu">predict</span>(modg)</span>
<span id="cb413-2"><a href="linear-mixed-effects-models.html#cb413-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(anchoring,<span class="fu">aes</span>(<span class="at">x=</span>anchor,<span class="at">y=</span>pred,<span class="at">colour=</span>referrer, <span class="at">group=</span>referrer)) <span class="sc">+</span> <span class="fu">geom_point</span>() <span class="sc">+</span> <span class="fu">geom_line</span>() <span class="sc">+</span> <span class="fu">theme</span>(<span class="at">legend.position=</span><span class="st">&quot;bottom&quot;</span>, <span class="at">legend.direction =</span> <span class="st">&quot;horizontal&quot;</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-238-1.svg" width="720" style="display: block; margin: auto;" /></p>
<p>This would also work if the variable of the x-axis is continuous, rather than categorical.</p>
</div>
</div>
<div id="obtaining-p-values-with-afexmixed" class="section level2" number="9.2">
<h2><span class="header-section-number">9.2</span> Obtaining p-values with <code>afex::mixed</code></h2>
<p>Despite some of the concerns about the validity of the <span class="math inline">\(p\)</span>-values for <span class="math inline">\(F\)</span>-tests of the fixed effects, they are often useful (if only to satisfy reviewers of your paper). Packages such as <code>pbkrtest</code> <span class="citation">(<a href="#ref-R-pbkrtest" role="doc-biblioref">Højsgaard 2020</a>)</span> and <code>lmerTest</code> <span class="citation">(<a href="#ref-R-lmerTest" role="doc-biblioref">Kuznetsova, Bruun Brockhoff, and Haubo Bojesen Christensen 2020</a>)</span> have been developed to provide these for mixed-effects models estimated with the <code>lmer()</code> function, using the Kenward-Roger or parametric bootstrap, and Satterthwaite approximations, respectively. The <code>afex</code> package <span class="citation">(<a href="#ref-R-afex" role="doc-biblioref">Singmann et al. 2021</a>)</span> provides a common interface to the functionality of these packages, via its <code>mixed</code> function. The <code>mixed</code> function offers some other convenient features, such as automatically using sum-to-zero contrasts (via <code>contr.sum()</code>), although I prefer setting my own contrasts and turn this off.</p>
<p>Some of the main arguments to the <code>mixed</code> function (see <code>?mixed</code> for the full overview) are:</p>
<ul>
<li><code>formula</code>: a two-sided linear formula describing both the fixed-effects and random-effects part of the model, with the response on the left of the <code>~</code> operator and predictors and random effects on the right-hand side of the <code>~</code> operator.</li>
<li><code>data</code>: A <code>data.frame</code>, which needs to be in the so-called “long” format, with a single row per observation. This may be different from what you might be used to when dealing with repeated-measures. A repeated-measures ANOVA in SPSS requires data in the “wide” format, where you use columns for the different repeated measures. Data in the “wide” format has a single row for each participants. In the “long” format, you will have multiple rows for the data from a single grouping level (e.g., participant, lab, etc.).<br />
</li>
<li><code>type</code>: Sums of Squares type to use (1, 2, or 3). Default is 3.</li>
<li><code>method</code>: Character vector indicating which approximation method to use for obtaining the p-values. <code>"KR"</code> for the Kenward-Roger approximation (default), <code>"S"</code> for the Satterthwaite approximation, <code>"PB"</code> for a parametric bootstrap, and <code>"LRT"</code> for the likelihood ratio test.</li>
<li><code>test_intercept</code>: Logical variable indicating whether to obtain a test of the fixed intercept (only for Type 3 SS). Default is <code>FALSE</code></li>
<li><code>check_contrasts</code>: Logical variable indicating whether contrasts for factors should be checked and changed to <code>contr.sum</code> if they are not identical to <code>contr.sum</code>. Default is <code>TRUE</code>. You should set this to <code>FALSE</code> if you supply your own orthogonal contrasts.</li>
<li><code>expand_re</code>: Logical variable indicating whether random effect terms should be expanded (i.e. factors transformed into contrast-coding numerical predictors) before fitting with lmer. This allows proper use of the <code>||</code> notation with factors.</li>
</ul>
<p>Let’s try it out! First, let’s load the package:</p>
<div class="sourceCode" id="cb414"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb414-1"><a href="linear-mixed-effects-models.html#cb414-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(afex)</span></code></pre></div>
<p>Note that after loading the <code>afex</code> package, the <code>lmer</code> function from <code>lme4</code> will be “masked” and the corresponding function from the <code>afex</code> namespace will be used (it is actually the same as the one from the <code>lmertest</code> namespace), which is mostly the same, but expands the class of the returned object somewhat. Afterwards, you either have to use <code>lme4::lmer</code> whenever you explicitly want the function from the <code>lme4</code> package, or avoid loading the <code>afex</code> package, and always type e.g. <code>afex::mixed</code>. Either is fine, and mostly you wouldn’t need to worry, but sometimes the overriding of function names in the global workspace can give confusion and unexpected results, so it is good to be aware if this behaviour.</p>
<p>In the code below, I use the <code>mixed</code> function to estimate the model and compute <span class="math inline">\(p\)</span>-values for the fixed effect of <code>anchor</code> and the intercept with the default <code>"KR"</code> option (note that this takes some time!):</p>
<div class="sourceCode" id="cb415"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb415-1"><a href="linear-mixed-effects-models.html#cb415-1" aria-hidden="true" tabindex="-1"></a>afmodg <span class="ot">&lt;-</span> <span class="fu">mixed</span>(everest_feet <span class="sc">~</span> anchor <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">+</span> anchor<span class="sc">|</span>referrer), <span class="at">data=</span>anchoring, <span class="at">check_contrasts =</span> <span class="cn">FALSE</span>, <span class="at">test_intercept =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## Fitting one lmer() model. [DONE]
## Calculating p-values. [DONE]</code></pre>
<p>The class of the returned object saved as <code>afmodg</code> is different from the usual one returned by the <code>lmer</code> function. To get the <span class="math inline">\(F\)</span> tests, you can just type in the name of the object:</p>
<div class="sourceCode" id="cb417"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb417-1"><a href="linear-mixed-effects-models.html#cb417-1" aria-hidden="true" tabindex="-1"></a>afmodg</span></code></pre></div>
<pre><code>## Mixed Model Anova Table (Type 3 tests, S-method)
## 
## Model: everest_feet ~ anchor + (1 + anchor | referrer)
## Data: anchoring
##   Effect       df          F p.value
## 1 anchor 1, 27.32 428.58 ***   &lt;.001
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;+&#39; 0.1 &#39; &#39; 1</code></pre>
<p>You can also use the <code>summary()</code> function to obtain the parameter estimates (now with associated <span class="math inline">\(p\)</span>-values with the Satterthwaite approximation):</p>
<div class="sourceCode" id="cb419"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb419-1"><a href="linear-mixed-effects-models.html#cb419-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(afmodg)</span></code></pre></div>
<pre><code>## Linear mixed model fit by REML. t-tests use Satterthwaite&#39;s method [&#39;lmerModLmerTest&#39;]
## Formula: everest_feet ~ anchor + (1 + anchor | referrer)
##    Data: data
## 
## REML criterion at convergence: 97944.4
## 
## Scaled residuals: 
##     Min      1Q  Median      3Q     Max 
## -3.5558 -0.6374 -0.1029  0.6551  3.8431 
## 
## Random effects:
##  Groups   Name        Variance Std.Dev. Corr 
##  referrer (Intercept)  2470481 1572          
##           anchor1     36036021 6003     -0.80
##  Residual             87887265 9375          
## Number of obs: 4632, groups:  referrer, 31
## 
## Fixed effects:
##             Estimate Std. Error       df t value Pr(&gt;|t|)    
## (Intercept) 22840.77     329.42    27.49   69.34   &lt;2e-16 ***
## anchor1     23578.76    1138.95    27.32   20.70   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Correlation of Fixed Effects:
##         (Intr)
## anchor1 -0.658</code></pre>
<p>We can also estimate the model without correlation between the random effects as follows:</p>
<div class="sourceCode" id="cb421"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb421-1"><a href="linear-mixed-effects-models.html#cb421-1" aria-hidden="true" tabindex="-1"></a>afmodr <span class="ot">&lt;-</span> <span class="fu">mixed</span>(everest_feet <span class="sc">~</span> anchor <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">+</span> anchor<span class="sc">||</span>referrer), <span class="at">data=</span>anchoring, <span class="at">check_contrasts =</span> <span class="cn">FALSE</span>, <span class="at">test_intercept =</span> <span class="cn">TRUE</span>, <span class="at">expand_re =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## Fitting one lmer() model. [DONE]
## Calculating p-values. [DONE]</code></pre>
<p>and get the <span class="math inline">\(F\)</span> tests for this model:</p>
<div class="sourceCode" id="cb423"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb423-1"><a href="linear-mixed-effects-models.html#cb423-1" aria-hidden="true" tabindex="-1"></a>afmodr</span></code></pre></div>
<pre><code>## Mixed Model Anova Table (Type 3 tests, S-method)
## 
## Model: everest_feet ~ anchor + (1 + anchor || referrer)
## Data: anchoring
##   Effect       df          F p.value
## 1 anchor 1, 28.22 424.51 ***   &lt;.001
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;+&#39; 0.1 &#39; &#39; 1</code></pre>
<p>and parameter estimates</p>
<div class="sourceCode" id="cb425"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb425-1"><a href="linear-mixed-effects-models.html#cb425-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(afmodr)</span></code></pre></div>
<pre><code>## Linear mixed model fit by REML. t-tests use Satterthwaite&#39;s method [&#39;lmerModLmerTest&#39;]
## Formula: everest_feet ~ anchor + (1 + re1.anchor1 || referrer)
##    Data: data
## 
## REML criterion at convergence: 97960.2
## 
## Scaled residuals: 
##     Min      1Q  Median      3Q     Max 
## -3.6330 -0.6464 -0.1011  0.6732  3.8333 
## 
## Random effects:
##  Groups     Name        Variance Std.Dev.
##  referrer   (Intercept)  2350312 1533    
##  referrer.1 re1.anchor1 36126381 6011    
##  Residual               87899463 9375    
## Number of obs: 4632, groups:  referrer, 31
## 
## Fixed effects:
##             Estimate Std. Error       df t value Pr(&gt;|t|)    
## (Intercept) 22773.65     326.69    29.08   69.71   &lt;2e-16 ***
## anchor1     23526.08    1141.84    28.22   20.60   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Correlation of Fixed Effects:
##         (Intr)
## anchor1 0.011</code></pre>
<p><strong>Note</strong> that entering the two models as is into the <code>anova</code> function <strong>will not</strong> provide the desired re-estimation of the models by maximum likelihood:</p>
<div class="sourceCode" id="cb427"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb427-1"><a href="linear-mixed-effects-models.html#cb427-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(afmodr,afmodg)</span></code></pre></div>
<pre><code>## Data: data
## Models:
## afmodr: everest_feet ~ anchor + (1 + re1.anchor1 || referrer)
## afmodg: everest_feet ~ anchor + (1 + anchor | referrer)
##        npar   AIC   BIC logLik deviance  Chisq Df Pr(&gt;Chisq)    
## afmodr    5 97970 98002 -48980    97960                         
## afmodg    6 97956 97995 -48972    97944 15.781  1  7.111e-05 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>and this is not clear from the output (apart from the missing <code>refitting model(s) with ML (instead of REML)</code> message). For the correct results, you will need to provide the <code>lmer</code> model, stored in the <code>afmodr</code> and <code>afmodg</code> objects under <code>$full_model</code>:</p>
<div class="sourceCode" id="cb429"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb429-1"><a href="linear-mixed-effects-models.html#cb429-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(afmodr<span class="sc">$</span>full_model, afmodg<span class="sc">$</span>full_model)</span></code></pre></div>
<pre><code>## Data: data
## Models:
## afmodr$full_model: everest_feet ~ anchor + (1 + re1.anchor1 || referrer)
## afmodg$full_model: everest_feet ~ anchor + (1 + anchor | referrer)
##                   npar   AIC   BIC logLik deviance  Chisq Df Pr(&gt;Chisq)    
## afmodr$full_model    5 98000 98032 -48995    97990                         
## afmodg$full_model    6 97985 98024 -48987    97973 16.339  1  5.296e-05 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Although the differences are small, the first test compares the “-2 log REML,” instead of the desired “-2 log ML” values. The assumptions underlying the likelihood-ratio test require the latter.</p>

</div>
</div>
<h3>References</h3>
<div id="refs" class="references csl-bib-body hanging-indent">
<div id="ref-R-lme4" class="csl-entry">
Bates, Douglas, Martin Maechler, Ben Bolker, and Steven Walker. 2021. <em>Lme4: Linear Mixed-Effects Models Using Eigen and S4</em>. <a href="https://github.com/lme4/lme4/">https://github.com/lme4/lme4/</a>.
</div>
<div id="ref-R-pbkrtest" class="csl-entry">
Højsgaard, Ulrich Halekoh Søren. 2020. <em>Pbkrtest: Parametric Bootstrap and Kenward Roger Based Methods for Mixed Model Comparison</em>. <a href="http://people.math.aau.dk/~sorenh/software/pbkrtest/">http://people.math.aau.dk/~sorenh/software/pbkrtest/</a>.
</div>
<div id="ref-R-lmerTest" class="csl-entry">
Kuznetsova, Alexandra, Per Bruun Brockhoff, and Rune Haubo Bojesen Christensen. 2020. <em>lmerTest: Tests in Linear Mixed Effects Models</em>. <a href="https://github.com/runehaubo/lmerTestR">https://github.com/runehaubo/lmerTestR</a>.
</div>
<div id="ref-R-afex" class="csl-entry">
Singmann, Henrik, Ben Bolker, Jake Westfall, Frederik Aust, and Mattan S. Ben-Shachar. 2021. <em>Afex: Analysis of Factorial Experiments</em>. <a href="https://CRAN.R-project.org/package=afex">https://CRAN.R-project.org/package=afex</a>.
</div>
<div id="ref-Singmann2019-mixed" class="csl-entry">
Singmann, Henrik, and David Kellen. 2019. <span>“An Introduction to Linear Mixed Modeling in Experimental Psychology.”</span> In <em>New Methods in Cognitive Psychology</em>, 4–31. Psychology Press. <a href="http://singmann.org/download/publications/singmann_kellen-introduction-mixed-models.pdf, preprint">http://singmann.org/download/publications/singmann_kellen-introduction-mixed-models.pdf, preprint</a>.
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="repeated-measures-anova.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="bayesian-hypothesis-testing-through-bayes-factors.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="book_assets/gitbook-2.6.7/js/app.min.js"></script>
<script src="book_assets/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="book_assets/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="book_assets/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="book_assets/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="book_assets/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="book_assets/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="book_assets/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": null,
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
},
"source": null
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
